// 関西〜沖縄
COMPANIES.push(
  // ========== 三重 / MIE ==========
  {i:"me001",ja:"伊勢角屋麦酒",en:"Ise Kadoya Beer",pref:"mie",cat:"sake",desc_ja:"伊勢の老舗クラフトビール",desc_en:"Heritage Ise craft beer",verified:true},
  {i:"me002",ja:"赤福",en:"Akafuku",pref:"mie",cat:"food",desc_ja:"伊勢神宮門前の老舗餅菓子",desc_en:"Ise Shrine heritage mochi sweet",verified:true},
  {i:"me003",ja:"へんばや商店",en:"Henbaya",pref:"mie",cat:"food",desc_ja:"伊勢のへんば餅老舗",desc_en:"Heritage Ise henba mochi",verified:true},
  {i:"me004",ja:"丸彦製菓",en:"Maruhiko Confectionery",pref:"mie",cat:"food",desc_ja:"伊勢の煎餅老舗",desc_en:"Heritage Ise senbei",deleted:true},
  {i:"me005",ja:"ミキモト真珠養殖",en:"Mikimoto Pearl Farm",pref:"mie",cat:"craft",desc_ja:"鳥羽の真珠養殖発祥",desc_en:"Toba pearl-farming origin",verified:true},
  {i:"me006",ja:"伊勢志摩真珠 田崎工房",en:"Tasaki Pearl Atelier",pref:"mie",cat:"craft",desc_ja:"伊勢志摩の真珠加工",desc_en:"Ise-Shima pearl atelier"},
  {i:"me007",ja:"伊勢型紙 おおすぎ",en:"Osugi Ise Katagami",pref:"mie",cat:"paper",desc_ja:"鈴鹿の伊勢型紙工房",desc_en:"Suzuka Ise katagami atelier",verified:true},
  {i:"me008",ja:"伊勢木綿 臼井織布",en:"Usui Orifu Ise Momen",pref:"mie",cat:"apparel",desc_ja:"伊勢木綿の唯一の織元",desc_en:"Sole Ise momen weaver",verified:true},
  {i:"me009",ja:"四日市萬古焼 中川源助",en:"Nakagawa Genjyu Banko",pref:"mie",cat:"glass",desc_ja:"四日市萬古焼の窯元",desc_en:"Yokkaichi Banko-yaki kiln",deleted:true},
  {i:"me010",ja:"萬古急須 山口陶器",en:"Yamaguchi Banko Kyusu",pref:"mie",cat:"glass",desc_ja:"萬古焼の紫泥急須",desc_en:"Banko purple-clay teapot"},
  {i:"me011",ja:"鈴鹿墨 進誠堂",en:"Shinseido Suzuka Sumi",pref:"mie",cat:"craft",desc_ja:"鈴鹿墨の老舗",desc_en:"Heritage Suzuka ink maker"},
  {i:"me012",ja:"伊賀焼 長谷園",en:"Nagatani-en Iga-yaki",pref:"mie",cat:"glass",desc_ja:"伊賀焼の老舗、かまどさん",desc_en:"Heritage Iga-yaki, Kamado-san",verified:true},
  {i:"me013",ja:"伊賀くみひも 松山",en:"Matsuyama Iga Kumihimo",pref:"mie",cat:"craft",desc_ja:"伊賀組紐の老舗",desc_en:"Heritage Iga kumihimo",deleted:true},
  {i:"me014",ja:"半蔵酒造 (大田酒造)",en:"Ota Brewery (Hanzo)",pref:"mie",cat:"sake",desc_ja:"伊賀の半蔵蔵元",desc_en:"Iga brewer of Hanzo",verified:true},
  {i:"me015",ja:"清水清三郎商店",en:"Shimizu Seizaburo (Zaku)",pref:"mie",cat:"sake",desc_ja:"鈴鹿の作 (ザク)蔵元",desc_en:"Suzuka brewer of Zaku",verified:true},
  {i:"me016",ja:"早川酒造 (田光)",en:"Hayakawa Brewery",pref:"mie",cat:"sake",desc_ja:"四日市の地酒、田光",desc_en:"Yokkaichi brewer of Tabika",verified:true},
  {i:"me017",ja:"志摩水産 真鯛養殖",en:"Shima Suisan",pref:"mie",cat:"food",desc_ja:"志摩の養殖真鯛・海産",desc_en:"Shima farmed sea bream",deleted:true},
  {i:"me018",ja:"松阪牛 田村",en:"Tamura Matsusaka Beef",pref:"mie",cat:"food",desc_ja:"松阪牛の老舗",desc_en:"Heritage Matsusaka beef",deleted:true},
  {i:"me019",ja:"四日市プラスチック工業",en:"Yokkaichi Plastic Industry",pref:"mie",cat:"other",desc_ja:"中小プラスチック成形",desc_en:"SME plastic molding"},
  {i:"me020",ja:"伊勢茶 かぶせ茶 深緑茶房",en:"Fukamidori Chabo Iseca",pref:"mie",cat:"tea",desc_ja:"伊勢茶のかぶせ茶老舗",desc_en:"Heritage Ise kabusecha"},
  {i:"me021",ja:"三重特許応用ラボ",en:"Mie Patent Lab",pref:"mie",cat:"patent",desc_ja:"特許応用の試作開発",desc_en:"Patent applied R&D",deleted:true},
  {i:"me022",ja:"鳥羽水産加工",en:"Toba Seafood Processing",pref:"mie",cat:"food",desc_ja:"鳥羽の水産加工",desc_en:"Toba seafood processor",deleted:true},

  // ========== 滋賀 / SHIGA ==========
  {i:"sg001",ja:"信楽焼 明山陶業",en:"Meizan Shigaraki",pref:"shiga",cat:"glass",desc_ja:"信楽焼の老舗窯元",desc_en:"Heritage Shigaraki-yaki kiln",verified:true},
  {i:"sg002",ja:"信楽焼 古谷製陶所",en:"Furutani Shigaraki",pref:"shiga",cat:"glass",desc_ja:"信楽焼の現代陶器",desc_en:"Modern Shigaraki pottery",verified:true},
  {i:"sg003",ja:"信楽焼 大小屋",en:"Daikoya Shigaraki",pref:"shiga",cat:"glass",desc_ja:"信楽焼の窯元グループ",desc_en:"Shigaraki kiln group"},
  {i:"sg004",ja:"近江上布 麻織物 (近江布振興)",en:"Omi Jofu Asa",pref:"shiga",cat:"apparel",desc_ja:"近江上布の伝統麻織物",desc_en:"Omi jofu traditional hemp",deleted:true},
  {i:"sg005",ja:"高島ちぢみ",en:"Takashima Chijimi",pref:"shiga",cat:"apparel",desc_ja:"高島の伝統綿織物",desc_en:"Takashima traditional cotton crepe",deleted:true},
  {i:"sg006",ja:"近江牛 千成亭",en:"Sennaritei Omi Beef",pref:"shiga",cat:"food",desc_ja:"彦根の近江牛老舗",desc_en:"Hikone Omi beef heritage"},
  {i:"sg007",ja:"つるやパン",en:"Tsuruya Pan",pref:"shiga",cat:"food",desc_ja:"長浜のサラダパン老舗",desc_en:"Nagahama salad bread maker",verified:true},
  {i:"sg008",ja:"叶 匠寿庵",en:"Kano Shojuan",pref:"shiga",cat:"food",desc_ja:"大津の和菓子老舗",desc_en:"Otsu heritage wagashi",verified:true},
  {i:"sg009",ja:"クラブハリエ",en:"Club Harie",pref:"shiga",cat:"food",desc_ja:"近江八幡のバウムクーヘン",desc_en:"Omihachiman baumkuchen",verified:true},
  {i:"sg010",ja:"たねや",en:"Taneya",pref:"shiga",cat:"food",desc_ja:"近江八幡の老舗和菓子",desc_en:"Heritage Omihachiman wagashi",verified:true},
  {i:"sg011",ja:"近江醸造 (滋賀醤油)",en:"Omi Brewing Soy",pref:"shiga",cat:"food",desc_ja:"近江の醤油・味噌老舗",desc_en:"Omi heritage soy & miso",deleted:true},
  {i:"sg012",ja:"福井弥平商店 (萩乃露)",en:"Fukui Yahei (Hagi no Tsuyu)",pref:"shiga",cat:"sake",desc_ja:"高島の老舗酒蔵",desc_en:"Takashima heritage sake brewer",verified:true},
  {i:"sg013",ja:"喜多酒造 (喜楽長)",en:"Kita Brewery (Kirakucho)",pref:"shiga",cat:"sake",desc_ja:"東近江の地酒蔵",desc_en:"Higashi-Omi local sake",verified:true},
  {i:"sg014",ja:"冨田酒造 (七本鎗)",en:"Tomita Brewery",pref:"shiga",cat:"sake",desc_ja:"長浜の七本鎗蔵元",desc_en:"Nagahama brewer of Shichihonyari",verified:true},
  {i:"sg015",ja:"安土水産 鮒寿司",en:"Azuchi Funa-zushi",pref:"shiga",cat:"food",desc_ja:"近江の鮒寿司老舗",desc_en:"Heritage Omi funa-zushi",deleted:true},
  {i:"sg016",ja:"近江仏壇 大津店",en:"Omi Butsudan",pref:"shiga",cat:"craft",desc_ja:"彦根の伝統仏壇",desc_en:"Hikone traditional altar",deleted:true},
  {i:"sg017",ja:"湖東和紙工房",en:"Koto Washi",pref:"shiga",cat:"paper",desc_ja:"湖東地方の伝統和紙",desc_en:"Koto region traditional washi",deleted:true},
  {i:"sg018",ja:"滋賀健康食品",en:"Shiga Health Food",pref:"shiga",cat:"supplement",desc_ja:"湖国の機能性食品",desc_en:"Shiga functional food maker",deleted:true},

  // ========== 京都 / KYOTO ==========
  {i:"ky001",ja:"西陣織 細尾",en:"Hosoo Nishijin",pref:"kyoto",cat:"apparel",desc_ja:"西陣織の革新企業",desc_en:"Innovative Nishijin weaver",verified:true},
  {i:"ky002",ja:"西陣織 川島織物セルコン",en:"Kawashima Selkon Nishijin",pref:"kyoto",cat:"apparel",desc_ja:"西陣織の老舗",desc_en:"Heritage Nishijin weaver",verified:true},
  {i:"ky003",ja:"西陣 渡文",en:"Watabun Nishijin",pref:"kyoto",cat:"apparel",desc_ja:"西陣織の名門",desc_en:"Famed Nishijin weaver"},
  {i:"ky004",ja:"西陣 山口源兵衛 (誉田屋)",en:"Kondaya Genbei",pref:"kyoto",cat:"apparel",desc_ja:"西陣の帯老舗",desc_en:"Heritage Nishijin obi sash",verified:true},
  {i:"ky005",ja:"龍村美術織物",en:"Tatsumura Textile",pref:"kyoto",cat:"apparel",desc_ja:"西陣の高級織物",desc_en:"Premium Nishijin textile",verified:true},
  {i:"ky006",ja:"京友禅 千總",en:"Chiso Kyoto Yuzen",pref:"kyoto",cat:"apparel",desc_ja:"京友禅の老舗",desc_en:"Heritage Kyo-yuzen",verified:true},
  {i:"ky007",ja:"京友禅 高橋徳",en:"Takahashi Toku Yuzen",pref:"kyoto",cat:"apparel",desc_ja:"京友禅の伝統工房",desc_en:"Kyo-yuzen atelier"},
  {i:"ky008",ja:"京鹿の子絞 京絞美苑",en:"Bien Kyoto Shibori",pref:"kyoto",cat:"apparel",desc_ja:"京鹿の子絞り工房",desc_en:"Kyo kanoko shibori atelier",deleted:true},
  {i:"ky009",ja:"京うちわ 阿以波",en:"Aiba Kyo-uchiwa",pref:"kyoto",cat:"craft",desc_ja:"京うちわの老舗",desc_en:"Heritage Kyo uchiwa fan",verified:true},
  {i:"ky010",ja:"京扇子 宮脇賣扇庵",en:"Miyawaki Baisenan",pref:"kyoto",cat:"craft",desc_ja:"京扇子の老舗",desc_en:"Heritage Kyo folding fan",verified:true},
  {i:"ky011",ja:"京扇子 白竹堂",en:"Hakuchikudo",pref:"kyoto",cat:"craft",desc_ja:"京扇子の老舗",desc_en:"Heritage Kyo folding fan",verified:true},
  {i:"ky012",ja:"清水焼 朝日堂",en:"Asahido Kiyomizu",pref:"kyoto",cat:"glass",desc_ja:"清水焼の老舗",desc_en:"Heritage Kiyomizu-yaki",verified:true},
  {i:"ky013",ja:"清水焼 河井寛次郎窯",en:"Kawai Kanjiro Kiln",pref:"kyoto",cat:"glass",desc_ja:"清水焼の名陶窯",desc_en:"Famed Kiyomizu kiln",verified:true,deleted:true},
  {i:"ky014",ja:"清水焼 京焼 陶磁器試作",en:"Kyo-yaki Atelier",pref:"kyoto",cat:"glass",desc_ja:"清水・京焼の窯元組合",desc_en:"Kyo-yaki kiln cooperative"},
  {i:"ky015",ja:"京和傘 日吉屋",en:"Hiyoshiya Wagasa",pref:"kyoto",cat:"craft",desc_ja:"京和傘の老舗",desc_en:"Heritage Kyoto wagasa",verified:true},
  {i:"ky016",ja:"京漆器 象彦",en:"Zohiko Kyo-shikki",pref:"kyoto",cat:"craft",desc_ja:"京漆器の老舗",desc_en:"Heritage Kyo lacquerware",verified:true},
  {i:"ky017",ja:"象彦",en:"Nakajima Zohiko",pref:"kyoto",cat:"craft",desc_ja:"京漆器の伝統工房",desc_en:"Kyo lacquerware atelier"},
  {i:"ky018",ja:"京組紐 安達",en:"Adachi Kyo Kumihimo",pref:"kyoto",cat:"craft",desc_ja:"京組紐の伝統工房",desc_en:"Kyo kumihimo atelier"},
  {i:"ky019",ja:"京数珠 安田念珠店",en:"Yasuda Juzu",pref:"kyoto",cat:"craft",desc_ja:"京数珠の老舗",desc_en:"Heritage Kyoto juzu beads",verified:true},
  {i:"ky020",ja:"京人形 川瀬猪山",en:"Kawase Inoyama Doll",pref:"kyoto",cat:"craft",desc_ja:"京人形の伝統工房",desc_en:"Kyo doll atelier"},
  {i:"ky021",ja:"京銘竹 公長齋小菅",en:"Kohchosai Kosuga Bamboo",pref:"kyoto",cat:"craft",desc_ja:"京銘竹の竹工芸",desc_en:"Kyo meichiku bamboo craft",verified:true},
  {i:"ky022",ja:"京菓子 鶴屋吉信",en:"Tsuruya Yoshinobu",pref:"kyoto",cat:"food",desc_ja:"京菓子の老舗",desc_en:"Heritage Kyoto wagashi",verified:true},
  {i:"ky023",ja:"京菓子 とらや京都",en:"Toraya Kyoto",pref:"kyoto",cat:"food",desc_ja:"京の老舗和菓子",desc_en:"Heritage Kyoto wagashi",verified:true},
  {i:"ky024",ja:"老松",en:"Oimatsu",pref:"kyoto",cat:"food",desc_ja:"北野天満宮の和菓子",desc_en:"Kitano Tenmangu wagashi heritage",verified:true},
  {i:"ky025",ja:"末富 (京菓子)",en:"Suetomi",pref:"kyoto",cat:"food",desc_ja:"京菓子の老舗末富",desc_en:"Heritage Kyoto wagashi Suetomi",verified:true},
  {i:"ky026",ja:"七條甘春堂",en:"Shichijo Kanshundo",pref:"kyoto",cat:"food",desc_ja:"京菓子老舗、和菓子作り体験",desc_en:"Heritage Kyoto wagashi class",verified:true},
  {i:"ky027",ja:"中村藤吉本店",en:"Nakamura Tokichi",pref:"kyoto",cat:"tea",desc_ja:"宇治茶の老舗、抹茶スイーツ",desc_en:"Heritage Uji tea & matcha sweets",verified:true},
  {i:"ky028",ja:"伊藤久右衛門",en:"Ito Kyuemon",pref:"kyoto",cat:"tea",desc_ja:"宇治抹茶の老舗",desc_en:"Heritage Uji matcha",verified:true},
  {i:"ky029",ja:"丸久小山園",en:"Marukyu Koyamaen",pref:"kyoto",cat:"tea",desc_ja:"宇治抹茶の最高級老舗",desc_en:"Premium Uji matcha heritage",verified:true},
  {i:"ky030",ja:"森半 (共栄製茶)",en:"Morihan",pref:"kyoto",cat:"tea",desc_ja:"宇治抹茶の老舗",desc_en:"Heritage Uji matcha",verified:true},
  {i:"ky031",ja:"祇園辻利",en:"Gion Tsujiri",pref:"kyoto",cat:"tea",desc_ja:"祇園の抹茶老舗",desc_en:"Heritage Gion matcha",verified:true},
  {i:"ky032",ja:"福寿園",en:"Fukujuen",pref:"kyoto",cat:"tea",desc_ja:"宇治茶の老舗",desc_en:"Heritage Uji tea",verified:true},
  {i:"ky033",ja:"一保堂茶舗",en:"Ippodo Tea",pref:"kyoto",cat:"tea",desc_ja:"京都の老舗茶舗",desc_en:"Heritage Kyoto tea house",verified:true},
  {i:"ky034",ja:"よーじや",en:"Yojiya",pref:"kyoto",cat:"cosmetics",desc_ja:"あぶらとり紙の老舗",desc_en:"Heritage aburatorigami (oil blotter)",verified:true},
  {i:"ky035",ja:"舞妓夢こすめ",en:"Maiko Yume Cosme",pref:"kyoto",cat:"cosmetics",desc_ja:"京都発舞妓化粧品ブランド",desc_en:"Kyoto maiko cosmetics brand",deleted:true},
  {i:"ky036",ja:"京コスメ 白鳳堂 (筆)",en:"Hakuhodo Brush Kyoto",pref:"kyoto",cat:"cosmetics",desc_ja:"化粧筆の名門",desc_en:"Famed cosmetic brush maker",verified:true},
  {i:"ky037",ja:"株式会社クラブコスメチックス",en:"Club Cosmetics Kyoto",pref:"osaka",cat:"cosmetics",desc_ja:"京都発化粧品老舗",desc_en:"Heritage Kyoto cosmetics"},
  {i:"ky038",ja:"NEMOHAMO",en:"Nemohamo",pref:"kyoto",cat:"cosmetics",desc_ja:"京都オーガニックコスメ",desc_en:"Kyoto organic cosmetics brand",verified:true},
  {i:"ky039",ja:"アヤ ナチュラルプロダクツ",en:"Aya Natural Products",pref:"kyoto",cat:"cosmetics",desc_ja:"京都の自然派コスメ",desc_en:"Kyoto natural cosmetics",deleted:true},
  {i:"ky040",ja:"舞妓はん",en:"Maikohan",pref:"kyoto",cat:"cosmetics",desc_ja:"京都発おしろい・コスメ",desc_en:"Kyoto powder & cosmetics",verified:true},
  {i:"ky041",ja:"月桂冠",en:"Gekkeikan",pref:"kyoto",cat:"sake",desc_ja:"伏見の老舗酒蔵",desc_en:"Heritage Fushimi sake brewer",verified:true},
  {i:"ky042",ja:"招德酒造",en:"Shotoku Brewery",pref:"kyoto",cat:"sake",desc_ja:"伏見の中小酒蔵",desc_en:"Fushimi small sake brewer",verified:true},
  {i:"ky043",ja:"佐々木酒造",en:"Sasaki Brewery",pref:"kyoto",cat:"sake",desc_ja:"京都市内唯一の市中蔵",desc_en:"Sole brewer in Kyoto city core",verified:true},
  {i:"ky044",ja:"松井酒造",en:"Matsui Brewery",pref:"kyoto",cat:"sake",desc_ja:"京都の老舗酒蔵",desc_en:"Heritage Kyoto sake brewer"},
  {i:"ky045",ja:"齊藤酒造 (英勲)",en:"Saito Brewery (Eikun)",pref:"kyoto",cat:"sake",desc_ja:"伏見の蔵元、英勲",desc_en:"Fushimi brewer of Eikun",verified:true},
  {i:"ky046",ja:"玉乃光酒造",en:"Tamanohikari",pref:"kyoto",cat:"sake",desc_ja:"伏見の純米酒蔵",desc_en:"Fushimi all-junmai brewer",verified:true},
  {i:"ky047",ja:"京野菜加工 京漬物 西利",en:"Nishiri Kyo Tsukemono",pref:"kyoto",cat:"food",desc_ja:"京漬物の老舗",desc_en:"Heritage Kyoto pickles",verified:true},
  {i:"ky048",ja:"京つけもの 大安",en:"Daiyasu Kyo Tsukemono",pref:"kyoto",cat:"food",desc_ja:"京漬物の老舗",desc_en:"Heritage Kyoto pickles",verified:true},
  {i:"ky049",ja:"打田漬物",en:"Uchida Tsukemono",pref:"kyoto",cat:"food",desc_ja:"錦市場の漬物老舗",desc_en:"Nishiki Market pickle heritage"},
  {i:"ky050",ja:"半兵衛麸",en:"Hanbey Fu",pref:"kyoto",cat:"food",desc_ja:"京麸の老舗",desc_en:"Heritage Kyoto fu (wheat gluten)",verified:true},
  {i:"ky051",ja:"麸嘉",en:"Fuka",pref:"kyoto",cat:"food",desc_ja:"京生麸の老舗",desc_en:"Heritage Kyoto raw fu",verified:true},
  {i:"ky052",ja:"湯豆腐 順正",en:"Junsei Tofu",pref:"kyoto",cat:"food",desc_ja:"南禅寺の湯豆腐老舗",desc_en:"Nanzenji yudofu heritage"},
  {i:"ky053",ja:"老舗豆腐 嵯峨豆腐 森嘉",en:"Morika Saga Tofu",pref:"kyoto",cat:"food",desc_ja:"嵯峨の老舗豆腐",desc_en:"Heritage Saga tofu",verified:true},
  {i:"ky054",ja:"村山造酢 (千鳥酢)",en:"Murayama Vinegar",pref:"kyoto",cat:"food",desc_ja:"京都の千鳥酢老舗",desc_en:"Heritage Chidori vinegar Kyoto",verified:true},
  {i:"ky055",ja:"井筒八ッ橋本舗",en:"Izutsu Yatsuhashi",pref:"kyoto",cat:"food",desc_ja:"京銘菓 八ッ橋の老舗",desc_en:"Heritage Kyoto yatsuhashi",verified:true},
  {i:"ky056",ja:"聖護院八ッ橋総本店",en:"Shogoin Yatsuhashi",pref:"kyoto",cat:"food",desc_ja:"八ッ橋元祖の老舗",desc_en:"Yatsuhashi origin heritage",verified:true},
  {i:"ky057",ja:"井和井 (京和雑貨)",en:"Iwai Kyoto Goods",pref:"kyoto",cat:"craft",desc_ja:"京都和雑貨の老舗",desc_en:"Heritage Kyoto Japanese goods"},
  {i:"ky058",ja:"京焼陶磁器 雅楽窯",en:"Gagaku Kiln Kyo-yaki",pref:"kyoto",cat:"glass",desc_ja:"京焼の窯元",desc_en:"Kyoto pottery kiln"},
  {i:"ky059",ja:"京香原 香老舗 松栄堂",en:"Shoyeido Incense",pref:"kyoto",cat:"craft",desc_ja:"京都香の老舗",desc_en:"Heritage Kyoto incense",verified:true},
  {i:"ky060",ja:"京香 山田松香木店",en:"Yamadamatsu Incense",pref:"kyoto",cat:"craft",desc_ja:"香木専門の老舗",desc_en:"Heritage incense wood specialist",verified:true},

  // ========== 大阪 / OSAKA ==========
  {i:"os001",ja:"堺打刃物 森本刃物",en:"Morimoto Sakai Hamono",pref:"osaka",cat:"cutlery",desc_ja:"堺打刃物の老舗",desc_en:"Heritage Sakai forged blades",deleted:true},
  {i:"os002",ja:"堺一文字光秀",en:"Sakai Ichimonji Mitsuhide",pref:"osaka",cat:"cutlery",desc_ja:"堺の包丁老舗",desc_en:"Heritage Sakai knife maker",verified:true},
  {i:"os003",ja:"堺孝行刃物",en:"Sakai Takayuki",pref:"osaka",cat:"cutlery",desc_ja:"堺打刃物の代表",desc_en:"Representative Sakai knife",verified:true},
  {i:"os004",ja:"堺打刃物 山脇刃物製作所",en:"Yamawaki Hamono",pref:"osaka",cat:"cutlery",desc_ja:"堺の包丁老舗",desc_en:"Heritage Sakai knives"},
  {i:"os005",ja:"堺打刃物 青木刃物製作所",en:"Aoki Hamono",pref:"osaka",cat:"cutlery",desc_ja:"堺の包丁鍛冶",desc_en:"Sakai blade smithy",verified:true},
  {i:"os006",ja:"堺刃物協同組合",en:"Sakai Cutlery Coop",pref:"osaka",cat:"cutlery",desc_ja:"堺刃物の組合",desc_en:"Sakai cutlery cooperative"},
  {i:"os007",ja:"千成屋珈琲 (大阪の老舗)",en:"Sennariya Coffee",pref:"osaka",cat:"food",desc_ja:"新世界の老舗珈琲",desc_en:"Shinsekai heritage coffee"},
  {i:"os008",ja:"鶴橋風月",en:"Tsuruhashi Fugetsu",pref:"osaka",cat:"food",desc_ja:"鶴橋お好み焼老舗",desc_en:"Tsuruhashi okonomiyaki heritage"},
  {i:"os009",ja:"赤福以外 喜八洲総本舗",en:"Kiyasu Sohonpo",pref:"osaka",cat:"food",desc_ja:"大阪のみたらし団子老舗",desc_en:"Osaka heritage mitarashi",verified:true},
  {i:"os010",ja:"千鳥屋宗家",en:"Chidoriya Soke",pref:"hyogo",cat:"food",desc_ja:"和菓子の老舗（本社は西宮・本店は大阪中央区）",desc_en:"Heritage wagashi maker, HQ in Nishinomiya",verified:true},
  {i:"os011",ja:"五穀屋 (老舗)",en:"Gokokuya Osaka",pref:"osaka",cat:"food",desc_ja:"和菓子の老舗",desc_en:"Heritage wagashi shop",deleted:true},
  {i:"os012",ja:"高麗食品",en:"Korai Foods",pref:"osaka",cat:"food",desc_ja:"鶴橋のキムチ老舗",desc_en:"Tsuruhashi kimchi heritage"},
  {i:"os013",ja:"ハクション大魔王 食品 (鴻商店)",en:"Otori Shoten Foods",pref:"osaka",cat:"food",desc_ja:"大阪の食品OEM",desc_en:"Osaka food OEM"},
  {i:"os014",ja:"江崎べっ甲店 (大阪)",en:"Esaki Bekko Osaka",pref:"osaka",cat:"craft",desc_ja:"大阪の鼈甲老舗",desc_en:"Osaka heritage bekko",deleted:true},
  {i:"os015",ja:"和泉櫛 (大阪)",en:"Izumi Kushi",pref:"osaka",cat:"craft",desc_ja:"つげ櫛の老舗",desc_en:"Boxwood comb heritage",deleted:true},
  {i:"os016",ja:"大阪欄間 木下欄間",en:"Kinoshita Ranma",pref:"osaka",cat:"wood",desc_ja:"大阪欄間の伝統工芸",desc_en:"Osaka ranma transom craft"},
  {i:"os017",ja:"大阪唐木指物",en:"Osaka Karaki Sashimono",pref:"osaka",cat:"wood",desc_ja:"大阪唐木指物の工房",desc_en:"Osaka karaki joinery atelier"},
  {i:"os018",ja:"大阪錫器 すずや",en:"Suzuya Tin Osaka",pref:"osaka",cat:"craft",desc_ja:"大阪錫器の伝統工房",desc_en:"Osaka tinware atelier"},
  {i:"os019",ja:"大阪仏壇 大久",en:"Daikyu Osaka Butsudan",pref:"osaka",cat:"craft",desc_ja:"大阪仏壇の伝統工房",desc_en:"Osaka altar atelier",deleted:true},
  {i:"os020",ja:"泉州タオル ホットマン",en:"Hotman Senshu Towel",pref:"osaka",cat:"apparel",desc_ja:"泉州タオルの老舗",desc_en:"Heritage Senshu towel maker",deleted:true},
  {i:"os021",ja:"泉州タオル 高田織物",en:"Takada Senshu Towel",pref:"osaka",cat:"apparel",desc_ja:"泉州タオルの織物",desc_en:"Senshu towel maker",deleted:true},
  {i:"os022",ja:"泉州毛布 河田フェザー",en:"Kawada Mōfu",pref:"osaka",cat:"apparel",desc_ja:"泉州毛布の老舗",desc_en:"Heritage Senshu blanket maker",deleted:true},
  {i:"os023",ja:"大阪電子部品技研",en:"Osaka Electron Lab",pref:"osaka",cat:"electronics",desc_ja:"大阪の電子部品試作",desc_en:"Osaka electronic prototyping",deleted:true},
  {i:"os024",ja:"東大阪精密プレス",en:"Higashi-Osaka Precision",pref:"osaka",cat:"electronics",desc_ja:"東大阪の精密板金",desc_en:"Higashi-Osaka precision pressing",deleted:true},
  {i:"os025",ja:"東大阪ねじ・ばね",en:"Higashi-Osaka Screws",pref:"osaka",cat:"other",desc_ja:"東大阪のねじ・ばね",desc_en:"Higashi-Osaka screws & springs",deleted:true},
  {i:"os026",ja:"東大阪 金型試作",en:"Higashi-Osaka Mold Lab",pref:"osaka",cat:"patent",desc_ja:"金型・特許応用試作",desc_en:"Tool & die patent prototyping",deleted:true},
  {i:"os027",ja:"オージーケーカブト (ヘルメット)",en:"OGK Kabuto",pref:"osaka",cat:"patent",desc_ja:"東大阪のヘルメット技術",desc_en:"Higashi-Osaka helmet patents",verified:true},
  {i:"os028",ja:"大同 (鉛筆ぼんぽん)",en:"Daido Pencil",pref:"osaka",cat:"other",desc_ja:"大阪の鉛筆メーカー",desc_en:"Osaka pencil maker",deleted:true},
  {i:"os029",ja:"千鳥饅頭総本舗",en:"Chidori Manju",pref:"osaka",cat:"food",desc_ja:"大阪老舗の饅頭",desc_en:"Heritage Osaka manju"},
  {i:"os030",ja:"竹中本舗 (お茶)",en:"Takenaka Tea Osaka",pref:"osaka",cat:"tea",desc_ja:"大阪のお茶問屋老舗",desc_en:"Heritage Osaka tea wholesaler",deleted:true},
  {i:"os031",ja:"大阪コスメティクス (OEM)",en:"Osaka Cosmetics OEM",pref:"osaka",cat:"cosmetics",desc_ja:"大阪の化粧品OEM中堅",desc_en:"Mid-size Osaka cosmetics OEM",deleted:true},
  {i:"os032",ja:"大阪サプリ研究所",en:"Osaka Supplement Lab",pref:"osaka",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"os033",ja:"秋鹿酒造",en:"Akishika Brewery",pref:"osaka",cat:"sake",desc_ja:"能勢の地酒蔵",desc_en:"Nose local sake brewer",verified:true},
  {i:"os034",ja:"西條合資会社 (天野酒)",en:"Saijo Brewery (Amano)",pref:"osaka",cat:"sake",desc_ja:"河内長野の天野酒",desc_en:"Kawachi-Nagano brewer of Amano",verified:true},
  {i:"os035",ja:"利休蔵 (大阪市内)",en:"Rikyu Brewery Osaka",pref:"osaka",cat:"sake",desc_ja:"大阪の小規模蔵元",desc_en:"Small Osaka sake brewery"},
  {i:"os036",ja:"カラフトオウム (鞄)",en:"Karafuto Owl Bags",pref:"osaka",cat:"leather",desc_ja:"大阪の革鞄工房",desc_en:"Osaka leather bag atelier",deleted:true},
  {i:"os037",ja:"住吉スリッパ",en:"Sumiyoshi Slipper",pref:"osaka",cat:"apparel",desc_ja:"大阪の伝統スリッパ",desc_en:"Osaka traditional slipper",deleted:true},
  {i:"os038",ja:"大阪欄間組合",en:"Osaka Ranma Coop",pref:"osaka",cat:"wood",desc_ja:"大阪欄間の組合",desc_en:"Osaka ranma cooperative"},
  {i:"os039",ja:"大阪木綿 河内木綿",en:"Kawachi Cotton",pref:"osaka",cat:"apparel",desc_ja:"河内木綿の伝統復興",desc_en:"Kawachi cotton revival",deleted:true},
  {i:"os040",ja:"大阪ガラス工房",en:"Osaka Glass Atelier",pref:"osaka",cat:"glass",desc_ja:"大阪のガラス工芸",desc_en:"Osaka glass craft",deleted:true},

  // ========== 兵庫 / HYOGO ==========
  {i:"hy001",ja:"灘 菊正宗酒造",en:"Kikumasamune",pref:"hyogo",cat:"sake",desc_ja:"灘五郷の老舗酒蔵",desc_en:"Heritage Nada-Gogo sake",verified:true},
  {i:"hy002",ja:"白鶴酒造",en:"Hakutsuru",pref:"hyogo",cat:"sake",desc_ja:"灘の老舗酒蔵",desc_en:"Heritage Nada sake brewer",verified:true},
  {i:"hy003",ja:"剣菱酒造",en:"Kenbishi",pref:"hyogo",cat:"sake",desc_ja:"灘の歴史ある酒蔵",desc_en:"Historic Nada sake brewer",verified:true},
  {i:"hy004",ja:"沢の鶴",en:"Sawanotsuru",pref:"hyogo",cat:"sake",desc_ja:"灘の純米酒蔵",desc_en:"Nada all-junmai brewer",verified:true},
  {i:"hy005",ja:"小西酒造 (白雪)",en:"Konishi Brewery (Shirayuki)",pref:"hyogo",cat:"sake",desc_ja:"伊丹の老舗酒蔵",desc_en:"Itami heritage sake brewer",verified:true},
  {i:"hy006",ja:"龍力 (本田商店)",en:"Honda Shoten (Tatsuriki)",pref:"hyogo",cat:"sake",desc_ja:"姫路の山田錦蔵元",desc_en:"Himeji Yamadanishiki brewer",verified:true},
  {i:"hy007",ja:"播州刃物 水池長弥",en:"Mizuike Banshu Hamono",pref:"hyogo",cat:"cutlery",desc_ja:"小野の播州刃物",desc_en:"Ono Banshu cutlery",verified:true},
  {i:"hy008",ja:"播州そろばん 宮本算盤",en:"Miyamoto Banshu Soroban",pref:"hyogo",cat:"craft",desc_ja:"小野の播州そろばん",desc_en:"Ono Banshu soroban abacus"},
  {i:"hy009",ja:"丹波立杭焼 大熊窯",en:"Okuma Tachikui-yaki",pref:"hyogo",cat:"glass",desc_ja:"丹波立杭焼の窯元",desc_en:"Tamba Tachikui pottery kiln"},
  {i:"hy010",ja:"丹波焼 田中陶器",en:"Tanaka Tamba Pottery",pref:"hyogo",cat:"glass",desc_ja:"丹波焼の窯元",desc_en:"Tamba-yaki kiln",deleted:true},
  {i:"hy011",ja:"出石焼",en:"Izushi-yaki",pref:"hyogo",cat:"glass",desc_ja:"出石の白磁焼物",desc_en:"Izushi white porcelain",deleted:true},
  {i:"hy012",ja:"明石焼 ふなまち",en:"Funamachi Akashiyaki",pref:"hyogo",cat:"food",desc_ja:"明石玉子焼の老舗",desc_en:"Heritage Akashi tamago-yaki"},
  {i:"hy013",ja:"神戸プリン本舗",en:"Kobe Pudding",pref:"hyogo",cat:"food",desc_ja:"神戸のプリン老舗",desc_en:"Heritage Kobe pudding maker",deleted:true},
  {i:"hy014",ja:"神戸風月堂",en:"Kobe Fugetsudo",pref:"hyogo",cat:"food",desc_ja:"神戸ゴーフルの老舗",desc_en:"Heritage Kobe gaufre",verified:true},
  {i:"hy015",ja:"モロゾフ (神戸)",en:"Morozoff",pref:"hyogo",cat:"food",desc_ja:"神戸の洋菓子老舗",desc_en:"Heritage Kobe confectionery",verified:true},
  {i:"hy016",ja:"宝塚ベイク",en:"Takarazuka Bake",pref:"hyogo",cat:"food",desc_ja:"宝塚の洋菓子店",desc_en:"Takarazuka pastry maker",deleted:true},
  {i:"hy017",ja:"播州素麺 揖保乃糸",en:"Ibonoito Somen Coop",pref:"hyogo",cat:"food",desc_ja:"揖保乃糸そうめんの組合",desc_en:"Ibonoito somen cooperative",verified:true},
  {i:"hy018",ja:"赤穂化成株式会社",en:"Akō Salt",pref:"hyogo",cat:"food",desc_ja:"赤穂の天日塩",desc_en:"Akō sun-dried salt"},
  {i:"hy019",ja:"丹波黒 黒大豆加工",en:"Tamba Black Bean",pref:"hyogo",cat:"food",desc_ja:"丹波黒大豆の加工",desc_en:"Tamba black soybean processor"},
  {i:"hy020",ja:"株式会社ヒライ",en:"Hirai Kobe Beef",pref:"hyogo",cat:"food",desc_ja:"神戸牛の加工",desc_en:"Kobe beef processor"},
  {i:"hy021",ja:"豊岡鞄 工房COCOMEISTER",en:"Cocomeister Toyooka",pref:"hyogo",cat:"leather",desc_ja:"豊岡鞄の高級革鞄",desc_en:"Toyooka premium leather bags",verified:true},
  {i:"hy022",ja:"豊岡鞄 由利亀",en:"Yurikame Toyooka",pref:"hyogo",cat:"leather",desc_ja:"豊岡鞄の老舗",desc_en:"Heritage Toyooka bags",deleted:true},
  {i:"hy023",ja:"豊岡鞄協同組合",en:"Toyooka Kaban Coop",pref:"hyogo",cat:"leather",desc_ja:"豊岡鞄の組合",desc_en:"Toyooka bag cooperative",verified:true},
  {i:"hy024",ja:"姫路革 (白なめし)",en:"Himeji Leather",pref:"hyogo",cat:"leather",desc_ja:"姫路白なめし革の老舗",desc_en:"Heritage Himeji white-tanned leather",deleted:true},
  {i:"hy025",ja:"出石蕎麦 福助",en:"Fukusuke Izushi Soba",pref:"hyogo",cat:"food",desc_ja:"出石蕎麦の製麺",desc_en:"Izushi soba noodle maker",deleted:true},
  {i:"hy026",ja:"神戸電子試作",en:"Kobe Electronic Lab",pref:"hyogo",cat:"electronics",desc_ja:"神戸の電子試作",desc_en:"Kobe electronic prototyping",deleted:true},
  {i:"hy027",ja:"姫路精機工業株式会社",en:"Himeji Precision",pref:"hyogo",cat:"electronics",desc_ja:"姫路の精密金属加工",desc_en:"Himeji precision metalwork"},
  {i:"hy028",ja:"神戸コスメ研究所",en:"Kobe Cosmetic Lab",pref:"hyogo",cat:"cosmetics",desc_ja:"神戸の化粧品OEM",desc_en:"Kobe cosmetics OEM",deleted:true},
  {i:"hy029",ja:"播州織 産元織元",en:"Banshu-ori Weaver",pref:"hyogo",cat:"apparel",desc_ja:"西脇の播州織織元",desc_en:"Nishiwaki Banshu-ori weaver",verified:true},
  {i:"hy030",ja:"丹波布 工房",en:"Tamba-fu Atelier",pref:"hyogo",cat:"apparel",desc_ja:"丹波布の伝統織",desc_en:"Tamba-fu textile tradition"},

  // ========== 奈良 / NARA ==========
  {i:"na001",ja:"奈良筆 あかしや",en:"Akashiya Nara Brush",pref:"nara",cat:"craft",desc_ja:"奈良筆の老舗",desc_en:"Heritage Nara writing brush",verified:true},
  {i:"na002",ja:"奈良墨 古梅園",en:"Kobaien Nara Sumi",pref:"nara",cat:"craft",desc_ja:"奈良墨の老舗 (1577年創業)",desc_en:"Heritage Nara ink, est.1577",verified:true},
  {i:"na003",ja:"奈良墨 錦光園",en:"Kinkoen Nara Sumi",pref:"nara",cat:"craft",desc_ja:"奈良墨の老舗",desc_en:"Heritage Nara ink maker"},
  {i:"na004",ja:"高山茶筌 谷村丹後",en:"Tanimura Tango Chasen",pref:"nara",cat:"craft",desc_ja:"高山茶筌の人間国宝家系",desc_en:"Takayama chasen, Living Treasure",verified:true},
  {i:"na005",ja:"高山茶筌 久保左文",en:"Kubo Sabun Chasen",pref:"nara",cat:"craft",desc_ja:"高山茶筌の伝統工房",desc_en:"Takayama chasen atelier"},
  {i:"na006",ja:"奈良漆器 樽井",en:"Tarui Nara Lacquer",pref:"nara",cat:"craft",desc_ja:"奈良漆器の伝統工房",desc_en:"Nara lacquerware atelier"},
  {i:"na007",ja:"赤膚焼 大塩",en:"Oshio Akahada-yaki",pref:"nara",cat:"glass",desc_ja:"赤膚焼の窯元",desc_en:"Akahada-yaki kiln",verified:true},
  {i:"na008",ja:"奈良一刀彫",en:"Nara Ittobori",pref:"nara",cat:"wood",desc_ja:"奈良の伝統一刀彫",desc_en:"Nara traditional ittobori carving"},
  {i:"na009",ja:"中川政七商店",en:"Nakagawa Masashichi",pref:"nara",cat:"craft",desc_ja:"奈良発、日本工芸セレクト",desc_en:"Nara-born craft selector",verified:true},
  {i:"na010",ja:"奈良蚊帳 (麻織物)",en:"Nara Kaya Asa",pref:"nara",cat:"apparel",desc_ja:"奈良蚊帳・麻織物",desc_en:"Nara kaya hemp textile"},
  {i:"na011",ja:"奈良井麻織物協同組合",en:"Narai Asa Coop",pref:"nara",cat:"apparel",desc_ja:"奈良晒の麻織物",desc_en:"Nara sarashi hemp textile"},
  {i:"na012",ja:"三輪素麺 山本",en:"Yamamoto Miwa Somen",pref:"nara",cat:"food",desc_ja:"三輪素麺の老舗",desc_en:"Heritage Miwa somen maker",verified:true},
  {i:"na013",ja:"三輪素麺 池利",en:"Ikeri Miwa Somen",pref:"nara",cat:"food",desc_ja:"三輪素麺の老舗",desc_en:"Heritage Miwa somen",verified:true},
  {i:"na014",ja:"三輪素麺マル勝",en:"Marukatsu Miwa Somen",pref:"nara",cat:"food",desc_ja:"三輪素麺の製麺",desc_en:"Miwa somen maker"},
  {i:"na015",ja:"奈良漬 山崎屋",en:"Yamazakiya Nara-zuke",pref:"nara",cat:"food",desc_ja:"奈良漬の老舗",desc_en:"Heritage Nara-zuke pickles",verified:true},
  {i:"na016",ja:"今西清兵衛商店 (春鹿)",en:"Imanishi Brewery (Harushika)",pref:"nara",cat:"sake",desc_ja:"奈良の春鹿蔵元",desc_en:"Nara brewer of Harushika",verified:true},
  {i:"na017",ja:"梅乃宿酒造",en:"Umenoyado Brewery",pref:"nara",cat:"sake",desc_ja:"葛城の地酒蔵",desc_en:"Katsuragi local sake brewer",verified:true},
  {i:"na018",ja:"油長酒造 (風の森)",en:"Yucho Brewery (Kaze no Mori)",pref:"nara",cat:"sake",desc_ja:"御所の風の森蔵元",desc_en:"Gose brewer of Kaze no Mori",verified:true},
  {i:"na019",ja:"奈良大和茶 月ヶ瀬",en:"Tsukigase Yamato Tea",pref:"nara",cat:"tea",desc_ja:"大和茶月ヶ瀬の老舗",desc_en:"Heritage Tsukigase Yamato tea"},
  {i:"na020",ja:"奈良吉野葛 井上天極堂",en:"Inoue Tenkyokudo Kuzu",pref:"nara",cat:"food",desc_ja:"吉野本葛の老舗",desc_en:"Heritage Yoshino kuzu starch",verified:true},

  // ========== 和歌山 / WAKAYAMA ==========
  {i:"wk001",ja:"南高梅 紀州梅干本舗",en:"Kishu Umeboshi Honpo",pref:"wakayama",cat:"food",desc_ja:"紀州南高梅の梅干し",desc_en:"Nanko plum umeboshi"},
  {i:"wk002",ja:"中田食品 (なかたのうめぼし)",en:"Nakata Food Umeboshi",pref:"wakayama",cat:"food",desc_ja:"紀州梅干の老舗",desc_en:"Heritage Kishu umeboshi maker",verified:true},
  {i:"wk003",ja:"五代庵 (梅干し)",en:"Godaian Umeboshi",pref:"wakayama",cat:"food",desc_ja:"南高梅の老舗",desc_en:"Heritage Nanko umeboshi",verified:true},
  {i:"wk004",ja:"紀州 にんにくみそ 食品",en:"Kishu Garlic Miso",pref:"wakayama",cat:"food",desc_ja:"和歌山産にんにく味噌",desc_en:"Wakayama garlic miso",deleted:true},
  {i:"wk005",ja:"紀州備長炭",en:"Kishu Binchotan",pref:"wakayama",cat:"other",desc_ja:"紀州備長炭の老舗",desc_en:"Heritage Kishu binchotan charcoal"},
  {i:"wk006",ja:"紀州漆器 角田漆器",en:"Tsunoda Kishu Lacquer",pref:"wakayama",cat:"craft",desc_ja:"紀州漆器の伝統工房",desc_en:"Kishu lacquerware atelier",deleted:true},
  {i:"wk007",ja:"紀州漆器 山家漆器店",en:"Yamaie Kishu Lacquer",pref:"wakayama",cat:"craft",desc_ja:"海南の紀州漆器",desc_en:"Kainan Kishu lacquerware"},
  {i:"wk008",ja:"高野山金剛峯寺 御用達 香",en:"Koyasan Incense Atelier",pref:"wakayama",cat:"craft",desc_ja:"高野山の香老舗",desc_en:"Koyasan heritage incense"},
  {i:"wk009",ja:"中野BC (梅酒)",en:"Nakano BC",pref:"wakayama",cat:"sake",desc_ja:"紀州梅酒の中堅",desc_en:"Mid-size Kishu plum-wine maker",verified:true},
  {i:"wk010",ja:"九重雜賀 (雑賀)",en:"Saika Brewery",pref:"wakayama",cat:"sake",desc_ja:"和歌山の食用酢・酒蔵",desc_en:"Wakayama vinegar & sake brewer",verified:true},
  {i:"wk011",ja:"世界一統",en:"Sekai Itto",pref:"wakayama",cat:"sake",desc_ja:"和歌山市の老舗酒蔵",desc_en:"Wakayama City heritage sake",verified:true},
  {i:"wk012",ja:"湯浅醤油 角長",en:"Kadocho Yuasa Shoyu",pref:"wakayama",cat:"food",desc_ja:"湯浅醤油発祥の老舗",desc_en:"Yuasa soy sauce origin",verified:true},
  {i:"wk013",ja:"丸新本家 (湯浅醤油・金山寺味噌)",en:"Marushin Honke",pref:"wakayama",cat:"food",desc_ja:"湯浅醤油・金山寺味噌",desc_en:"Yuasa shoyu & kinzanji miso",verified:true},
  {i:"wk014",ja:"紀州蜜柑加工",en:"Kishu Mikan Processing",pref:"wakayama",cat:"food",desc_ja:"和歌山みかんの加工",desc_en:"Wakayama mikan processor"},
  {i:"wk015",ja:"観音山フルーツガーデン",en:"Kannonyama Fruit",pref:"wakayama",cat:"food",desc_ja:"和歌山の柑橘加工",desc_en:"Wakayama citrus processor",verified:true},
  {i:"wk016",ja:"和歌山革加工",en:"Wakayama Leather Atelier",pref:"wakayama",cat:"leather",desc_ja:"県南の革加工中小",desc_en:"Southern Wakayama leather SME",deleted:true},
  {i:"wk017",ja:"南紀ニット",en:"Nanki Knit",pref:"wakayama",cat:"apparel",desc_ja:"南紀のニット工場",desc_en:"Nanki knit factory",deleted:true},
  {i:"wk018",ja:"高野紙工房",en:"Koya Paper Atelier",pref:"wakayama",cat:"paper",desc_ja:"高野紙の伝統和紙",desc_en:"Koya traditional washi",deleted:true},

  // ========== 鳥取 / TOTTORI ==========
  {i:"tt001",ja:"鳥取砂丘らっきょう",en:"Tottori Dune Rakkyo",pref:"tottori",cat:"food",desc_ja:"砂丘らっきょうの加工",desc_en:"Sand dune rakkyo processor"},
  {i:"tt002",ja:"二十世紀梨加工 福寿",en:"Fukuju Nashi",pref:"tottori",cat:"food",desc_ja:"二十世紀梨の加工",desc_en:"Nijuseiki pear processor",deleted:true},
  {i:"tt003",ja:"鳥取和紙 因州中央和紙",en:"Inshu Chuo Washi",pref:"tottori",cat:"paper",desc_ja:"因州和紙の伝統",desc_en:"Inshu washi tradition",deleted:true},
  {i:"tt004",ja:"因州和紙 山根和紙",en:"Yamane Inshu Washi",pref:"tottori",cat:"paper",desc_ja:"因州和紙の工房",desc_en:"Inshu washi atelier",deleted:true},
  {i:"tt005",ja:"千代むすび酒造",en:"Chiyo Musubi",pref:"tottori",cat:"sake",desc_ja:"境港の地酒蔵",desc_en:"Sakaiminato local sake",verified:true},
  {i:"tt006",ja:"諏訪酒造 (鳥取)",en:"Suwa Sake Tottori",pref:"tottori",cat:"sake",desc_ja:"鳥取の地酒蔵",desc_en:"Tottori local sake brewer"},
  {i:"tt007",ja:"鳥取大山ハム",en:"Daisen Ham",pref:"tottori",cat:"food",desc_ja:"大山の老舗ハム",desc_en:"Heritage Daisen ham",verified:true},
  {i:"tt008",ja:"米子木工",en:"Yonago Mokko",pref:"tottori",cat:"wood",desc_ja:"米子の木工製品",desc_en:"Yonago woodwork",deleted:true},
  {i:"tt009",ja:"鳥取電子工業",en:"Tottori Electronics",pref:"tottori",cat:"electronics",desc_ja:"鳥取の電子部品",desc_en:"Tottori electronic parts",deleted:true},
  {i:"tt010",ja:"石谷精華堂",en:"Utsubuki Dango",pref:"tottori",cat:"food",desc_ja:"倉吉の老舗和菓子（銘菓「打吹公園だんご」の製造元）",desc_en:"Kurayoshi wagashi maker of Utsubuki-koen dango"},
  {i:"tt011",ja:"中井窯",en:"Nakai Kiln",pref:"tottori",cat:"glass",desc_ja:"牛ノ戸焼の窯元",desc_en:"Ushinoto-yaki kiln"},
  {i:"tt012",ja:"鳥取ハーブティー",en:"Tottori Herbal Tea",pref:"tottori",cat:"tea",desc_ja:"県産ハーブの茶",desc_en:"Tottori herb tea maker",deleted:true},

  // ========== 島根 / SHIMANE ==========
  {i:"sh001",ja:"出雲そば 本田商店",en:"Honda Izumo Soba",pref:"shimane",cat:"food",desc_ja:"出雲そばの老舗",desc_en:"Heritage Izumo soba maker"},
  {i:"sh002",ja:"羽根屋出雲そば",en:"Haneya Izumo Soba",pref:"shimane",cat:"food",desc_ja:"出雲そばの老舗",desc_en:"Heritage Izumo soba",verified:true},
  {i:"sh003",ja:"国暉酒造",en:"Kokki Brewery",pref:"shimane",cat:"sake",desc_ja:"松江の老舗酒蔵",desc_en:"Matsue heritage sake brewer"},
  {i:"sh004",ja:"李白酒造",en:"Rihaku Brewery",pref:"shimane",cat:"sake",desc_ja:"松江の地酒、李白",desc_en:"Matsue brewer of Rihaku",verified:true},
  {i:"sh005",ja:"日本海酒造 (環日本海)",en:"Nihonkai Brewery",pref:"shimane",cat:"sake",desc_ja:"浜田の地酒蔵",desc_en:"Hamada local sake brewer"},
  {i:"sh006",ja:"奥出雲酒造",en:"Okuizumo Brewery",pref:"shimane",cat:"sake",desc_ja:"奥出雲の地酒",desc_en:"Okuizumo local sake"},
  {i:"sh007",ja:"出雲ぜんざい 坂根屋",en:"Sakaneya Zenzai",pref:"shimane",cat:"food",desc_ja:"出雲ぜんざいの老舗",desc_en:"Heritage Izumo zenzai"},
  {i:"sh008",ja:"中浦食品 (どじょうすくい饅頭)",en:"Nakaura Foods",pref:"shimane",cat:"food",desc_ja:"安来の老舗菓子",desc_en:"Yasugi heritage confectioner",verified:true,deleted:true},
  {i:"sh009",ja:"石見銀山 群言堂",en:"Gungendo Iwami",pref:"shimane",cat:"apparel",desc_ja:"石見銀山発の生活雑貨ブランド",desc_en:"Iwami Ginzan lifestyle brand",verified:true},
  {i:"sh010",ja:"石州瓦 セラミックス",en:"Sekishu Roof Tile",pref:"shimane",cat:"glass",desc_ja:"石州瓦の伝統製造",desc_en:"Sekishu roof tile tradition",deleted:true},
  {i:"sh011",ja:"出雲 鏡像張子",en:"Izumo Hariko Folk Art",pref:"shimane",cat:"craft",desc_ja:"出雲張子の郷土玩具",desc_en:"Izumo paper-mache folk toys",deleted:true},
  {i:"sh012",ja:"出雲和紙工房",en:"Izumo Washi Atelier",pref:"shimane",cat:"paper",desc_ja:"出雲の伝統和紙",desc_en:"Izumo traditional washi"},
  {i:"sh013",ja:"出雲メノウ細工",en:"Izumo Agate Crafts",pref:"shimane",cat:"craft",desc_ja:"出雲メノウの伝統工芸",desc_en:"Izumo agate craft tradition",deleted:true},
  {i:"sh014",ja:"奥出雲たたら和鋼工房",en:"Okuizumo Tatara Steel",pref:"shimane",cat:"cutlery",desc_ja:"たたら製鉄の和鋼工房",desc_en:"Tatara wakou steel atelier",deleted:true},
  {i:"sh015",ja:"島根電子工業",en:"Shimane Electronics",pref:"shimane",cat:"electronics",desc_ja:"中小電子部品メーカー",desc_en:"SME electronic parts",deleted:true},

  // ========== 岡山 / OKAYAMA ==========
  {i:"ok001",ja:"備前焼 木村清五郎",en:"Kimura Seigoro Bizen",pref:"okayama",cat:"glass",desc_ja:"備前焼の伝統工芸",desc_en:"Bizen-yaki tradition",deleted:true},
  {i:"ok002",ja:"備前焼 藤原啓",en:"Fujiwara Kei Bizen",pref:"okayama",cat:"glass",desc_ja:"備前焼の人間国宝家系",desc_en:"Bizen, Living National Treasure",verified:true,deleted:true},
  {i:"ok003",ja:"備前焼 伊勢崎陽山",en:"Isezaki Yozan",pref:"okayama",cat:"glass",desc_ja:"備前焼の名陶",desc_en:"Famed Bizen potter"},
  {i:"ok004",ja:"備前焼陶友会",en:"Bizen Toyukai",pref:"okayama",cat:"glass",desc_ja:"備前焼の作家組合",desc_en:"Bizen potter cooperative"},
  {i:"ok005",ja:"児島ジーンズ ベティスミス",en:"Betty Smith Kojima Denim",pref:"okayama",cat:"apparel",desc_ja:"児島ジーンズの老舗",desc_en:"Heritage Kojima denim",verified:true},
  {i:"ok006",ja:"児島ジーンズ 桃太郎ジーンズ",en:"Momotaro Jeans",pref:"okayama",cat:"apparel",desc_ja:"児島の高級デニム",desc_en:"Kojima premium denim",verified:true},
  {i:"ok007",ja:"児島 ジャパンブルー",en:"Japan Blue Jeans",pref:"okayama",cat:"apparel",desc_ja:"児島デニムブランド",desc_en:"Kojima denim brand",verified:true},
  {i:"ok008",ja:"児島 ビッグジョン",en:"Big John Kojima",pref:"okayama",cat:"apparel",desc_ja:"児島の老舗デニム",desc_en:"Heritage Kojima denim",verified:true},
  {i:"ok009",ja:"児島 EVISU JEANS",en:"Evisu Jeans Kojima",pref:"okayama",cat:"apparel",desc_ja:"児島の世界的デニム",desc_en:"World-famous Kojima denim",verified:true},
  {i:"ok010",ja:"大江洋服店（OOE YOFUKUTEN）",en:"OOE Yofukuten",pref:"aichi",cat:"apparel",desc_ja:"一宮の職人が縫うジーンズ（生地は岡山・児島産）",desc_en:"Ichinomiya-sewn jeans using Kojima denim"},
  {i:"ok011",ja:"きびだんご 廣榮堂",en:"Koeido Kibidango",pref:"okayama",cat:"food",desc_ja:"岡山きびだんごの老舗",desc_en:"Heritage Okayama kibidango",verified:true},
  {i:"ok012",ja:"つるの玉子",en:"Tsuru no Tamago",pref:"okayama",cat:"food",desc_ja:"岡山銘菓鶴の玉子",desc_en:"Okayama heritage tsuru no tamago"},
  {i:"ok013",ja:"白桃加工 林フルーツ",en:"Hayashi Peach",pref:"okayama",cat:"food",desc_ja:"岡山白桃の加工",desc_en:"Okayama peach processor",deleted:true},
  {i:"ok014",ja:"宮下酒造",en:"Miyashita Brewery",pref:"okayama",cat:"sake",desc_ja:"岡山の地酒・地ビール蔵",desc_en:"Okayama craft beer & sake brewer",verified:true},
  {i:"ok015",ja:"室町酒造",en:"Muromachi Brewery",pref:"okayama",cat:"sake",desc_ja:"赤磐の地酒蔵",desc_en:"Akaiwa local sake brewer",verified:true},
  {i:"ok016",ja:"丸本酒造",en:"Marumoto Brewery",pref:"okayama",cat:"sake",desc_ja:"浅口の竹林蔵元",desc_en:"Asakuchi brewer of Chikurin",verified:true},
  {i:"ok017",ja:"岡山特産マスカット加工",en:"Okayama Muscat Processor",pref:"okayama",cat:"food",desc_ja:"マスカットの菓子・加工",desc_en:"Muscat grape sweets & processing",deleted:true},
  {i:"ok018",ja:"倉敷帆布",en:"Kurashiki Hanpu",pref:"okayama",cat:"apparel",desc_ja:"倉敷の帆布鞄・バッグ",desc_en:"Kurashiki canvas bag maker",verified:true},
  {i:"ok019",ja:"倉敷意匠計画室",en:"Kurashiki Ishou",pref:"okayama",cat:"craft",desc_ja:"倉敷の生活雑貨",desc_en:"Kurashiki lifestyle goods",verified:true},
  {i:"ok020",ja:"勝央ジャージーバター",en:"Shoo Jersey Butter",pref:"okayama",cat:"food",desc_ja:"勝央のジャージー牛乳・バター",desc_en:"Shoo Jersey milk & butter",deleted:true},
  {i:"ok021",ja:"福岡製靴 (倉敷)",en:"Fukuoka Shoe Kurashiki",pref:"okayama",cat:"leather",desc_ja:"児島の革靴OEM",desc_en:"Kojima leather shoe OEM",deleted:true},
  {i:"ok022",ja:"岡山電子精密",en:"Okayama Precision Electronics",pref:"okayama",cat:"electronics",desc_ja:"岡山の電子部品",desc_en:"Okayama electronic parts",deleted:true},

  // ========== 広島 / HIROSHIMA ==========
  {i:"hi001",ja:"熊野筆 白鳳堂",en:"Hakuhodo Kumano Brush",pref:"hiroshima",cat:"cosmetics",desc_ja:"熊野筆の最高級化粧筆",desc_en:"Premium Kumano cosmetic brush",verified:true},
  {i:"hi002",ja:"熊野筆 竹宝堂",en:"Chikuhodo Kumano",pref:"hiroshima",cat:"cosmetics",desc_ja:"熊野化粧筆の老舗",desc_en:"Heritage Kumano cosmetic brush",verified:true},
  {i:"hi003",ja:"熊野筆 晃祐堂",en:"Koyudo Kumano Brush",pref:"hiroshima",cat:"cosmetics",desc_ja:"熊野化粧筆メーカー",desc_en:"Kumano cosmetic brush maker",verified:true},
  {i:"hi004",ja:"熊野筆 喜筆",en:"Kihitsu Kumano Brush",pref:"hiroshima",cat:"cosmetics",desc_ja:"熊野筆の伝統工房",desc_en:"Kumano brush atelier"},
  {i:"hi005",ja:"熊野筆協同組合",en:"Kumano Brush Coop",pref:"hiroshima",cat:"cosmetics",desc_ja:"熊野筆の組合",desc_en:"Kumano brush cooperative"},
  {i:"hi006",ja:"宮島工芸製作所 (杓子)",en:"Miyajima Shamoji",pref:"hiroshima",cat:"wood",desc_ja:"宮島杓子の老舗",desc_en:"Heritage Miyajima rice paddle",verified:true},
  {i:"hi007",ja:"もみじ饅頭 にしき堂",en:"Nishikido Momiji Manju",pref:"hiroshima",cat:"food",desc_ja:"もみじ饅頭の老舗",desc_en:"Heritage Momiji Manju",verified:true},
  {i:"hi008",ja:"もみじ饅頭 やまだ屋",en:"Yamadaya Momiji",pref:"hiroshima",cat:"food",desc_ja:"宮島もみじ饅頭の老舗",desc_en:"Heritage Miyajima Momiji Manju",verified:true},
  {i:"hi009",ja:"もみじ饅頭 藤い屋",en:"Fujiiya Momiji",pref:"hiroshima",cat:"food",desc_ja:"宮島のもみじ饅頭",desc_en:"Miyajima Momiji Manju",verified:true},
  {i:"hi010",ja:"オタフクソース",en:"Otafuku Sauce",pref:"hiroshima",cat:"food",desc_ja:"広島お好み焼ソース",desc_en:"Hiroshima okonomiyaki sauce",verified:true},
  {i:"hi011",ja:"カキ加工 株式会社丸じょう",en:"Marujo Oyster",pref:"hiroshima",cat:"food",desc_ja:"広島カキの加工",desc_en:"Hiroshima oyster processor",deleted:true},
  {i:"hi012",ja:"瀬戸内レモン加工",en:"Setouchi Lemon",pref:"hiroshima",cat:"food",desc_ja:"瀬戸内レモンの加工",desc_en:"Setouchi lemon processor",deleted:true},
  {i:"hi013",ja:"白牡丹酒造",en:"Hakubotan",pref:"hiroshima",cat:"sake",desc_ja:"西条の老舗酒蔵",desc_en:"Saijo heritage sake brewer",verified:true},
  {i:"hi014",ja:"賀茂泉酒造",en:"Kamoizumi",pref:"hiroshima",cat:"sake",desc_ja:"西条の純米酒蔵",desc_en:"Saijo all-junmai brewer",verified:true},
  {i:"hi015",ja:"亀齢酒造",en:"Kirei Brewery",pref:"hiroshima",cat:"sake",desc_ja:"西条の老舗酒蔵",desc_en:"Saijo heritage sake brewer",verified:true},
  {i:"hi016",ja:"福美人酒造",en:"Fukubijin Brewery",pref:"hiroshima",cat:"sake",desc_ja:"西条の地酒蔵",desc_en:"Saijo local sake brewer"},
  {i:"hi017",ja:"竹鶴酒造",en:"Taketsuru Brewery",pref:"hiroshima",cat:"sake",desc_ja:"竹原の老舗酒蔵",desc_en:"Takehara heritage sake brewer",verified:true},
  {i:"hi018",ja:"備後絣 (織元)",en:"Bingo Kasuri Weaver",pref:"hiroshima",cat:"apparel",desc_ja:"備後絣の伝統織",desc_en:"Bingo kasuri textile",deleted:true},
  {i:"hi019",ja:"福山琴 工房",en:"Fukuyama Koto Atelier",pref:"hiroshima",cat:"craft",desc_ja:"福山の伝統琴",desc_en:"Fukuyama traditional koto",deleted:true},
  {i:"hi020",ja:"宮島彫り",en:"Miyajima Wood Carving",pref:"hiroshima",cat:"wood",desc_ja:"宮島の伝統木彫",desc_en:"Miyajima wood carving",deleted:true},
  {i:"hi021",ja:"広島電子精密",en:"Hiroshima Electron Precision",pref:"hiroshima",cat:"electronics",desc_ja:"広島の電子部品試作",desc_en:"Hiroshima electronic prototyping",deleted:true},
  {i:"hi022",ja:"尾道帆布工房",en:"Onomichi Canvas",pref:"hiroshima",cat:"apparel",desc_ja:"尾道の帆布製品",desc_en:"Onomichi canvas products",deleted:true},
  {i:"hi023",ja:"広島ジビエ加工",en:"Hiroshima Gibier",pref:"hiroshima",cat:"food",desc_ja:"中山間のジビエ加工",desc_en:"Hiroshima gibier processor",deleted:true},
  {i:"hi024",ja:"庄原乳業",en:"Shobara Dairy",pref:"hiroshima",cat:"food",desc_ja:"庄原の乳製品",desc_en:"Shobara dairy products",deleted:true},
  {i:"hi025",ja:"広島サプリ研究所",en:"Hiroshima Supplement Lab",pref:"hiroshima",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},

  // ========== 山口 / YAMAGUCHI ==========
  {i:"yc001",ja:"萩焼 大屋窯",en:"Oyo-gama Hagi",pref:"yamaguchi",cat:"glass",desc_ja:"萩焼の窯元",desc_en:"Hagi-yaki kiln",verified:true},
  {i:"yc002",ja:"萩焼 坂倉新兵衛",en:"Sakakura Shinbei Hagi",pref:"yamaguchi",cat:"glass",desc_ja:"萩焼の名門",desc_en:"Famed Hagi-yaki lineage",verified:true},
  {i:"yc003",ja:"萩焼 三輪窯",en:"Miwa Kiln Hagi",pref:"yamaguchi",cat:"glass",desc_ja:"萩焼の人間国宝家系",desc_en:"Hagi, Living National Treasure",verified:true},
  {i:"yc004",ja:"大屋窯",en:"Oya Pottery Hagi",pref:"yamaguchi",cat:"glass",desc_ja:"萩焼の中堅",desc_en:"Mid-size Hagi-yaki"},
  {i:"yc005",ja:"獺祭 (旭酒造)",en:"Asahi Shuzo (Dassai)",pref:"yamaguchi",cat:"sake",desc_ja:"岩国の獺祭蔵元",desc_en:"Iwakuni brewer of Dassai",verified:true},
  {i:"yc006",ja:"雁木 (八百新酒造)",en:"Yaoshin Brewery (Gangi)",pref:"yamaguchi",cat:"sake",desc_ja:"岩国の地酒、雁木",desc_en:"Iwakuni brewer of Gangi",verified:true},
  {i:"yc007",ja:"五橋 (酒井酒造)",en:"Sakai Brewery (Gokyo)",pref:"yamaguchi",cat:"sake",desc_ja:"岩国の老舗酒蔵",desc_en:"Iwakuni heritage sake brewer",verified:true},
  {i:"yc008",ja:"周防大島みかん加工",en:"Suo-Oshima Mikan",pref:"yamaguchi",cat:"food",desc_ja:"周防大島のみかん",desc_en:"Suo-Oshima mikan processor",deleted:true},
  {i:"yc009",ja:"林兼産業株式会社",en:"Hayashikane Fugu",pref:"yamaguchi",cat:"food",desc_ja:"下関のふぐ加工",desc_en:"Shimonoseki fugu processor"},
  {i:"yc010",ja:"下関 山口萬幸軒 ふぐ加工",en:"Yamaguchi Mankoken",pref:"yamaguchi",cat:"food",desc_ja:"下関ふぐの老舗加工",desc_en:"Heritage Shimonoseki fugu",deleted:true},
  {i:"yc011",ja:"北九州ニッスイ 宇部工場",en:"Ube Kamaboko",pref:"yamaguchi",cat:"food",desc_ja:"宇部工場でつくるかまぼこ（運営は北九州ニッスイ・本社は福岡）",desc_en:"Ube-plant kamaboko, operated by Kitakyushu Nissui"},
  {i:"yc012",ja:"瓦そば たかせ",en:"Takase Kawara Soba",pref:"yamaguchi",cat:"food",desc_ja:"下関瓦そば老舗",desc_en:"Heritage Shimonoseki kawara soba"},
  {i:"yc013",ja:"萩夏みかん加工",en:"Hagi Natsumikan",pref:"yamaguchi",cat:"food",desc_ja:"萩の夏みかん加工",desc_en:"Hagi natsumikan processor",deleted:true},
  {i:"yc014",ja:"徳山織物",en:"Tokuyama Textile",pref:"yamaguchi",cat:"apparel",desc_ja:"徳山の織物",desc_en:"Tokuyama textile",deleted:true},
  {i:"yc015",ja:"山口電子工業",en:"Yamaguchi Electronics",pref:"yamaguchi",cat:"electronics",desc_ja:"山口の電子部品",desc_en:"Yamaguchi electronic parts",deleted:true},

  // ========== 徳島 / TOKUSHIMA ==========
  {i:"ts001",ja:"阿波藍染 古庄染工所",en:"Furusho Awa Indigo",pref:"tokushima",cat:"apparel",desc_ja:"阿波藍染の老舗",desc_en:"Heritage Awa indigo dye",verified:true},
  {i:"ts002",ja:"阿波藍染 BUAISOU",en:"BUAISOU Indigo",pref:"tokushima",cat:"apparel",desc_ja:"阿波藍染の若手職人ブランド",desc_en:"Young Awa indigo artisan brand",verified:true},
  {i:"ts003",ja:"阿波和紙 阿波和紙伝統産業会館",en:"Awagami Factory",pref:"tokushima",cat:"paper",desc_ja:"阿波和紙の老舗",desc_en:"Heritage Awa washi",verified:true},
  {i:"ts004",ja:"鳴門わかめ加工",en:"Naruto Wakame",pref:"tokushima",cat:"food",desc_ja:"鳴門わかめの加工",desc_en:"Naruto wakame processor"},
  {i:"ts005",ja:"徳島すだち加工 松浦酒造",en:"Tokushima Sudachi Sake",pref:"tokushima",cat:"sake",desc_ja:"すだちリキュール",desc_en:"Sudachi citrus liqueur"},
  {i:"ts006",ja:"徳島 鳴門金時 加工",en:"Naruto Kintoki Processor",pref:"tokushima",cat:"food",desc_ja:"鳴門金時の加工",desc_en:"Naruto kintoki sweet potato processor",deleted:true},
  {i:"ts007",ja:"日新酒類",en:"Nisshin Shurui",pref:"tokushima",cat:"sake",desc_ja:"徳島の地酒・リキュール",desc_en:"Tokushima sake & liqueur"},
  {i:"ts008",ja:"本家松浦酒造場",en:"Matsuura Brewery (Narutotai)",pref:"tokushima",cat:"sake",desc_ja:"鳴門鯛ブランドの蔵元",desc_en:"Brewer of Narutotai",verified:true},
  {i:"ts009",ja:"芳水酒造 (徳島)",en:"Hosui Brewery",pref:"tokushima",cat:"sake",desc_ja:"三好の地酒蔵",desc_en:"Miyoshi local sake brewer"},
  {i:"ts010",ja:"和三盆 岡田製糖所",en:"Okada Wasanbon",pref:"tokushima",cat:"food",desc_ja:"和三盆糖の老舗",desc_en:"Heritage wasanbon sugar maker",verified:true},
  {i:"ts011",ja:"鳴門ハム",en:"Naruto Ham",pref:"tokushima",cat:"food",desc_ja:"鳴門の地場ハム",desc_en:"Naruto local ham",deleted:true},
  {i:"ts012",ja:"徳島電子部品",en:"Tokushima Electronic Parts",pref:"tokushima",cat:"electronics",desc_ja:"徳島の電子部品",desc_en:"Tokushima electronic parts"},

  // ========== 香川 / KAGAWA ==========
  {i:"kg001",ja:"讃岐うどん 山田家",en:"Yamadaya Sanuki Udon",pref:"kagawa",cat:"food",desc_ja:"讃岐うどんの老舗",desc_en:"Heritage Sanuki udon",verified:true},
  {i:"kg002",ja:"讃岐うどん 川福",en:"Kawafuku Udon",pref:"kagawa",cat:"food",desc_ja:"高松うどん老舗",desc_en:"Heritage Takamatsu udon"},
  {i:"kg003",ja:"讃岐うどん 石丸製麺",en:"Ishimaru Seimen",pref:"kagawa",cat:"food",desc_ja:"讃岐うどん製麺の老舗",desc_en:"Heritage Sanuki udon noodle maker",verified:true},
  {i:"kg004",ja:"丸亀うちわ 三谷",en:"Mitani Marugame Uchiwa",pref:"kagawa",cat:"craft",desc_ja:"丸亀うちわの老舗",desc_en:"Heritage Marugame uchiwa"},
  {i:"kg005",ja:"丸亀うちわ協同組合",en:"Marugame Uchiwa Coop",pref:"kagawa",cat:"craft",desc_ja:"丸亀うちわの組合",desc_en:"Marugame uchiwa cooperative",verified:true},
  {i:"kg006",ja:"庵治石 産元",en:"Aji Stone Quarry",pref:"kagawa",cat:"other",desc_ja:"庵治石の伝統石工",desc_en:"Aji stone craft",deleted:true},
  {i:"kg007",ja:"小豆島 ヤマロク醤油",en:"Yamaroku Soy Sauce",pref:"kagawa",cat:"food",desc_ja:"小豆島の木桶醤油老舗",desc_en:"Shodoshima wooden-vat soy heritage",verified:true},
  {i:"kg008",ja:"小豆島 マルキン醤油",en:"Marukin Shoyu",pref:"kagawa",cat:"food",desc_ja:"小豆島醤油の老舗",desc_en:"Heritage Shodoshima soy sauce",verified:true},
  {i:"kg009",ja:"小豆島オリーブ園",en:"Shodoshima Olive Garden",pref:"kagawa",cat:"food",desc_ja:"小豆島のオリーブ油",desc_en:"Shodoshima olive oil",verified:true},
  {i:"kg010",ja:"金陵 (西野金陵)",en:"Nishino Kinryo Brewery",pref:"kagawa",cat:"sake",desc_ja:"金毘羅の老舗酒蔵",desc_en:"Konpira heritage sake brewer",verified:true},
  {i:"kg011",ja:"川鶴酒造",en:"Kawatsuru Brewery",pref:"kagawa",cat:"sake",desc_ja:"観音寺の地酒蔵",desc_en:"Kanonji local sake brewer",verified:true},
  {i:"kg012",ja:"高松盆栽 (鬼無)",en:"Kinashi Bonsai",pref:"kagawa",cat:"craft",desc_ja:"鬼無の松盆栽",desc_en:"Kinashi pine bonsai",verified:true},
  {i:"kg013",ja:"讃岐かがり手まり",en:"Sanuki Temari",pref:"kagawa",cat:"craft",desc_ja:"讃岐かがり手まりの伝統工芸",desc_en:"Sanuki temari ball craft"},
  {i:"kg014",ja:"骨付鳥 一鶴",en:"Ikkaku Honetsuki Dori",pref:"kagawa",cat:"food",desc_ja:"丸亀の骨付鳥老舗",desc_en:"Heritage Marugame honetsuki",verified:true},
  {i:"kg015",ja:"香川電子工業",en:"Kagawa Electronics",pref:"kagawa",cat:"electronics",desc_ja:"香川の電子部品",desc_en:"Kagawa electronic parts",deleted:true},

  // ========== 愛媛 / EHIME ==========
  {i:"eh001",ja:"今治タオル コンテックス",en:"Kontex Imabari Towel",pref:"ehime",cat:"apparel",desc_ja:"今治タオルの代表",desc_en:"Representative Imabari towel",verified:true},
  {i:"eh002",ja:"今治タオル 池内オーガニック",en:"Ikeuchi Organic",pref:"ehime",cat:"apparel",desc_ja:"今治オーガニックタオル",desc_en:"Imabari organic towel",verified:true},
  {i:"eh003",ja:"今治タオル 楠橋紋織",en:"Kusubashi Monori",pref:"ehime",cat:"apparel",desc_ja:"今治紋織タオル",desc_en:"Imabari monori towel",verified:true},
  {i:"eh004",ja:"今治タオル 工房くもくも",en:"Kumokumo Imabari",pref:"ehime",cat:"apparel",desc_ja:"今治の小規模工房",desc_en:"Imabari small atelier",deleted:true},
  {i:"eh005",ja:"今治タオル工業組合",en:"Imabari Towel Coop",pref:"ehime",cat:"apparel",desc_ja:"今治タオルの組合",desc_en:"Imabari towel cooperative",verified:true},
  {i:"eh006",ja:"砥部焼 梅山窯",en:"Baizan Tobeyaki",pref:"ehime",cat:"glass",desc_ja:"砥部焼の老舗窯元",desc_en:"Heritage Tobe-yaki kiln",verified:true},
  {i:"eh007",ja:"砥部焼 中田窯",en:"Nakata Tobe Kiln",pref:"ehime",cat:"glass",desc_ja:"砥部焼の窯元",desc_en:"Tobe-yaki kiln"},
  {i:"eh008",ja:"伊予柑加工 ポンジュース系列",en:"Iyokan Processor Ehime",pref:"ehime",cat:"food",desc_ja:"愛媛みかんの加工OEM",desc_en:"Ehime mikan OEM"},
  {i:"eh009",ja:"霧の森 茶加工",en:"Kirinomori Matcha",pref:"ehime",cat:"tea",desc_ja:"愛媛新宮村の抹茶加工",desc_en:"Shingu-mura matcha processor",verified:true},
  {i:"eh010",ja:"梅錦酒造",en:"Umenishiki Brewery",pref:"ehime",cat:"sake",desc_ja:"四国中央の梅錦蔵元",desc_en:"Shikoku-Chuo brewer of Umenishiki",verified:true},
  {i:"eh011",ja:"石鎚酒造",en:"Ishizuchi Brewery",pref:"ehime",cat:"sake",desc_ja:"西条の地酒蔵",desc_en:"Saijo local sake brewer",verified:true},
  {i:"eh012",ja:"水口酒造 (道後ビール)",en:"Mizuguchi Brewery (Dogo Beer)",pref:"ehime",cat:"sake",desc_ja:"道後温泉の地ビール",desc_en:"Dogo Onsen craft beer",verified:true},
  {i:"eh013",ja:"大三島 みかん加工",en:"Omishima Mikan",pref:"ehime",cat:"food",desc_ja:"大三島のみかん加工",desc_en:"Omishima mikan processor"},
  {i:"eh014",ja:"五十崎和紙",en:"Ikazaki Washi",pref:"ehime",cat:"paper",desc_ja:"内子の伝統大洲和紙",desc_en:"Uchiko Ozu washi tradition"},
  {i:"eh015",ja:"内子手すき和紙",en:"Uchiko Tesuki Washi",pref:"ehime",cat:"paper",desc_ja:"内子の手すき和紙",desc_en:"Uchiko handmade washi"},
  {i:"eh016",ja:"宇和島真珠加工",en:"Uwajima Pearl",pref:"ehime",cat:"craft",desc_ja:"宇和島の真珠養殖",desc_en:"Uwajima pearl farming",deleted:true},
  {i:"eh017",ja:"愛媛電子部品",en:"Ehime Electronic Parts",pref:"ehime",cat:"electronics",desc_ja:"愛媛の中小電子部品",desc_en:"Ehime SME electronic parts",deleted:true},
  {i:"eh018",ja:"松山高級タオル",en:"Matsuyama Premium Towel",pref:"ehime",cat:"apparel",desc_ja:"愛媛の高級タオルOEM",desc_en:"Ehime premium towel OEM",deleted:true},

  // ========== 高知 / KOCHI ==========
  {i:"kc001",ja:"土佐和紙 ロギール アウテンボーガルト",en:"Rogier Toh Washi",pref:"kochi",cat:"paper",desc_ja:"土佐和紙の海外職人",desc_en:"Tosa washi international artisan",verified:true},
  {i:"kc002",ja:"土佐和紙工芸村",en:"Tosa Washi Village",pref:"kochi",cat:"paper",desc_ja:"土佐和紙の伝統工芸",desc_en:"Tosa washi tradition",deleted:true},
  {i:"kc003",ja:"土佐打刃物 トヨクニ",en:"Toyokuni Tosa Hamono",pref:"kochi",cat:"cutlery",desc_ja:"土佐打刃物の老舗",desc_en:"Heritage Tosa cutlery",verified:true},
  {i:"kc004",ja:"黒鳥鍛造工場",en:"Kurotori Denkichi",pref:"kochi",cat:"cutlery",desc_ja:"土佐打刃物の鍛冶",desc_en:"Tosa blade smithy"},
  {i:"kc005",ja:"司牡丹酒造",en:"Tsukasa Botan",pref:"kochi",cat:"sake",desc_ja:"佐川の老舗酒蔵",desc_en:"Sakawa heritage sake brewer",verified:true},
  {i:"kc006",ja:"無手無冠 (栗焼酎)",en:"Mutemuka",pref:"kochi",cat:"sake",desc_ja:"四万十栗焼酎",desc_en:"Shimanto chestnut shochu",verified:true},
  {i:"kc007",ja:"高知ゆず加工 馬路村",en:"Umaji Village Yuzu",pref:"kochi",cat:"food",desc_ja:"馬路村ゆずの加工",desc_en:"Umaji village yuzu products",verified:true},
  {i:"kc008",ja:"高知ゆず ぽん酢 旭フレッシュ",en:"Asahi Yuzu Ponzu",pref:"kochi",cat:"food",desc_ja:"高知ゆずぽん酢",desc_en:"Kochi yuzu ponzu maker"},
  {i:"kc009",ja:"土佐文旦加工",en:"Tosa Buntan Processor",pref:"kochi",cat:"food",desc_ja:"土佐文旦の加工",desc_en:"Tosa buntan citrus processor"},
  {i:"kc010",ja:"四万十川海苔",en:"Shimanto Aonori",pref:"kochi",cat:"food",desc_ja:"四万十川の青さ海苔",desc_en:"Shimanto river aonori",deleted:true},
  {i:"kc011",ja:"高知サプリ工房",en:"Kochi Supplement Atelier",pref:"kochi",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"kc012",ja:"高知電子試作",en:"Kochi Electronic Atelier",pref:"kochi",cat:"electronics",desc_ja:"電子試作の中小",desc_en:"SME electronic prototyping",deleted:true},

  // ========== 福岡 / FUKUOKA ==========
  {i:"fo001",ja:"博多織 西村織物",en:"Nishimura Hakata-ori",pref:"fukuoka",cat:"apparel",desc_ja:"博多織の老舗",desc_en:"Heritage Hakata-ori weaver",verified:true},
  {i:"fo002",ja:"博多織 福絖織物",en:"Fukko Hakata-ori",pref:"fukuoka",cat:"apparel",desc_ja:"博多織の織元",desc_en:"Hakata-ori weaver",deleted:true},
  {i:"fo003",ja:"博多人形 中村",en:"Nakamura Hakata Doll",pref:"fukuoka",cat:"craft",desc_ja:"博多人形の伝統工房",desc_en:"Hakata doll atelier",verified:true},
  {i:"fo004",ja:"博多曲物 柴田玉樹",en:"Shibata Hakata Magemono",pref:"fukuoka",cat:"wood",desc_ja:"博多曲物の老舗",desc_en:"Heritage Hakata magemono"},
  {i:"fo005",ja:"明月堂 (博多通りもん)",en:"Meigetsudo Tōrimon",pref:"fukuoka",cat:"food",desc_ja:"博多通りもんの老舗",desc_en:"Heritage Hakata Tōrimon",verified:true},
  {i:"fo006",ja:"ひよ子本舗吉野堂",en:"Yoshinodo Hiyoko",pref:"fukuoka",cat:"food",desc_ja:"ひよ子饅頭の老舗",desc_en:"Heritage Hiyoko sweet",verified:true},
  {i:"fo007",ja:"如水庵",en:"Josuian",pref:"fukuoka",cat:"food",desc_ja:"博多和菓子の老舗",desc_en:"Heritage Hakata wagashi",verified:true},
  {i:"fo008",ja:"福岡 椒房庵 (久原本家)",en:"Kubara Honke Saiboan",pref:"fukuoka",cat:"food",desc_ja:"あごだしの老舗",desc_en:"Heritage flying-fish dashi",verified:true},
  {i:"fo009",ja:"福岡 茅乃舎 (久原)",en:"Kayanoya",pref:"fukuoka",cat:"food",desc_ja:"茅乃舎だしブランド",desc_en:"Kayanoya dashi brand",verified:true},
  {i:"fo010",ja:"福さ屋 辛子明太子",en:"Fukusaya Mentaiko",pref:"fukuoka",cat:"food",desc_ja:"博多辛子明太子",desc_en:"Hakata spicy cod roe maker",verified:true},
  {i:"fo011",ja:"ふくや 明太子",en:"Fukuya Mentaiko",pref:"fukuoka",cat:"food",desc_ja:"明太子発祥の老舗",desc_en:"Heritage origin of mentaiko",verified:true},
  {i:"fo012",ja:"やまや (明太子)",en:"Yamaya Mentaiko",pref:"fukuoka",cat:"food",desc_ja:"福岡明太子の中堅",desc_en:"Mid-size Fukuoka mentaiko",verified:true},
  {i:"fo013",ja:"上野焼 (赤池窯)",en:"Akaike Agano-yaki",pref:"fukuoka",cat:"glass",desc_ja:"上野焼の窯元",desc_en:"Agano-yaki kiln",deleted:true},
  {i:"fo014",ja:"小石原焼 早川窯",en:"Hayakawa Koishiwara",pref:"fukuoka",cat:"glass",desc_ja:"小石原焼の窯元",desc_en:"Koishiwara-yaki kiln",verified:true},
  {i:"fo015",ja:"小石原焼 太田",en:"Ota Koishiwara",pref:"fukuoka",cat:"glass",desc_ja:"小石原焼の伝統工房",desc_en:"Koishiwara atelier",deleted:true},
  {i:"fo016",ja:"久留米絣 池田絣工房",en:"Ikeda Kurume Kasuri",pref:"fukuoka",cat:"apparel",desc_ja:"久留米絣の老舗",desc_en:"Heritage Kurume kasuri",verified:true},
  {i:"fo017",ja:"久留米絣 下川織物",en:"Shimokawa Kurume",pref:"fukuoka",cat:"apparel",desc_ja:"久留米絣の織元",desc_en:"Kurume kasuri weaver",verified:true},
  {i:"fo018",ja:"博多曲物 柴田徳商店",en:"Shibata Toku Magemono",pref:"fukuoka",cat:"wood",desc_ja:"博多曲物の伝統工房",desc_en:"Hakata magemono atelier"},
  {i:"fo019",ja:"喜多屋 (酒造)",en:"Kitaya Brewery",pref:"fukuoka",cat:"sake",desc_ja:"八女の喜多屋蔵元",desc_en:"Yame brewer of Kitaya",verified:true},
  {i:"fo020",ja:"白糸酒造",en:"Shiraito Brewery",pref:"fukuoka",cat:"sake",desc_ja:"糸島の地酒蔵",desc_en:"Itoshima local sake brewer",verified:true},
  {i:"fo021",ja:"杜の蔵",en:"Mori no Kura",pref:"fukuoka",cat:"sake",desc_ja:"久留米の純米酒蔵",desc_en:"Kurume all-junmai brewer",verified:true},
  {i:"fo022",ja:"八女茶 矢部園",en:"Yabe-en Yame Tea",pref:"fukuoka",cat:"tea",desc_ja:"八女茶の老舗",desc_en:"Heritage Yame tea",deleted:true},
  {i:"fo023",ja:"株式会社福寿園",en:"Yame Fukujuen",pref:"kyoto",cat:"tea",desc_ja:"八女抹茶の名門",desc_en:"Famed Yame matcha"},
  {i:"fo024",ja:"八女茶 田中茶舗",en:"Tanaka Chaho Yame",pref:"fukuoka",cat:"tea",desc_ja:"八女茶の老舗茶舗",desc_en:"Heritage Yame tea house"},
  {i:"fo025",ja:"八女ふくおか茶協同組合",en:"Fukuoka Yame Tea Coop",pref:"fukuoka",cat:"tea",desc_ja:"八女茶組合",desc_en:"Yame tea cooperative"},
  {i:"fo026",ja:"博多曲物 十八代柴田玉樹",en:"Hakata Magemono Tamaki",pref:"fukuoka",cat:"wood",desc_ja:"博多曲物の若手",desc_en:"Young Hakata magemono"},
  {i:"fo027",ja:"福岡コスメ研究所",en:"Fukuoka Cosmetics Lab",pref:"fukuoka",cat:"cosmetics",desc_ja:"福岡の化粧品OEM",desc_en:"Fukuoka cosmetics OEM",deleted:true},
  {i:"fo028",ja:"福岡サプリ工房",en:"Fukuoka Supplement Atelier",pref:"fukuoka",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"fo029",ja:"博多金物株式会社",en:"Hakata Iron Pan",pref:"fukuoka",cat:"cutlery",desc_ja:"博多の鉄鍋メーカー",desc_en:"Hakata iron pan maker",deleted:true},
  {i:"fo030",ja:"北九州精密電子",en:"Kitakyushu Precision",pref:"fukuoka",cat:"electronics",desc_ja:"北九州の電子部品",desc_en:"Kitakyushu electronic parts",deleted:true},

  // ========== 佐賀 / SAGA ==========
  {i:"sa001",ja:"有田焼 香蘭社",en:"Koransha Aritayaki",pref:"saga",cat:"glass",desc_ja:"有田焼の老舗",desc_en:"Heritage Arita porcelain",verified:true},
  {i:"sa002",ja:"有田焼 深川製磁",en:"Fukagawa Seiji",pref:"saga",cat:"glass",desc_ja:"有田焼の宮内庁御用達",desc_en:"Arita, Imperial Household supplier",verified:true},
  {i:"sa003",ja:"有田焼 源右衛門窯",en:"Gen-emon Kiln",pref:"saga",cat:"glass",desc_ja:"有田焼の老舗窯元",desc_en:"Heritage Arita kiln",verified:true},
  {i:"sa004",ja:"有田焼 柿右衛門窯",en:"Kakiemon Kiln",pref:"saga",cat:"glass",desc_ja:"有田焼の人間国宝家系",desc_en:"Arita Living Treasure lineage",verified:true},
  {i:"sa005",ja:"有田焼 今右衛門窯",en:"Imaemon Kiln",pref:"saga",cat:"glass",desc_ja:"有田焼の人間国宝家系",desc_en:"Arita Living Treasure lineage",verified:true},
  {i:"sa006",ja:"伊万里焼 鍋島焼",en:"Imari Nabeshima",pref:"saga",cat:"glass",desc_ja:"伊万里・鍋島焼の窯元",desc_en:"Imari & Nabeshima kiln",deleted:true},
  {i:"sa007",ja:"伊万里 畑萬陶苑",en:"Hatamanto-en",pref:"saga",cat:"glass",desc_ja:"鍋島焼の代表窯",desc_en:"Representative Nabeshima kiln",verified:true},
  {i:"sa008",ja:"唐津焼 中里太郎右衛門陶房",en:"Nakazato Taroemon Kiln",pref:"saga",cat:"glass",desc_ja:"唐津焼の人間国宝家系",desc_en:"Karatsu Living Treasure lineage",verified:true},
  {i:"sa009",ja:"唐津焼 隆太窯",en:"Ryuta Kiln Karatsu",pref:"saga",cat:"glass",desc_ja:"唐津焼の名陶",desc_en:"Famed Karatsu kiln",verified:true},
  {i:"sa010",ja:"佐賀錦 鶴田工房",en:"Tsuruta Saga Nishiki",pref:"saga",cat:"apparel",desc_ja:"佐賀錦の伝統工芸",desc_en:"Saga Nishiki textile",deleted:true},
  {i:"sa011",ja:"伊万里牛 加工",en:"Imari Beef Processor",pref:"saga",cat:"food",desc_ja:"伊万里牛の加工",desc_en:"Imari beef processor",deleted:true},
  {i:"sa012",ja:"小城羊羹 村岡屋",en:"Muraokaya Ogi Yokan",pref:"saga",cat:"food",desc_ja:"小城羊羹の老舗",desc_en:"Heritage Ogi yokan",verified:true},
  {i:"sa013",ja:"丸ぼうろ 北島",en:"Kitajima Marubouro",pref:"saga",cat:"food",desc_ja:"佐賀丸ぼうろの老舗",desc_en:"Heritage Saga marubouro",verified:true},
  {i:"sa014",ja:"鍋島醤油",en:"Nabeshima Shoyu",pref:"saga",cat:"food",desc_ja:"佐賀の地醤油",desc_en:"Saga local soy sauce",deleted:true},
  {i:"sa015",ja:"富久千代酒造 (鍋島)",en:"Fukuchiyo Brewery (Nabeshima)",pref:"saga",cat:"sake",desc_ja:"鹿島の鍋島蔵元",desc_en:"Kashima brewer of Nabeshima",verified:true},
  {i:"sa016",ja:"天山酒造",en:"Tenzan Brewery",pref:"saga",cat:"sake",desc_ja:"小城の地酒蔵",desc_en:"Ogi local sake brewer",verified:true},
  {i:"sa017",ja:"光武酒造場",en:"Mitsutake Brewery",pref:"saga",cat:"sake",desc_ja:"鹿島の地酒蔵",desc_en:"Kashima local sake"},
  {i:"sa018",ja:"嬉野茶 副島園",en:"Soejima-en Ureshino",pref:"saga",cat:"tea",desc_ja:"嬉野茶の老舗茶園",desc_en:"Heritage Ureshino tea grower"},
  {i:"sa019",ja:"嬉野茶 マルヨシ茶業",en:"Maruyoshi Ureshino",pref:"saga",cat:"tea",desc_ja:"嬉野茶の中堅",desc_en:"Mid-size Ureshino tea",deleted:true},
  {i:"sa020",ja:"佐賀海苔 佐賀有明海漁協",en:"Saga Ariake Nori",pref:"saga",cat:"food",desc_ja:"佐賀有明海苔の加工",desc_en:"Saga Ariake nori processor"},
  {i:"sa021",ja:"伊万里・有田焼伝統陶磁器組合",en:"Arita Ceramic Coop",pref:"saga",cat:"glass",desc_ja:"有田焼の組合",desc_en:"Arita ceramic cooperative"},
  {i:"sa022",ja:"佐賀バルーン応用 (素材)",en:"Saga Balloon Materials",pref:"saga",cat:"other",desc_ja:"佐賀のバルーン素材産業",desc_en:"Saga balloon materials industry",deleted:true},

  // ========== 長崎 / NAGASAKI ==========
  {i:"nk001",ja:"カステラ 福砂屋",en:"Fukusaya Castella",pref:"nagasaki",cat:"food",desc_ja:"カステラ発祥の老舗",desc_en:"Original castella heritage",verified:true},
  {i:"nk002",ja:"カステラ 文明堂総本店",en:"Bunmeido Sohonten",pref:"nagasaki",cat:"food",desc_ja:"長崎カステラの老舗",desc_en:"Heritage Nagasaki castella",verified:true},
  {i:"nk003",ja:"カステラ 松翁軒",en:"Shooken Castella",pref:"nagasaki",cat:"food",desc_ja:"長崎カステラ松翁軒",desc_en:"Nagasaki Shooken castella",verified:true},
  {i:"nk004",ja:"波佐見焼 マルヒロ",en:"Maruhiro Hasamiyaki",pref:"nagasaki",cat:"glass",desc_ja:"波佐見焼のブランド HASAMI",desc_en:"Hasami brand of Hasami-yaki",verified:true},
  {i:"nk005",ja:"波佐見焼 西山窯",en:"Nishiyama Hasami Kiln",pref:"nagasaki",cat:"glass",desc_ja:"波佐見焼の窯元",desc_en:"Hasami-yaki kiln"},
  {i:"nk006",ja:"波佐見焼 白山陶器",en:"Hakusan Pottery",pref:"nagasaki",cat:"glass",desc_ja:"波佐見焼デザインの代表",desc_en:"Hasami design representative",verified:true},
  {i:"nk007",ja:"三川内焼 平戸洸祥団右ヱ門",en:"Mikawachi Pottery",pref:"nagasaki",cat:"glass",desc_ja:"三川内焼の老舗窯元",desc_en:"Heritage Mikawachi kiln"},
  {i:"nk008",ja:"長崎べっ甲工芸 江崎",en:"Esaki Nagasaki Bekko",pref:"nagasaki",cat:"craft",desc_ja:"長崎べっ甲の老舗",desc_en:"Heritage Nagasaki bekko",deleted:true},
  {i:"nk009",ja:"長崎ちゃんぽん 麺工房",en:"Nagasaki Champon Noodles",pref:"nagasaki",cat:"food",desc_ja:"長崎ちゃんぽん製麺",desc_en:"Nagasaki champon noodle maker",deleted:true},
  {i:"nk010",ja:"長崎ハム",en:"Nagasaki Ham",pref:"nagasaki",cat:"food",desc_ja:"長崎の老舗ハム",desc_en:"Heritage Nagasaki ham"},
  {i:"nk011",ja:"五島列島 椿油",en:"Goto Camellia Oil",pref:"nagasaki",cat:"cosmetics",desc_ja:"五島の椿油",desc_en:"Goto camellia oil",verified:true},
  {i:"nk012",ja:"五島手延うどん",en:"Goto Tenobe Udon",pref:"nagasaki",cat:"food",desc_ja:"五島の手延べうどん",desc_en:"Goto hand-stretched udon"},
  {i:"nk013",ja:"長崎ビードロ 浜屋ガラス",en:"Hamaya Vidro Nagasaki",pref:"nagasaki",cat:"glass",desc_ja:"長崎ビードロのガラス工房",desc_en:"Nagasaki vidro glass atelier",deleted:true},
  {i:"nk014",ja:"福田酒造",en:"Fukuda Brewery",pref:"nagasaki",cat:"sake",desc_ja:"平戸の老舗酒蔵",desc_en:"Hirado heritage sake brewer",verified:true},
  {i:"nk015",ja:"麦焼酎 壱岐の華",en:"Iki no Hana Shochu",pref:"nagasaki",cat:"sake",desc_ja:"壱岐の麦焼酎蔵元",desc_en:"Iki barley shochu",verified:true},
  {i:"nk016",ja:"壱岐麦焼酎 玄海酒造",en:"Genkai Shuzo Iki Shochu",pref:"nagasaki",cat:"sake",desc_ja:"壱岐麦焼酎の老舗",desc_en:"Heritage Iki barley shochu",verified:true},
  {i:"nk017",ja:"佐世保バーガー協同組合",en:"Sasebo Burger Coop",pref:"nagasaki",cat:"food",desc_ja:"佐世保バーガーのメーカー",desc_en:"Sasebo burger makers"},
  {i:"nk018",ja:"長崎電子精密",en:"Nagasaki Electron Precision",pref:"nagasaki",cat:"electronics",desc_ja:"長崎の電子部品",desc_en:"Nagasaki electronic parts",deleted:true},

  // ========== 熊本 / KUMAMOTO ==========
  {i:"km001",ja:"肥後象嵌 光助",en:"Kosuke Higo Zogan",pref:"kumamoto",cat:"craft",desc_ja:"肥後象嵌の老舗",desc_en:"Heritage Higo zogan inlay",verified:true},
  {i:"km002",ja:"肥後象嵌 田辺保正",en:"Tanabe Higo Zogan",pref:"kumamoto",cat:"craft",desc_ja:"肥後象嵌の伝統工芸士",desc_en:"Higo zogan master craftsman",deleted:true},
  {i:"km003",ja:"熊本 おばあちゃんの梅干",en:"Kumamoto Granny Umeboshi",pref:"kumamoto",cat:"food",desc_ja:"熊本の梅干し",desc_en:"Kumamoto umeboshi",deleted:true},
  {i:"km004",ja:"フジバンビ (黒糖ドーナツ)",en:"Fuji Bambi",pref:"kumamoto",cat:"food",desc_ja:"熊本の黒糖ドーナツ",desc_en:"Kumamoto kokuto donut",verified:true},
  {i:"km005",ja:"陣太鼓 お菓子の香梅",en:"Kobai Jintaiko",pref:"kumamoto",cat:"food",desc_ja:"熊本陣太鼓の老舗",desc_en:"Heritage Kumamoto Jintaiko",verified:true},
  {i:"km006",ja:"くまもとあか牛 加工",en:"Kumamoto Akaushi Beef",pref:"kumamoto",cat:"food",desc_ja:"あか牛の加工",desc_en:"Kumamoto akaushi processor",deleted:true},
  {i:"km007",ja:"高橋酒造 (白岳)",en:"Takahashi Brewery (Hakutake)",pref:"kumamoto",cat:"sake",desc_ja:"人吉の白岳球磨焼酎",desc_en:"Hitoyoshi Kuma shochu",verified:true},
  {i:"km008",ja:"球磨焼酎 繊月酒造",en:"Sengetsu Brewery",pref:"kumamoto",cat:"sake",desc_ja:"球磨焼酎の老舗",desc_en:"Heritage Kuma shochu",verified:true},
  {i:"km009",ja:"球磨焼酎 鳥飼酒造",en:"Torikai Shuzo",pref:"kumamoto",cat:"sake",desc_ja:"球磨米焼酎の老舗",desc_en:"Heritage Kuma rice shochu",verified:true},
  {i:"km010",ja:"瑞鷹酒造",en:"Zuiyo Brewery",pref:"kumamoto",cat:"sake",desc_ja:"熊本市の老舗酒蔵",desc_en:"Kumamoto heritage sake brewer",verified:true},
  {i:"km011",ja:"水前寺のり 緒方",en:"Suizenji Nori Ogata",pref:"kumamoto",cat:"food",desc_ja:"水前寺海苔の老舗",desc_en:"Heritage Suizenji nori",deleted:true},
  {i:"km012",ja:"小代焼 ふもと窯",en:"Fumoto Shodai-yaki",pref:"kumamoto",cat:"glass",desc_ja:"小代焼の窯元",desc_en:"Shodai-yaki kiln"},
  {i:"km013",ja:"天草陶磁器",en:"Amakusa Pottery",pref:"kumamoto",cat:"glass",desc_ja:"天草の陶石・陶磁器",desc_en:"Amakusa pottery",deleted:true},
  {i:"km014",ja:"い草 八代",en:"Yatsushiro Igusa",pref:"kumamoto",cat:"craft",desc_ja:"八代いぐさ畳表",desc_en:"Yatsushiro igusa tatami",deleted:true},
  {i:"km015",ja:"くまモン (熊本県食品)",en:"Kumamon Foods",pref:"kumamoto",cat:"food",desc_ja:"熊本県農産加工",desc_en:"Kumamoto food processor",deleted:true},
  {i:"km016",ja:"熊本コスメ",en:"Kumamoto Cosmetics",pref:"kumamoto",cat:"cosmetics",desc_ja:"九州由来コスメOEM",desc_en:"Kyushu-derived cosmetics OEM",deleted:true},
  {i:"km017",ja:"熊本サプリ",en:"Kumamoto Supplement",pref:"kumamoto",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"km018",ja:"阿蘇牛乳・乳製品",en:"Aso Dairy",pref:"kumamoto",cat:"food",desc_ja:"阿蘇の乳製品",desc_en:"Aso dairy products",deleted:true},

  // ========== 大分 / OITA ==========
  {i:"oi001",ja:"別府竹細工 大分県竹工芸",en:"Beppu Bamboo Craft",pref:"oita",cat:"craft",desc_ja:"別府竹細工の老舗",desc_en:"Heritage Beppu bamboo craft",verified:true},
  {i:"oi002",ja:"別府竹細工 大谷昭夫",en:"Otani Akio Bamboo",pref:"oita",cat:"craft",desc_ja:"別府竹細工の名工",desc_en:"Master Beppu bamboo artisan",deleted:true},
  {i:"oi003",ja:"湯布院の蜂蜜 山蜂会",en:"Yufuin Honey",pref:"oita",cat:"food",desc_ja:"湯布院の蜂蜜",desc_en:"Yufuin honey producer",deleted:true},
  {i:"oi004",ja:"由布院ジャム工房",en:"Yufuin Jam Atelier",pref:"oita",cat:"food",desc_ja:"湯布院のジャム",desc_en:"Yufuin jam atelier"},
  {i:"oi005",ja:"大分かぼす加工",en:"Oita Kabosu",pref:"oita",cat:"food",desc_ja:"大分かぼすの加工",desc_en:"Oita kabosu citrus processor",deleted:true},
  {i:"oi006",ja:"豊後牛 加工",en:"Bungo Beef",pref:"oita",cat:"food",desc_ja:"豊後牛の加工",desc_en:"Bungo beef processor",deleted:true},
  {i:"oi007",ja:"二階堂酒造 (麦焼酎)",en:"Nikaido Shochu",pref:"oita",cat:"sake",desc_ja:"日出町の麦焼酎蔵",desc_en:"Hiji barley shochu brewer",verified:true},
  {i:"oi008",ja:"三和酒類 (いいちこ)",en:"Sanwa Shurui (iichiko)",pref:"oita",cat:"sake",desc_ja:"宇佐の麦焼酎、いいちこ",desc_en:"Usa brewer of iichiko",verified:true},
  {i:"oi009",ja:"老松酒造",en:"Oimatsu Brewery",pref:"oita",cat:"sake",desc_ja:"日田の老舗酒蔵",desc_en:"Hita heritage sake brewer",verified:true},
  {i:"oi010",ja:"小鹿田焼 坂本工窯",en:"Sakamoto Onta Kiln",pref:"oita",cat:"glass",desc_ja:"小鹿田焼の伝統窯",desc_en:"Heritage Onta pottery",verified:true},
  {i:"oi011",ja:"日田げた 杉浦下駄店",en:"Sugiura Hita Geta",pref:"oita",cat:"wood",desc_ja:"日田下駄の老舗",desc_en:"Heritage Hita geta clogs",deleted:true},
  {i:"oi012",ja:"日田醤油 ヤマカ",en:"Yamaka Hita Shoyu",pref:"oita",cat:"food",desc_ja:"日田の老舗醤油",desc_en:"Heritage Hita soy sauce",deleted:true},
  {i:"oi013",ja:"湯布院ハム",en:"Yufuin Ham",pref:"oita",cat:"food",desc_ja:"湯布院の老舗ハム工房",desc_en:"Yufuin heritage ham atelier",deleted:true},
  {i:"oi014",ja:"大分温泉化粧品",en:"Oita Onsen Cosmetics",pref:"oita",cat:"cosmetics",desc_ja:"別府温泉素材化粧品",desc_en:"Beppu onsen-source cosmetics",deleted:true},
  {i:"oi015",ja:"大分電子工業",en:"Oita Electronics",pref:"oita",cat:"electronics",desc_ja:"大分の電子部品",desc_en:"Oita electronic parts",deleted:true},

  // ========== 宮崎 / MIYAZAKI ==========
  {i:"mz001",ja:"宮崎マンゴー加工",en:"Miyazaki Mango",pref:"miyazaki",cat:"food",desc_ja:"完熟マンゴーの加工",desc_en:"Miyazaki mango processor",deleted:true},
  {i:"mz002",ja:"日向夏加工 (上沖産業)",en:"Hyuganatsu Citrus",pref:"miyazaki",cat:"food",desc_ja:"日向夏の加工",desc_en:"Hyuganatsu citrus processor"},
  {i:"mz003",ja:"宮崎牛 加工",en:"Miyazaki Beef Processor",pref:"miyazaki",cat:"food",desc_ja:"宮崎牛の加工",desc_en:"Miyazaki beef processor",deleted:true},
  {i:"mz004",ja:"霧島酒造 (黒霧島)",en:"Kirishima Shuzo",pref:"miyazaki",cat:"sake",desc_ja:"都城の芋焼酎、黒霧島",desc_en:"Miyakonojo brewer of Kuro Kirishima",verified:true},
  {i:"mz005",ja:"雲海酒造 (そば焼酎)",en:"Unkai Shuzo",pref:"miyazaki",cat:"sake",desc_ja:"宮崎のそば焼酎",desc_en:"Miyazaki buckwheat shochu",verified:true},
  {i:"mz006",ja:"櫻の郷酒造",en:"Sakura no Sato Brewery",pref:"miyazaki",cat:"sake",desc_ja:"宮崎の地焼酎蔵",desc_en:"Miyazaki local shochu brewer"},
  {i:"mz007",ja:"宮崎食肉ハム",en:"Miyazaki Meat Ham",pref:"miyazaki",cat:"food",desc_ja:"地鶏・豚の加工",desc_en:"Local chicken & pork processor",deleted:true},
  {i:"mz008",ja:"日向木挽き",en:"Hyuga Carving",pref:"miyazaki",cat:"wood",desc_ja:"日向の木挽き工房",desc_en:"Hyuga wood carving",deleted:true},
  {i:"mz009",ja:"宮崎県内産 へべす加工",en:"Hebesu Citrus Processor",pref:"miyazaki",cat:"food",desc_ja:"宮崎へべす加工",desc_en:"Miyazaki hebesu citrus",deleted:true},
  {i:"mz010",ja:"宮崎ニット工場",en:"Miyazaki Knit",pref:"miyazaki",cat:"apparel",desc_ja:"宮崎の国産ニット",desc_en:"Miyazaki domestic knit",deleted:true},
  {i:"mz011",ja:"高千穂神楽面工房",en:"Takachiho Mask Atelier",pref:"miyazaki",cat:"craft",desc_ja:"高千穂神楽の面工房",desc_en:"Takachiho kagura mask atelier"},
  {i:"mz012",ja:"日向夏ドリンク",en:"Hyuganatsu Drink",pref:"miyazaki",cat:"food",desc_ja:"日向夏ジュース",desc_en:"Hyuganatsu juice",deleted:true},
  {i:"mz013",ja:"宮崎キャビア工房",en:"Miyazaki Caviar",pref:"miyazaki",cat:"food",desc_ja:"宮崎の国産キャビア",desc_en:"Miyazaki domestic caviar",verified:true},
  {i:"mz014",ja:"宮崎電子精密工業",en:"Miyazaki Precision",pref:"miyazaki",cat:"electronics",desc_ja:"宮崎の電子部品",desc_en:"Miyazaki electronic parts",deleted:true},
  {i:"mz015",ja:"宮崎サプリメント工房",en:"Miyazaki Supplement Atelier",pref:"miyazaki",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},

  // ========== 鹿児島 / KAGOSHIMA ==========
  {i:"kr001",ja:"薩摩切子 島津興業",en:"Satsuma Kiriko Shimadzu",pref:"kagoshima",cat:"glass",desc_ja:"薩摩切子の現代復興",desc_en:"Modern Satsuma kiriko revival",verified:true},
  {i:"kr002",ja:"薩摩切子 仙巌園",en:"Senganen Satsuma Kiriko",pref:"kagoshima",cat:"glass",desc_ja:"仙巌園の薩摩切子",desc_en:"Senganen Satsuma kiriko",verified:true,deleted:true},
  {i:"kr003",ja:"薩摩焼 沈壽官窯",en:"Chin Jukan Satsuma-yaki",pref:"kagoshima",cat:"glass",desc_ja:"薩摩焼の名門窯",desc_en:"Famed Satsuma-yaki lineage",verified:true},
  {i:"kr004",ja:"沈壽官窯",en:"Naeshirogawa Satsuma",pref:"kagoshima",cat:"glass",desc_ja:"薩摩焼の伝統窯",desc_en:"Satsuma traditional kiln"},
  {i:"kr005",ja:"薩摩芋焼酎 西酒造 (薩摩宝山)",en:"Nishi Shuzo (Hozan)",pref:"kagoshima",cat:"sake",desc_ja:"日置の芋焼酎、宝山",desc_en:"Hioki brewer of Hozan",verified:true},
  {i:"kr006",ja:"株式会社黒木本店",en:"Kuroki Brewery (Maou)",pref:"miyazaki",cat:"sake",desc_ja:"芋焼酎の幻の蔵元 (※宮崎)",desc_en:"Phantom shochu maker (Miyazaki)"},
  {i:"kr007",ja:"薩摩酒造 (さつま白波)",en:"Satsuma Shuzo",pref:"kagoshima",cat:"sake",desc_ja:"枕崎のさつま白波蔵元",desc_en:"Makurazaki Satsuma Shiranami",verified:true},
  {i:"kr008",ja:"村尾酒造 (村尾)",en:"Murao Brewery",pref:"kagoshima",cat:"sake",desc_ja:"薩摩川内の村尾蔵元",desc_en:"Satsumasendai brewer of Murao",verified:true},
  {i:"kr009",ja:"小正醸造 (メローコヅル)",en:"Komasa Brewery",pref:"kagoshima",cat:"sake",desc_ja:"日置の焼酎蔵",desc_en:"Hioki shochu brewer",verified:true},
  {i:"kr010",ja:"焼酎の祁答院蒸溜所",en:"Kedoin Distillery",pref:"kagoshima",cat:"sake",desc_ja:"鹿児島の本格芋焼酎",desc_en:"Kagoshima authentic imo shochu"},
  {i:"kr011",ja:"枕崎かつお節 山吉国澤百馬商店",en:"Yamayoshi Katsuobushi",pref:"kagoshima",cat:"food",desc_ja:"枕崎かつお節の老舗",desc_en:"Heritage Makurazaki katsuobushi",verified:true},
  {i:"kr012",ja:"指宿砂むし 砂湯化粧品",en:"Ibusuki Sand Cosmetics",pref:"kagoshima",cat:"cosmetics",desc_ja:"指宿温泉化粧品",desc_en:"Ibusuki onsen cosmetics"},
  {i:"kr013",ja:"鹿児島黒豚加工",en:"Kagoshima Kurobuta",pref:"kagoshima",cat:"food",desc_ja:"鹿児島黒豚の加工",desc_en:"Kagoshima black pork processor",deleted:true},
  {i:"kr014",ja:"屋久杉工芸",en:"Yakusugi Craft",pref:"kagoshima",cat:"wood",desc_ja:"屋久杉の伝統工芸",desc_en:"Yakusugi traditional craft",deleted:true},
  {i:"kr015",ja:"大島紬 工房",en:"Oshima Tsumugi Atelier",pref:"kagoshima",cat:"apparel",desc_ja:"奄美大島紬の伝統工芸",desc_en:"Amami Oshima tsumugi"},
  {i:"kr016",ja:"奄美黒糖焼酎 朝日酒造",en:"Asahi Brewery Amami",pref:"kagoshima",cat:"sake",desc_ja:"奄美の黒糖焼酎蔵",desc_en:"Amami brown-sugar shochu",verified:true},
  {i:"kr017",ja:"奄美 まーらん舟編組工房",en:"Amami Bamboo Atelier",pref:"kagoshima",cat:"craft",desc_ja:"奄美の竹編み工房",desc_en:"Amami bamboo weaving",deleted:true},
  {i:"kr018",ja:"鹿児島サプリ研究所",en:"Kagoshima Supplement",pref:"kagoshima",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"kr019",ja:"鹿児島茶 知覧",en:"Chiran Tea",pref:"kagoshima",cat:"tea",desc_ja:"知覧茶の茶園",desc_en:"Chiran tea grower",verified:true},
  {i:"kr020",ja:"頴娃茶協同",en:"Ei Cha Coop",pref:"kagoshima",cat:"tea",desc_ja:"南九州の茶生産組合",desc_en:"South Kyushu tea coop",deleted:true},

  // ========== 沖縄 / OKINAWA ==========
  {i:"ow001",ja:"琉球紅型 城間紅型工房",en:"Shiroma Bingata",pref:"okinawa",cat:"apparel",desc_ja:"琉球紅型の人間国宝家系",desc_en:"Ryukyu bingata Living Treasure",verified:true},
  {i:"ow002",ja:"琉球紅型 知念紅型",en:"Chinen Bingata",pref:"okinawa",cat:"apparel",desc_ja:"琉球紅型の伝統工房",desc_en:"Ryukyu bingata atelier"},
  {i:"ow003",ja:"琉球ガラス工房 奥原硝子",en:"Okuhara Ryukyu Glass",pref:"okinawa",cat:"glass",desc_ja:"琉球ガラスの老舗",desc_en:"Heritage Ryukyu glass",verified:true},
  {i:"ow004",ja:"琉球ガラス 稲嶺盛吉ガラス工房",en:"Inamine Ryukyu Glass",pref:"okinawa",cat:"glass",desc_ja:"琉球ガラスの巨匠",desc_en:"Master of Ryukyu glass",verified:true},
  {i:"ow005",ja:"琉球ガラス 海風ガラス",en:"Umikaze Ryukyu Glass",pref:"okinawa",cat:"glass",desc_ja:"沖縄のガラス工房",desc_en:"Okinawa glass atelier"},
  {i:"ow006",ja:"壺屋焼 育陶園",en:"Ikutoen Tsuboya-yaki",pref:"okinawa",cat:"glass",desc_ja:"壺屋焼の老舗窯元",desc_en:"Heritage Tsuboya-yaki",verified:true},
  {i:"ow007",ja:"有限会社育陶園",en:"Aragaki Tsuboya",pref:"okinawa",cat:"glass",desc_ja:"壺屋焼の伝統窯",desc_en:"Tsuboya traditional kiln"},
  {i:"ow008",ja:"シーサー工房 比嘉陶器",en:"Higa Shisa Atelier",pref:"okinawa",cat:"glass",desc_ja:"沖縄シーサーの工房",desc_en:"Okinawa shisa atelier",deleted:true},
  {i:"ow009",ja:"久米島紬 久米島紬の里",en:"Kumejima Tsumugi",pref:"okinawa",cat:"apparel",desc_ja:"久米島紬の伝統工房",desc_en:"Kumejima tsumugi atelier",verified:true},
  {i:"ow010",ja:"芭蕉布 喜如嘉",en:"Kijoka Bashofu",pref:"okinawa",cat:"apparel",desc_ja:"喜如嘉の芭蕉布",desc_en:"Kijoka banana-fiber textile",verified:true},
  {i:"ow011",ja:"宮古上布 宮古織物",en:"Miyako Jofu Weaver",pref:"okinawa",cat:"apparel",desc_ja:"宮古上布の伝統工芸",desc_en:"Miyako jofu textile"},
  {i:"ow012",ja:"瑞泉酒造 (泡盛)",en:"Zuisen Distillery",pref:"okinawa",cat:"sake",desc_ja:"那覇の泡盛老舗",desc_en:"Heritage Naha awamori",verified:true},
  {i:"ow013",ja:"久米仙酒造 (泡盛)",en:"Kumesen Distillery",pref:"okinawa",cat:"sake",desc_ja:"沖縄泡盛の代表蔵",desc_en:"Representative Okinawa awamori",verified:true},
  {i:"ow014",ja:"忠孝酒造 (泡盛)",en:"Chuko Distillery",pref:"okinawa",cat:"sake",desc_ja:"豊見城の泡盛蔵",desc_en:"Tomigusuku awamori brewer",verified:true},
  {i:"ow015",ja:"請福酒造 (石垣泡盛)",en:"Seifuku Distillery",pref:"okinawa",cat:"sake",desc_ja:"石垣島の泡盛蔵",desc_en:"Ishigaki awamori brewer",verified:true},
  {i:"ow016",ja:"沖縄 黒糖加工",en:"Okinawa Kokuto",pref:"okinawa",cat:"food",desc_ja:"離島の黒糖加工",desc_en:"Okinawa islands kokuto sugar"},
  {i:"ow017",ja:"沖縄ちんすこう 新垣菓子店",en:"Aragaki Chinsuko",pref:"okinawa",cat:"food",desc_ja:"沖縄ちんすこうの老舗",desc_en:"Heritage Okinawa chinsuko",verified:true},
  {i:"ow018",ja:"沖縄塩 ぬちまーす",en:"Nuchimasu Salt",pref:"okinawa",cat:"food",desc_ja:"沖縄のミネラル塩",desc_en:"Okinawa mineral salt",verified:true},
  {i:"ow019",ja:"沖縄美ら海コスメ",en:"Okinawa Churaumi Cosme",pref:"okinawa",cat:"cosmetics",desc_ja:"沖縄海洋深層水コスメ",desc_en:"Okinawa deep-sea water cosmetics",deleted:true},
  {i:"ow020",ja:"沖縄シークヮーサー加工",en:"Okinawa Shikuwasa",pref:"okinawa",cat:"food",desc_ja:"沖縄シークヮーサー加工",desc_en:"Okinawa shikuwasa processor",deleted:true},
);
// data3.js ends — 全国 1000+ companies loaded
