// 公式サイトURLパッチ
// 確度が高い既知URLのみ収録。それ以外の会社は app.js 側で
// Google検索フォールバックボタンが表示される（誤URLを表示するより安全）。
// URL変更があれば随時更新可能。

const KNOWN_URLS = {
  // === 北海道 ===
  "hk001": "https://www.rokkatei.co.jp/",
  "hk002": "https://www.royce.com/",
  "hk004": "https://www.ishiya.co.jp/",
  "hk006": "https://www.tomoechan.co.jp/",
  "hk008": "https://www.sato-suisan.co.jp/",
  "hk009": "https://www.kitakaro.com/",
  "hk010": "https://www.kinotoya.com/",
  "hk011": "https://www.hokkaidowine.com/",
  "hk012": "https://www.nipponseishu.co.jp/",
  "hk013": "https://www.otokoyama.com/",
  "hk014": "https://www.takasagoshuzo.com/",
  "hk015": "https://www.kunimare.co.jp/",
  "hk018": "https://shiro-shiro.jp/",
  "hk020": "https://www.northfarmstock.com/",
  "hk024": "https://www.condehouse.co.jp/",
  "hk026": "https://www.kitanosumai-sekkeisha.com/",
  "hk029": "https://www.aminoup.co.jp/",

  // === 青森 ===
  "am002": "https://tsugaruvidro.jp/",
  "am005": "https://www.shinyapple.jp/",
  "am006": "https://kaneshou.co.jp/",
  "am008": "https://hachinohe-shuzo.com/",
  "am009": "https://www.densyu.co.jp/",
  "am016": "https://www.aomoriai.com/",

  // === 岩手 ===
  "iw001": "https://oitomi.jp/",
  "iw002": "https://www.iwachu.co.jp/",
  "iw004": "https://oigen.jp/",
  "iw005": "https://suzukimorihisa.com/",
  "iw009": "https://www.nanbubijin.co.jp/",
  "iw010": "https://www.asabiraki-net.jp/",
  "iw011": "https://kikunotsukasa.jp/",
  "iw013": "https://iwaizumi-milk.co.jp/",

  // === 宮城 ===
  "mg004": "https://www.sasaju.co.jp/",
  "mg005": "https://www.abekama.co.jp/",
  "mg007": "https://www.kanezaki.co.jp/",
  "mg008": "https://www.ichinokura.co.jp/",
  "mg009": "https://www.urakasumi.com/",
  "mg010": "https://hirakoushuzou.co.jp/",
  "mg016": "https://www.rikyu-gyutan.co.jp/",

  // === 秋田 ===
  "ak001": "https://magewappa.com/",
  "ak002": "https://magewappa.co.jp/",
  "ak005": "https://www.mugendo.jp/",
  "ak006": "https://www.sato-yoske.co.jp/",
  "ak007": "https://www.aramasa.jp/",
  "ak008": "https://www.takashimizu.co.jp/",
  "ak009": "https://www.ryozeki.co.jp/",
  "ak015": "https://yatsuyanagi.jp/",
  "ak016": "https://denshiro.jp/",

  // === 山形 ===
  "yg001": "https://www.dewazakura.co.jp/",
  "yg005": "https://www.toko-sake.co.jp/",
  "yg007": "https://www.tendo-mokko.co.jp/",
  "yg008": "https://www.satoseni.com/",
  "yg012": "https://kikuchi-hojudo.com/",
  "yg013": "https://oc-jp.com/",

  // === 福島 ===
  "fk001": "https://www.suzuzen.com/",
  "fk003": "https://www.sake-suehiro.jp/",
  "fk004": "https://miyaizumi.co.jp/",
  "fk006": "https://www.daishichi.com/",
  "fk007": "https://www.okunomatsu.co.jp/",

  // === 茨城 ===
  "ib001": "https://www.kodawari.cc/",
  "ib002": "https://www.meirishurui.com/",
  "ib003": "https://www.fuchuhomare.com/",
  "ib004": "https://www.raifuku.co.jp/",
  "ib008": "https://www.tengunatto.com/",
  "ib013": "https://yukitumugi.co.jp/",

  // === 栃木 ===
  "tg001": "https://www.tsukamoto.net/",
  "tg004": "https://www.sohomare.co.jp/",
  "tg005": "https://senkin.co.jp/",
  "tg014": "https://www.tochigi-leather.com/",

  // === 群馬 ===
  "gm002": "https://www.yokoodairyfoods.co.jp/",
  "gm005": "https://www.osawaya.co.jp/",
  "gm006": "https://www.tamaruya.jp/",

  // === 埼玉 ===
  "st002": "https://www.kurazukuri.com/",
  "st003": "https://www.koedo-kameya.com/",
  "st005": "https://saitama-ogawawashi.jp/",
  "st007": "https://kagamiyama.jp/",
  "st008": "https://www.shinkame.co.jp/",
  "st010": "https://www.one-drinks.com/",
  "st011": "https://www.chichibu-nishiki.co.jp/",
  "st016": "https://www.sekiguchien-shop.com/",
  "st017": "https://www.hirumaen.com/",

  // === 千葉 ===
  "cb002": "https://www.nagomi-yoneya.co.jp/",
  "cb003": "https://www.holland-ya.jp/",
  "cb004": "https://www.higeta.co.jp/",
  "cb005": "https://www.yamasa.com/",
  "cb006": "https://www.miyashoyu.co.jp/",
  "cb008": "https://www.iinumahonke.co.jp/",
  "cb009": "https://www.nabedana.co.jp/",
  "cb010": "https://kankiku.com/",
  "cb024": "https://www.kikkoman.co.jp/manjo/",

  // === 東京 ===
  "tk001": "https://www.horiguchiglass.com/",
  "tk002": "https://kiriko.net/",
  "tk003": "https://www.hanashyo.com/",
  "tk004": "https://www.kimotoglass.tokyo/",
  "tk005": "https://hirota-glass.co.jp/",
  "tk006": "https://www.nakagawa-masashichi.jp/",
  "tk009": "https://tsuchiya-kaban.jp/",
  "tk010": "https://www.hamano.co.jp/",
  "tk013": "https://www.tokyomatsuya.co.jp/",
  "tk014": "https://www.ozuwashi.net/",
  "tk015": "https://www.haibara.co.jp/",
  "tk016": "https://www.kyukyodo.co.jp/",
  "tk017": "https://www.ibasen.co.jp/",
  "tk018": "https://www.hakuchikudo.co.jp/",
  "tk021": "https://www.mori-silver.co.jp/",
  "tk024": "https://www.murata-megane.co.jp/",
  "tk025": "https://www.kaneko-optical.co.jp/",
  "tk026": "https://www.kiya-hamono.co.jp/",
  "tk027": "https://ubukeya.com/",
  "tk028": "https://www.kikuhide.jp/",
  "tk029": "https://kama-asa.co.jp/",
  "tk030": "https://www.kappabashi.or.jp/",
  "tk028b": "https://www.tomita-senkougei.com/",
  "tk033": "https://www.onoya.com/",
  "tk034": "https://funawa.jp/",
  "tk035": "https://www.kameju.com/",
  "tk036": "https://www.toraya-group.co.jp/",
  "tk038": "https://sembikiya.co.jp/",
  "tk039": "https://www.eitaro.com/",
  "tk043": "https://www.yamamotoyama.co.jp/",
  "tk054": "https://www.ayura.co.jp/",
  "tk056": "https://osaji.net/",
  "tk057": "https://andbe-official.com/",
  "tk058": "https://www.toonecosmetics.com/",
  "tk069": "https://www.sawanoi-sake.com/",
  "tk070": "https://www.tamajiman.co.jp/",
  "tk072": "https://www.seishu-kasen.com/",
  "tk076": "https://www.edofurin.com/",

  // === 神奈川 ===
  "kn001": "https://www.hakkodo.jp/",
  "kn003": "https://www.hato.co.jp/",
  "kn004": "https://www.beniya-ajisai.co.jp/",
  "kn006": "https://kiyoken.com/",
  "kn008": "https://www.kamaboko.com/",
  "kn009": "https://www.kagosei.co.jp/",
  "kn012": "https://www.yoseki.com/",
  "kn027": "https://setosyuzou.com/",
  "kn028": "https://www.kawanishiya.com/",

  // === 新潟 (燕三条) ===
  "ng001": "https://www.gyokusendo.com/",
  "ng002": "https://www.suwada.co.jp/",
  "ng003": "https://tojiro.net/",
  "ng004": "https://www.tadafusa.com/",
  "ng006": "https://www.snowpeak.co.jp/",
  "ng007": "https://www.marunao.com/",
  "ng010": "https://yamazaki-kk.com/",
  "ng012": "https://wahei.co.jp/",
  "ng014": "https://hinoura-knife.com/",
  "ng016": "https://www.asahi-shuzo.co.jp/",
  "ng017": "https://www.hakkaisan.com/",
  "ng018": "https://www.jozen.co.jp/",
  "ng019": "https://www.imayotsukasa.co.jp/",
  "ng020": "https://imayotsukasa.co.jp/",
  "ng033": "https://www.migaki-ya.com/",
  "ng038": "https://www.kamite.co.jp/",
  "ng041": "https://www.sado-milk.co.jp/",
  "ng044": "https://tsunan-sake.com/",
  "ng045": "https://www.ichishima.jp/",
  "ng047": "https://www.echigoseika.co.jp/",

  // === 富山 ===
  "ty001": "https://www.oigo.jp/",
  "ty002": "https://www.nousaku.co.jp/",
  "ty003": "https://yotsukawa.com/",
  "ty004": "https://mf-orii.co.jp/",
  "ty005": "https://syouryu.shimatani.co.jp/",
  "ty006": "https://www.koukandou.co.jp/",
  "ty007": "https://www.hangontan.co.jp/",
  "ty009": "https://www.tateyama.jp/",
  "ty010": "https://www.masuizumi.co.jp/",
  "ty012": "https://www.mabotaru.co.jp/",
  "ty013": "https://aimono-konbu.com/",
  "ty014": "https://umekama.co.jp/",
  "ty015": "https://www.minamoto.co.jp/",
  "ty016": "https://www.inamichoukoku.jp/",
  "ty018": "https://www.gokayama-washi.jp/",
  "ty020": "https://toyama-garasukobo.jp/",

  // === 石川 ===
  "is001": "https://www.hakuichi.co.jp/",
  "is002": "https://www.kinpaku.co.jp/",
  "is004": "https://www.kaburaki.jp/",
  "is005": "https://kutaniseiyou.co.jp/",
  "is006": "https://choemon.com/",
  "is007": "https://hakuza.co.jp/",
  "is008": "https://www.kirimoto.net/",
  "is010": "https://www.tayashikkiten.co.jp/",
  "is014": "https://www.fukumitsuya.co.jp/",
  "is015": "https://noguchi-naohiko.co.jp/",
  "is016": "https://www.sogen-shuzou.com/",
  "is019": "https://kintuba.co.jp/",
  "is020": "https://www.kagaboucha.co.jp/",
  "is021": "https://hakusan-syuzo.com/",

  // === 福井 ===
  "fi002": "https://www.kaneko-optical.co.jp/",
  "fi003": "https://www.bjclassic.jp/",
  "fi004": "https://www.bostonclub.co.jp/",
  "fi005": "https://hakusan-megane.co.jp/",
  "fi006": "https://www.fournines.co.jp/",
  "fi007": "https://www.shitsurindo.com/",
  "fi009": "https://ryusen-hamono.com/",
  "fi010": "https://www.knife-takamura.com/",
  "fi011": "https://www.iwano-ichibei.jp/",
  "fi012": "https://www.washiya.com/",
  "fi015": "https://www.kokuryu.co.jp/",
  "fi016": "https://www.born.co.jp/",
  "fi018": "https://www.matsukan.com/",
  "fi019": "https://www.hyozaemon.co.jp/",

  // === 山梨 ===
  "ym004": "https://www.katsunuma-winery.com/",
  "ym005": "https://www.grace-wine.com/",
  "ym006": "https://www.lumiere.jp/",
  "ym007": "https://www.rubaiyat.jp/",
  "ym008": "https://www.sake-shichiken.co.jp/",
  "ym009": "https://www.takenoi.jp/",
  "ym010": "https://www.kikyouya.co.jp/",
  "ym011": "https://www.kinseiken.co.jp/",

  // === 長野 ===
  "nn002": "https://marutaka-suwa.com/",
  "nn004": "https://www.obinata.co.jp/",
  "nn006": "https://www.shinshuham.co.jp/",
  "nn007": "https://www.hakubanishiki.com/",
  "nn008": "https://www.masumi.co.jp/",
  "nn009": "https://maihime.co.jp/",
  "nn010": "https://www.obusewinery.com/",
  "nn011": "https://obusedo.com/",
  "nn012": "https://www.chikufudo.com/",
  "nn013": "https://www.matsumin.com/",

  // === 岐阜 ===
  "gf002": "https://sakuzan.co.jp/",
  "gf003": "https://www.barbar.co.jp/",
  "gf007": "https://www.kai-group.com/",
  "gf009": "https://sumikama.co.jp/",
  "gf011": "https://www.iedashikou.com/",
  "gf014": "https://oakv.co.jp/",
  "gf015": "https://www.hidasangyo.com/",
  "gf016": "https://www.kashiwa.gr.jp/",
  "gf017": "https://www.hakusen.co.jp/",
  "gf018": "https://www.kosaka-syuzou.com/",
  "gf019": "https://www.sake-hourai.co.jp/",
  "gf022": "https://www.ozeki-lantern.co.jp/",

  // === 静岡 ===
  "sz007": "https://nanaya-matcha.com/",
  "sz014": "https://www.shunkado.co.jp/",
  "sz015": "https://www.jiichiro.com/",
  "sz016": "https://www.yamadaichi.com/",
  "sz019": "https://katsuobushi.com/",
  "sz020": "https://www.isojiman-sake.jp/",
  "sz022": "https://hananomai.co.jp/",
  "sz023": "https://shidaizumi.com/",

  // === 愛知 ===
  "ai003": "https://www.setohongyo.jp/",
  "ai005": "https://www.takedakahei.co.jp/",
  "ai007": "https://kawai-fude.jp/",
  "ai010": "https://www.kakukyu.jp/",
  "ai011": "https://www.maruyahatcho.com/",
  "ai012": "https://www.nakamo.co.jp/",
  "ai014": "https://www.myokoen.com/",
  "ai016": "https://www.kuheiji.co.jp/",
  "ai017": "https://www.nemuri-tonbo.com/",

  // === 三重 ===
  "me001": "https://www.kadoyabeer.com/",
  "me002": "https://www.akafuku.co.jp/",
  "me003": "https://henbaya.jp/",
  "me005": "https://www.mikimoto-pearl.com/",
  "me007": "https://osugikatagami.jp/",
  "me008": "https://isemomen.co.jp/",
  "me012": "https://www.igamono.co.jp/",
  "me014": "https://www.hanzo-sake.com/",
  "me015": "https://seizaburo.jp/",
  "me016": "https://hayakawasyuzou.jp/",

  // === 滋賀 ===
  "sg001": "https://meizan.com/",
  "sg002": "https://furutani.co/",
  "sg007": "https://tsuruyapan.jp/",
  "sg008": "https://kanou.com/",
  "sg009": "https://clubharie.jp/",
  "sg010": "https://taneya.jp/",
  "sg012": "https://www.fukui-yahei.co.jp/",
  "sg013": "https://kirakucho.jp/",
  "sg014": "https://www.7yari.co.jp/",

  // === 京都 ===
  "ky001": "https://www.hosoo.co.jp/",
  "ky002": "https://www.kawashimaselkon.com/",
  "ky004": "https://www.kondaya.com/",
  "ky005": "https://www.tatsumura.co.jp/",
  "ky006": "https://www.chiso.co.jp/",
  "ky009": "https://www.aiba-kyouchiwa.jp/",
  "ky010": "https://www.baisenan.co.jp/",
  "ky011": "https://www.hakuchikudo.co.jp/",
  "ky012": "https://www.asahido.co.jp/",
  "ky015": "https://www.wagasa.com/",
  "ky016": "https://www.zohiko.co.jp/",
  "ky019": "https://www.yasuda-juzu.co.jp/",
  "ky021": "https://www.kohchosai.co.jp/",
  "ky022": "https://www.turuya.co.jp/",
  "ky023": "https://www.toraya-group.co.jp/",
  "ky024": "https://oimatu.co.jp/",
  "ky025": "https://www.kyoto-suetomi.com/",
  "ky026": "https://7jyo-kansyundo.co.jp/",
  "ky027": "https://www.tokichi.jp/",
  "ky028": "https://www.itohkyuemon.co.jp/",
  "ky029": "https://www.marukyu-koyamaen.co.jp/",
  "ky030": "https://www.morihan.com/",
  "ky031": "https://www.giontsujiri.co.jp/",
  "ky032": "https://www.fukujuen.com/",
  "ky033": "https://www.ippodo-tea.co.jp/",
  "ky034": "https://www.yojiya.co.jp/",
  "ky036": "https://www.hakuhodo.jp/",
  "ky038": "https://nemohamo.com/",
  "ky040": "https://maikohan.com/",
  "ky041": "https://www.gekkeikan.co.jp/",
  "ky042": "https://shotoku.co.jp/",
  "ky043": "https://jukondo.jp/",
  "ky045": "https://eikun.com/",
  "ky046": "https://www.tamanohikari.co.jp/",
  "ky047": "https://www.nishiri.co.jp/",
  "ky048": "https://www.daiyasu.co.jp/",
  "ky050": "https://www.hanbey.co.jp/",
  "ky051": "https://www.fuka-kyoto.com/",
  "ky054": "https://www.chidorisu.co.jp/",
  "ky055": "https://www.yatsuhashi.co.jp/",
  "ky056": "https://www.shogoin.co.jp/",
  "ky059": "https://www.shoyeido.co.jp/",
  "ky060": "https://www.yamadamatsu.co.jp/",

  // === 大阪 ===
  "os002": "https://www.aritsugu.com/",
  "os003": "https://www.sakaitakayuki.co.jp/",
  "os005": "https://www.aoki-hamono.co.jp/",
  "os027": "https://www.ogkkabuto.co.jp/",

  // === 兵庫 ===
  "hy001": "https://www.kikumasamune.co.jp/",
  "hy002": "https://www.hakutsuru.co.jp/",
  "hy003": "https://www.kenbishi.co.jp/",
  "hy004": "https://www.sawanotsuru.co.jp/",
  "hy005": "https://www.konishi.co.jp/",
  "hy006": "https://www.taturiki.com/",
  "hy014": "https://www.kobe-fugetsudo.co.jp/",
  "hy015": "https://www.morozoff.co.jp/",
  "hy017": "https://www.ibonoito.or.jp/",
  "hy021": "https://cocomeister.jp/",
  "hy023": "https://toyooka-kaban.jp/",

  // === 奈良 ===
  "na001": "https://www.akashiya-fude.co.jp/",
  "na002": "https://kobaien.jp/",
  "na004": "https://take-yamada.com/",
  "na009": "https://www.yu-nakagawa.co.jp/",
  "na012": "https://www.miwayama.co.jp/",
  "na013": "https://www.ikeri.co.jp/",
  "na015": "https://www.naraduke.co.jp/",
  "na016": "https://www.harushika.com/",
  "na017": "https://www.umenoyado.com/",
  "na018": "https://www.yucho-sake.jp/",
  "na020": "https://www.kudzu.co.jp/",

  // === 和歌山 ===
  "wk002": "https://www.nakatafoods.co.jp/",
  "wk003": "https://www.kishu-umeboshi.jp/",
  "wk009": "https://www.nakano-group.co.jp/",
  "wk010": "https://www.kunokuni.co.jp/",
  "wk011": "https://www.sekaiitto.co.jp/",
  "wk012": "https://www.kadocho.co.jp/",
  "wk013": "https://www.marushinhonke.com/",
  "wk015": "https://kannonyama.com/",

  // === 鳥取・島根 ===
  "tt005": "https://chiyomusubi.co.jp/",
  "sh002": "https://www.haneyasoba.co.jp/",
  "sh004": "https://www.rihaku.co.jp/",
  "sh008": "https://nakaura.co.jp/",
  "sh009": "https://www.gungendo.co.jp/",

  // === 岡山 ===
  "ok005": "https://betty.co.jp/",
  "ok006": "https://www.momotarojeans.com/",
  "ok007": "https://www.japanblue-jeans.com/",
  "ok008": "https://www.bigjohn.co.jp/",
  "ok009": "https://www.evisu.com/",
  "ok011": "https://www.koeido.co.jp/",
  "ok014": "https://www.msb.co.jp/",
  "ok015": "https://www.sake-okayama.com/",
  "ok016": "https://www.chikurin.jp/",
  "ok018": "https://www.kurashiki-hanpu.co.jp/",
  "ok019": "https://www.classiky.co.jp/",

  // === 広島 ===
  "hi001": "https://www.hakuhodo.jp/",
  "hi002": "https://www.chikuhodo.com/",
  "hi003": "https://www.koyudo.co.jp/",
  "hi006": "https://miyajima-shamoji.jp/",
  "hi007": "https://nisikido.co.jp/",
  "hi008": "https://yamadaya.co.jp/",
  "hi009": "https://www.momiji.co.jp/",
  "hi010": "https://www.otafuku.co.jp/",
  "hi013": "https://hakubotan.co.jp/",
  "hi014": "https://www.kamoizumi.co.jp/",
  "hi015": "https://www.kireinishu.jp/",
  "hi017": "https://www.taketsuru.co.jp/",

  // === 山口 ===
  "yc001": "https://oyogama.com/",
  "yc002": "https://www.sakakurashinbei.com/",
  "yc003": "https://miwagama.com/",
  "yc005": "https://www.asahishuzo.ne.jp/",
  "yc006": "https://yaoshin.co.jp/",
  "yc007": "https://gokyo-sake.co.jp/",

  // === 徳島・香川・愛媛・高知 ===
  "ts001": "https://furushou.jp/",
  "ts002": "https://www.buaisou-i.com/",
  "ts003": "https://www.awagami.jp/",
  "ts008": "https://www.narutotai.jp/",
  "ts010": "https://wasanbon.co.jp/",
  "kg003": "https://ishimaru-seimen.co.jp/",
  "kg005": "https://www.marugameuchiwa.jp/",
  "kg007": "https://yama-roku.net/",
  "kg008": "https://www.marukin-shoyu.com/",
  "kg009": "https://shodoshima.or.jp/",
  "kg010": "https://kotobukinishino.com/",
  "kg011": "https://kawatsuru.com/",
  "kg012": "https://kinashibonsai.com/",
  "kg014": "https://www.ikkaku.co.jp/",
  "eh001": "https://www.kontex.co.jp/",
  "eh002": "https://www.ikeuchi.org/",
  "eh003": "https://kusu-mon.com/",
  "eh005": "https://www.itoweb.com/",
  "eh006": "https://www.tobeyaki.co.jp/",
  "eh009": "https://kirinomori.co.jp/",
  "eh010": "https://www.umenishiki.com/",
  "eh011": "https://www.ishizuchi.co.jp/",
  "eh012": "https://www.dogobeer.co.jp/",
  "kc003": "https://www.toyokuni.net/",
  "kc005": "https://www.tsukasabotan.co.jp/",
  "kc006": "https://www.mutemuka.com/",
  "kc007": "https://umajimura.jp/",

  // === 福岡 ===
  "fo001": "https://www.nishimuraori.com/",
  "fo003": "https://nakamura-ningyo.com/",
  "fo005": "https://www.meigetsudo.co.jp/",
  "fo006": "https://www.hiyoko.co.jp/",
  "fo007": "https://josuian.jp/",
  "fo008": "https://www.kubara.jp/",
  "fo009": "https://www.kayanoya.com/",
  "fo010": "https://www.fukusaya.co.jp/",
  "fo011": "https://www.fukuya.com/",
  "fo012": "https://www.yamaya.com/",
  "fo014": "https://hayakawa-toubou.com/",
  "fo016": "https://www.ikeda-kasuri.jp/",
  "fo017": "https://shimokawaorimono.com/",
  "fo019": "https://www.kitaya.co.jp/",
  "fo020": "https://www.shiraito.com/",
  "fo021": "https://www.morinokura.co.jp/",

  // === 佐賀・長崎 ===
  "sa001": "https://www.koransha.co.jp/",
  "sa002": "https://www.fukagawa-seiji.co.jp/",
  "sa003": "https://www.gen-emon.co.jp/",
  "sa004": "https://www.kakiemon.co.jp/",
  "sa005": "https://imaemon.co.jp/",
  "sa007": "https://hataman.jp/",
  "sa008": "https://www.taroemon.com/",
  "sa009": "https://www.ryuta-gama.com/",
  "sa012": "https://www.muraokaya.co.jp/",
  "sa013": "https://www.kitajimaya.co.jp/",
  "sa015": "https://nabeshima.co.jp/",
  "sa016": "https://www.tenzan.co.jp/",
  "sa017": "https://www.mitsutake.co.jp/",
  "nk001": "https://www.castella.co.jp/",
  "nk002": "https://www.bunmeido.ne.jp/",
  "nk003": "https://shooken.com/",
  "nk004": "https://www.hasamiyaki.jp/",
  "nk006": "https://www.hakusan-porcelain.co.jp/",
  "nk011": "https://www.tsubaki-abura.jp/",
  "nk014": "https://www.fukudashuzou.co.jp/",
  "nk015": "https://ikinohana.co.jp/",
  "nk016": "https://genkai-sake.com/",

  // === 熊本・大分・宮崎・鹿児島 ===
  "km001": "https://www.kosuke-zougan.com/",
  "km004": "https://fuji-bambi.com/",
  "km005": "https://www.kobai.jp/",
  "km007": "https://hakutake.co.jp/",
  "km008": "https://sengetsu.co.jp/",
  "km009": "https://torikai.jp/",
  "km010": "https://www.zuiyo.co.jp/",
  "oi001": "https://www.takeko.jp/",
  "oi007": "https://www.nikaido-shuzo.co.jp/",
  "oi008": "https://www.iichiko.co.jp/",
  "oi009": "https://www.oimatsu.com/",
  "oi010": "https://onta-yaki-sakamoto.com/",
  "mz004": "https://www.kirishima.co.jp/",
  "mz005": "https://www.unkai.co.jp/",
  "mz013": "https://miyazaki-caviar.com/",
  "kr001": "https://www.satsumakiriko.jp/",
  "kr003": "https://chin-jukan.co.jp/",
  "kr005": "https://www.hozan.jp/",
  "kr007": "https://www.satsuma.co.jp/",
  "kr008": "https://murao-shuzo.jp/",
  "kr009": "https://www.komasa.co.jp/",
  "kr011": "https://yamayoshi-honten.com/",
  "kr016": "https://www.kokuto.co.jp/",
  "kr019": "https://chiran-cha.com/",

  // === 沖縄 ===
  "ow001": "https://shiroma-bingata.com/",
  "ow003": "https://okuhara-glass.com/",
  "ow004": "https://inamine-glass.com/",
  "ow006": "https://www.ikutouen.com/",
  "ow009": "https://www.kumejimatsumugi.com/",
  "ow010": "https://kijoka.jp/",
  "ow012": "https://www.zuisen.co.jp/",
  "ow013": "https://www.k-kumesen.co.jp/",
  "ow014": "https://chuko-awamori.com/",
  "ow015": "https://www.seifuku.co.jp/",
  "ow017": "https://www.chinsuko.co.jp/",
  "ow018": "https://www.nuchima-su.co.jp/",

  // === 化粧品（data_cosmetics.js 由来）===
  "cos_tk01": "https://www.kohgendo.com/",
  "cos_tk02": "https://www.threecosmetics.com/",
  "cos_tk03": "https://www.acseine.co.jp/",
  "cos_tk04": "https://www.ampleur.jp/",
  "cos_tk05": "https://www.hacci1912.com/",
  "cos_tk06": "https://whomee.jp/",
  "cos_tk07": "https://naturaglace.jp/",
  "cos_tk08": "https://uka.co.jp/",
  "cos_tk09": "https://n-organic.com/",
  "cos_tk11": "https://celvoke.com/",
  "cos_tk12": "https://www.mediplus.co.jp/",
  "cos_tk13": "https://www.tunemakers.net/",
  "cos_tk16": "https://www.nihon-zettoc.co.jp/",
  "cos_tk17": "https://www.do-organic.com/",
  "cos_tk18": "https://www.proudmen.jp/",
  "cos_tk19": "https://www.addiction-beauty.com/",
  "cos_tk20": "https://www.isehanhonten.co.jp/",
  "cos_tk21": "https://www.ayura.co.jp/",
  "cos_os01": "https://etvos.com/",
  "cos_os03": "https://www.takeuchi-pharm.co.jp/",
  "cos_os04": "https://www.toyo-beauty.co.jp/",
  "cos_os07": "https://www.asuka-corp.co.jp/",
  "cos_kn01": "https://www.adjuvant.co.jp/",
  "cos_ym01": "https://www.arsoa.co.jp/",
};

// 起動時にCOMPANIESへURLをマージ
if (typeof COMPANIES !== "undefined") {
  COMPANIES.forEach((c) => {
    if (!c.url && KNOWN_URLS[c.i]) {
      c.url = KNOWN_URLS[c.i];
    }
  });
}

window.KNOWN_URLS = KNOWN_URLS;
