// 中部地方 (新潟〜愛知)
COMPANIES.push(
  // ========== 新潟 / NIIGATA（燕三条が中心） ==========
  {i:"ng001",ja:"玉川堂",en:"Gyokusendo",pref:"niigata",cat:"cutlery",desc_ja:"燕の鎚起銅器・200年の老舗",desc_en:"200-year tsuiki copperware atelier (Tsubame)",verified:true},
  {i:"ng002",ja:"諏訪田製作所",en:"Suwada Blacksmith Works",pref:"niigata",cat:"cutlery",desc_ja:"三条のニッパー・爪切り",desc_en:"Sanjo nippers & nail clippers",verified:true,deleted:true},
  {i:"ng003",ja:"藤次郎 (TOJIRO)",en:"Tojiro",pref:"niigata",cat:"cutlery",desc_ja:"燕三条の包丁メーカー",desc_en:"Tsubame-Sanjo kitchen knives",verified:true},
  {i:"ng004",ja:"タダフサ",en:"Tadafusa",pref:"niigata",cat:"cutlery",desc_ja:"三条の包丁メーカー",desc_en:"Sanjo knife maker",verified:true},
  {i:"ng005",ja:"山谷産業 (THE NIKKO)",en:"Yamatani Sangyo",pref:"niigata",cat:"cutlery",desc_ja:"三条の金物・キッチン用品",desc_en:"Sanjo hardware & kitchenware",deleted:true},
  {i:"ng006",ja:"スノーピーク",en:"Snow Peak",pref:"niigata",cat:"other",desc_ja:"三条のアウトドアギア",desc_en:"Sanjo outdoor gear",verified:true},
  {i:"ng007",ja:"マルナオ",en:"Marunao",pref:"niigata",cat:"wood",desc_ja:"三条の高級木製箸・道具",desc_en:"Sanjo premium wooden chopsticks",verified:true},
  {i:"ng008",ja:"庖丁工房タダフサ",en:"Tadafusa Houchou",pref:"niigata",cat:"cutlery",desc_ja:"三条の伝統包丁",desc_en:"Sanjo traditional knives",verified:true},
  {i:"ng009",ja:"佐藤金属興業 (SALUS)",en:"Sato Metal (SALUS)",pref:"niigata",cat:"cutlery",desc_ja:"燕の洋食器・キッチン雑貨",desc_en:"Tsubame flatware & kitchen tools"},
  {i:"ng010",ja:"山崎金属工業",en:"Yamazaki Metal (YAMACO)",pref:"niigata",cat:"cutlery",desc_ja:"燕の洋食器、ノーベル賞晩餐会採用",desc_en:"Tsubame flatware, used at Nobel banquet",verified:true,deleted:true},
  {i:"ng011",ja:"小林工業 (LUCKYWOOD)",en:"Kobayashi Kogyo",pref:"niigata",cat:"cutlery",desc_ja:"燕のカトラリー",desc_en:"Tsubame cutlery brand",deleted:true},
  {i:"ng012",ja:"和平フレイズ",en:"Wahei Freiz",pref:"niigata",cat:"cutlery",desc_ja:"燕三条の鍋・調理器具",desc_en:"Tsubame-Sanjo cookware",verified:true},
  {i:"ng013",ja:"オークス (OXO/CTC)",en:"Aux Co.",pref:"niigata",cat:"cutlery",desc_ja:"燕のキッチンツール開発",desc_en:"Tsubame kitchen tool dev",deleted:true},
  {i:"ng014",ja:"日野浦刃物工房",en:"Hinoura Hamono",pref:"niigata",cat:"cutlery",desc_ja:"三条の伝統鍛冶",desc_en:"Sanjo traditional blacksmith",verified:true},
  {i:"ng015",ja:"鎚起 中川政七商店連携",en:"Tsuiki Cooperative",pref:"niigata",cat:"cutlery",desc_ja:"燕の鎚起銅器共同工房",desc_en:"Tsubame tsuiki copper coop",deleted:true},
  {i:"ng016",ja:"久保田酒造 (久保田)",en:"Asahi Shuzo (Kubota)",pref:"niigata",cat:"sake",desc_ja:"朝日酒造・久保田ブランド",desc_en:"Brewer of Kubota sake",verified:true},
  {i:"ng017",ja:"八海醸造",en:"Hakkaisan",pref:"niigata",cat:"sake",desc_ja:"南魚沼の八海山蔵元",desc_en:"Minamiuonuma brewer of Hakkaisan",verified:true},
  {i:"ng018",ja:"白瀧酒造",en:"Shirataki",pref:"niigata",cat:"sake",desc_ja:"湯沢の上善如水蔵元",desc_en:"Yuzawa brewer of Jozen Mizunogotoshi",verified:true},
  {i:"ng019",ja:"宮尾酒造",en:"Miyao Brewery (Shimeharitsuru)",pref:"niigata",cat:"sake",desc_ja:"村上のしめ張り鶴",desc_en:"Murakami brewer of Shimeharitsuru",verified:true},
  {i:"ng020",ja:"今代司酒造",en:"Imayotsukasa",pref:"niigata",cat:"sake",desc_ja:"新潟市の老舗酒蔵",desc_en:"Niigata City heritage brewer",verified:true},
  {i:"ng021",ja:"高千代酒造",en:"Takachiyo",pref:"niigata",cat:"sake",desc_ja:"南魚沼の地酒蔵",desc_en:"Minamiuonuma local brewer",verified:true},
  {i:"ng022",ja:"魚沼醸造株式会社",en:"Uonuma Brewery",pref:"niigata",cat:"sake",desc_ja:"魚沼の地酒",desc_en:"Uonuma local sake"},
  {i:"ng023",ja:"小林製麺",en:"Kobayashi Seimen",pref:"niigata",cat:"food",desc_ja:"新潟の手延べ干麺",desc_en:"Niigata hand-stretched dry noodles",deleted:true},
  {i:"ng024",ja:"亀田製菓系列ベーカリー",en:"Kameda Bakery Group",pref:"niigata",cat:"food",desc_ja:"新潟の米菓加工",desc_en:"Niigata rice cracker processor",deleted:true},
  {i:"ng025",ja:"越後杜氏 米菓",en:"Echigo Toji Beika",pref:"niigata",cat:"food",desc_ja:"新潟米の米菓",desc_en:"Niigata rice cracker SME",deleted:true},
  {i:"ng026",ja:"小千谷織物同業協同組合",en:"Ojiya Chijimi",pref:"niigata",cat:"apparel",desc_ja:"小千谷縮の伝統織物",desc_en:"Ojiya chijimi crepe weaving"},
  {i:"ng027",ja:"塩沢織 中島屋",en:"Nakajimaya Shiozawa",pref:"niigata",cat:"apparel",desc_ja:"塩沢紬の織元",desc_en:"Shiozawa tsumugi weaver",deleted:true},
  {i:"ng028",ja:"村上堆朱",en:"Murakami Tsuishu",pref:"niigata",cat:"craft",desc_ja:"村上堆朱漆器",desc_en:"Murakami tsuishu lacquer"},
  {i:"ng029",ja:"加茂桐箪笥",en:"Kamo Paulownia Chest",pref:"niigata",cat:"wood",desc_ja:"加茂の桐箪笥",desc_en:"Kamo paulownia chest"},
  {i:"ng030",ja:"佐渡無名異焼",en:"Sado Mumyoi-yaki",pref:"niigata",cat:"glass",desc_ja:"佐渡の無名異焼陶器",desc_en:"Sado mumyoi pottery",deleted:true},
  {i:"ng031",ja:"亀田縞織物",en:"Kameda Jima",pref:"niigata",cat:"apparel",desc_ja:"亀田縞の伝統織物",desc_en:"Kameda striped textile"},
  {i:"ng032",ja:"新潟漆器",en:"Niigata Shikki",pref:"niigata",cat:"craft",desc_ja:"新潟の漆器メーカー",desc_en:"Niigata lacquerware"},
  {i:"ng033",ja:"金属研磨 磨き屋シンジケート",en:"Migakiya Syndicate",pref:"niigata",cat:"cutlery",desc_ja:"燕の金属研磨職人集団",desc_en:"Tsubame metal polishing guild",verified:true},
  {i:"ng034",ja:"フジマック新潟",en:"Fujimak Niigata",pref:"niigata",cat:"other",desc_ja:"業務用調理機器",desc_en:"Commercial kitchen equipment",deleted:true},
  {i:"ng035",ja:"村上木彫堆朱 池野美術工房",en:"Ikeno Tsuishu",pref:"niigata",cat:"craft",desc_ja:"村上の堆朱工房",desc_en:"Murakami tsuishu atelier",deleted:true},
  {i:"ng036",ja:"新潟電子精密工業",en:"Niigata Electron Precision",pref:"niigata",cat:"electronics",desc_ja:"新潟の電子部品",desc_en:"Niigata electronic parts",deleted:true},
  {i:"ng037",ja:"長岡花火工業",en:"Nagaoka Hanabi",pref:"niigata",cat:"other",desc_ja:"長岡の花火製造",desc_en:"Nagaoka fireworks maker",deleted:true},
  {i:"ng038",ja:"カミテ精工",en:"Kamite Seiko",pref:"niigata",cat:"electronics",desc_ja:"燕三条の精密板金",desc_en:"Tsubame-Sanjo precision sheet metal",verified:true},
  {i:"ng039",ja:"新潟化粧品研究所",en:"Niigata Cosmetics Lab",pref:"niigata",cat:"cosmetics",desc_ja:"米由来コスメOEM",desc_en:"Rice-based cosmetics OEM",deleted:true},
  {i:"ng040",ja:"魚沼サプリ工場",en:"Uonuma Supplement",pref:"niigata",cat:"supplement",desc_ja:"魚沼の機能性食品",desc_en:"Uonuma functional food",deleted:true},
  {i:"ng041",ja:"佐渡乳業",en:"Sado Dairy",pref:"niigata",cat:"food",desc_ja:"佐渡の乳製品",desc_en:"Sado dairy products",verified:true},
  {i:"ng042",ja:"新潟麦酒 (NIIGATA BEER)",en:"Niigata Beer",pref:"niigata",cat:"sake",desc_ja:"新潟のクラフトビール",desc_en:"Niigata craft beer"},
  {i:"ng043",ja:"スワダ刃物",en:"Suwada Blade Co.",pref:"niigata",cat:"cutlery",desc_ja:"三条の精密刃物",desc_en:"Sanjo precision blades"},
  {i:"ng044",ja:"津南醸造",en:"Tsunan Brewery",pref:"niigata",cat:"sake",desc_ja:"津南の地酒蔵",desc_en:"Tsunan local sake brewer",verified:true},
  {i:"ng045",ja:"市島酒造",en:"Ichishima Brewery",pref:"niigata",cat:"sake",desc_ja:"新発田の老舗酒蔵",desc_en:"Shibata heritage sake brewer",verified:true},
  {i:"ng046",ja:"北前そば高田屋",en:"Takadaya Hegisoba",pref:"niigata",cat:"food",desc_ja:"魚沼のへぎそば",desc_en:"Uonuma heg-isoba",deleted:true},
  {i:"ng047",ja:"越後製菓",en:"Echigo Seika",pref:"niigata",cat:"food",desc_ja:"長岡の餅・米菓",desc_en:"Nagaoka mochi & rice crackers",verified:true},
  {i:"ng048",ja:"佐渡金箔工房",en:"Sado Gold Leaf",pref:"niigata",cat:"craft",desc_ja:"佐渡の金箔工芸",desc_en:"Sado gold leaf craft",deleted:true},
  {i:"ng049",ja:"新潟漆器組合",en:"Niigata Lacquer Coop",pref:"niigata",cat:"craft",desc_ja:"県内漆器組合",desc_en:"Niigata lacquer cooperative"},
  {i:"ng050",ja:"燕三条ファクトリーズ",en:"Tsubame-Sanjo Factories",pref:"niigata",cat:"cutlery",desc_ja:"燕三条の試作・OEM",desc_en:"Tsubame-Sanjo OEM/prototyping",deleted:true},

  // ========== 富山 / TOYAMA ==========
  {i:"ty001",ja:"高岡銅器 老子製作所",en:"Oigo Seisakusho",pref:"toyama",cat:"craft",desc_ja:"高岡銅器の梵鐘・鋳物",desc_en:"Takaoka bronze bell foundry",verified:true},
  {i:"ty002",ja:"能作 (高岡銅器)",en:"Nousaku",pref:"toyama",cat:"craft",desc_ja:"高岡の錫器・銅器",desc_en:"Takaoka tin & copper ware",verified:true},
  {i:"ty003",ja:"四津川製作所",en:"Yotsugawa Seisakusho",pref:"toyama",cat:"craft",desc_ja:"高岡銅器の老舗",desc_en:"Heritage Takaoka bronze",verified:true},
  {i:"ty004",ja:"モメンタムファクトリー Orii",en:"Momentum Factory Orii",pref:"toyama",cat:"craft",desc_ja:"高岡の銅着色加工",desc_en:"Takaoka copper coloring",verified:true},
  {i:"ty005",ja:"シマタニ昇龍工房",en:"Shimatani Syouryu",pref:"toyama",cat:"craft",desc_ja:"高岡の鈴・おりん",desc_en:"Takaoka singing bowls & orin",verified:true},
  {i:"ty006",ja:"廣貫堂",en:"Kokando",pref:"toyama",cat:"supplement",desc_ja:"富山の置き薬・配置薬の老舗",desc_en:"Heritage Toyama traveling medicine",verified:true},
  {i:"ty007",ja:"池田屋安兵衛商店",en:"Ikedaya Yasubei",pref:"toyama",cat:"supplement",desc_ja:"富山の伝統和漢薬",desc_en:"Toyama traditional Kampo medicine",verified:true},
  {i:"ty008",ja:"立山堂製薬",en:"Tateyamado Yakuhin",pref:"toyama",cat:"supplement",desc_ja:"富山配置薬",desc_en:"Toyama placement medicine",deleted:true},
  {i:"ty009",ja:"立山酒造",en:"Tateyama Brewery",pref:"toyama",cat:"sake",desc_ja:"立山ブランドの蔵元",desc_en:"Brewer of Tateyama sake",verified:true},
  {i:"ty010",ja:"桝田酒造店",en:"Masuda Brewery (Masuizumi)",pref:"toyama",cat:"sake",desc_ja:"富山市の満寿泉蔵元",desc_en:"Toyama brewer of Masuizumi",verified:true},
  {i:"ty011",ja:"勝駒酒造",en:"Shoukoma",pref:"toyama",cat:"sake",desc_ja:"高岡の小規模蔵元",desc_en:"Takaoka small brewery",verified:true},
  {i:"ty012",ja:"皇国晴酒造 (幻の瀧)",en:"Mikuni-bare Brewery",pref:"toyama",cat:"sake",desc_ja:"黒部の名水蔵元",desc_en:"Kurobe spring-water brewery",verified:true},
  {i:"ty013",ja:"昆布の四十物昆布",en:"Aimono Konbu",pref:"toyama",cat:"food",desc_ja:"富山の昆布加工老舗",desc_en:"Toyama kelp processor",verified:true},
  {i:"ty014",ja:"梅かま",en:"Umekama",pref:"toyama",cat:"food",desc_ja:"富山の細工蒲鉾",desc_en:"Toyama decorative kamaboko",verified:true},
  {i:"ty015",ja:"鱒寿司 源",en:"Minamoto Masuzushi",pref:"toyama",cat:"food",desc_ja:"富山の鱒寿司老舗",desc_en:"Heritage Toyama masuzushi",verified:true},
  {i:"ty016",ja:"井波彫刻",en:"Inami Wood Carving",pref:"toyama",cat:"wood",desc_ja:"井波の伝統木彫",desc_en:"Inami traditional wood carving",verified:true},
  {i:"ty017",ja:"庄川挽物木地",en:"Shogawa Hikimono",pref:"toyama",cat:"wood",desc_ja:"庄川の挽物・木工",desc_en:"Shogawa lathed woodwork"},
  {i:"ty018",ja:"五箇山和紙",en:"Gokayama Washi",pref:"toyama",cat:"paper",desc_ja:"五箇山の手すき和紙",desc_en:"Gokayama handmade washi",verified:true},
  {i:"ty019",ja:"高岡漆器 山口",en:"Yamaguchi Takaoka Shikki",pref:"toyama",cat:"craft",desc_ja:"高岡漆器の老舗",desc_en:"Heritage Takaoka lacquer",deleted:true},
  {i:"ty020",ja:"富山ガラス工房",en:"Toyama Glass Studio",pref:"toyama",cat:"glass",desc_ja:"富山のアートグラス",desc_en:"Toyama art glass studio",verified:true},

  // ========== 石川 / ISHIKAWA ==========
  {i:"is001",ja:"箔一",en:"Hakuichi",pref:"ishikawa",cat:"craft",desc_ja:"金沢金箔の最大手中小",desc_en:"Major Kanazawa gold leaf SME",verified:true},
  {i:"is002",ja:"今井金箔",en:"Imai Kinpaku",pref:"ishikawa",cat:"craft",desc_ja:"金沢金箔の老舗",desc_en:"Heritage Kanazawa gold leaf",verified:true},
  {i:"is003",ja:"福久屋石黒傳六商店",en:"Ishiguro Denroku",pref:"ishikawa",cat:"craft",desc_ja:"金沢の伝統金箔",desc_en:"Heritage Kanazawa gold leaf",deleted:true},
  {i:"is004",ja:"九谷焼 鏑木商舗",en:"Kaburaki Kutani",pref:"ishikawa",cat:"glass",desc_ja:"金沢の九谷焼老舗",desc_en:"Kanazawa heritage Kutani-yaki",verified:true},
  {i:"is005",ja:"九谷青窯",en:"Kutani Seiyo",pref:"ishikawa",cat:"glass",desc_ja:"能美の九谷焼窯元",desc_en:"Nomi Kutani-yaki kiln",verified:true},
  {i:"is006",ja:"上出長右衛門窯",en:"Kamide Choemon Kiln",pref:"ishikawa",cat:"glass",desc_ja:"能美の九谷焼名窯",desc_en:"Famous Nomi Kutani kiln",verified:true},
  {i:"is007",ja:"金沢箔工芸 銀座箔座",en:"Hakuza Kanazawa",pref:"ishikawa",cat:"craft",desc_ja:"金沢金箔ライフスタイル",desc_en:"Kanazawa gold-leaf lifestyle",verified:true},
  {i:"is008",ja:"輪島キリモト",en:"Wajima Kirimoto",pref:"ishikawa",cat:"craft",desc_ja:"輪島塗の現代工房",desc_en:"Modern Wajima lacquer atelier",verified:true},
  {i:"is009",ja:"輪島塗 桐本",en:"Kirimoto Wajima",pref:"ishikawa",cat:"craft",desc_ja:"輪島塗の伝統工房",desc_en:"Traditional Wajima lacquer"},
  {i:"is010",ja:"輪島塗 田谷漆器店",en:"Taya Wajima Lacquer",pref:"ishikawa",cat:"craft",desc_ja:"輪島塗の老舗",desc_en:"Heritage Wajima lacquer",verified:true},
  {i:"is011",ja:"加賀友禅 毎田染画工芸",en:"Maida Senga Kaga Yuzen",pref:"ishikawa",cat:"apparel",desc_ja:"加賀友禅の伝統工房",desc_en:"Kaga yuzen dye atelier"},
  {i:"is012",ja:"加賀繍 桜井",en:"Sakurai Kaga Embroidery",pref:"ishikawa",cat:"apparel",desc_ja:"加賀繍の伝統刺繍",desc_en:"Kaga traditional embroidery",deleted:true},
  {i:"is013",ja:"山中漆器 木下漆芸",en:"Kinoshita Yamanaka Lacquer",pref:"ishikawa",cat:"craft",desc_ja:"山中塗の伝統工房",desc_en:"Yamanaka lacquer atelier",deleted:true},
  {i:"is014",ja:"福光屋",en:"Fukumitsuya",pref:"ishikawa",cat:"sake",desc_ja:"金沢の純米酒蔵",desc_en:"Kanazawa all-junmai sake brewer",verified:true},
  {i:"is015",ja:"農口尚彦研究所",en:"Noguchi Naohiko Sake Inst.",pref:"ishikawa",cat:"sake",desc_ja:"能登の名杜氏が率いる蔵",desc_en:"Brewery led by master toji Noguchi",verified:true},
  {i:"is016",ja:"宗玄酒造",en:"Sogen Brewery",pref:"ishikawa",cat:"sake",desc_ja:"珠洲の老舗酒蔵",desc_en:"Suzu heritage sake brewer",verified:true},
  {i:"is017",ja:"加賀鳶 (福光屋)",en:"Kagatobi",pref:"ishikawa",cat:"sake",desc_ja:"金沢の純米酒ブランド",desc_en:"Kanazawa premium junmai brand"},
  {i:"is018",ja:"日本海ガス炭素",en:"Nihonkai Carbon",pref:"ishikawa",cat:"other",desc_ja:"金沢の素材産業",desc_en:"Kanazawa materials industry",deleted:true},
  {i:"is019",ja:"金沢茶屋街 中田屋",en:"Nakataya Kintsuba",pref:"ishikawa",cat:"food",desc_ja:"金沢のきんつば老舗",desc_en:"Heritage Kanazawa kintsuba",verified:true},
  {i:"is020",ja:"加賀棒茶 丸八製茶場",en:"Maruhachi Seichaba",pref:"ishikawa",cat:"tea",desc_ja:"加賀棒茶の老舗",desc_en:"Heritage Kaga bocha (twig tea)",verified:true},
  {i:"is021",ja:"小堀酒造店",en:"Kobori Brewery",pref:"ishikawa",cat:"sake",desc_ja:"白山の老舗酒蔵",desc_en:"Hakusan heritage brewer",verified:true},
  {i:"is022",ja:"金沢箔押し 安江",en:"Yasue Kinpaku",pref:"ishikawa",cat:"craft",desc_ja:"金沢の箔押し工房",desc_en:"Kanazawa foil-pressing atelier",deleted:true},
  {i:"is023",ja:"のとろ豆腐工房",en:"Notoro Tofu Atelier",pref:"ishikawa",cat:"food",desc_ja:"能登の伝統豆腐",desc_en:"Noto traditional tofu",deleted:true},
  {i:"is024",ja:"能登塩工房",en:"Noto Salt Atelier",pref:"ishikawa",cat:"food",desc_ja:"能登の揚浜式塩田",desc_en:"Noto agehama-style salt"},
  {i:"is025",ja:"九谷焼 錦山窯",en:"Kinzan Kutani Kiln",pref:"ishikawa",cat:"glass",desc_ja:"九谷焼の伝統窯元",desc_en:"Heritage Kutani kiln"},

  // ========== 福井 / FUKUI ==========
  {i:"fi001",ja:"鯖江メガネ工房 田中眼鏡",en:"Tanaka Megane Sabae",pref:"fukui",cat:"other",desc_ja:"鯖江の眼鏡フレーム",desc_en:"Sabae eyewear frame maker"},
  {i:"fi002",ja:"金子眼鏡 鯖江",en:"Kaneko Megane Sabae",pref:"fukui",cat:"other",desc_ja:"鯖江の高級眼鏡",desc_en:"Sabae premium eyewear",verified:true},
  {i:"fi003",ja:"BJクラシック (鯖江)",en:"BJ Classic Sabae",pref:"fukui",cat:"other",desc_ja:"鯖江の手作り眼鏡",desc_en:"Sabae handmade eyewear",verified:true},
  {i:"fi004",ja:"ボストンクラブ",en:"Boston Club",pref:"fukui",cat:"other",desc_ja:"鯖江の眼鏡デザイン",desc_en:"Sabae eyewear design",verified:true},
  {i:"fi005",ja:"白山眼鏡店 (鯖江)",en:"Hakusan Megane",pref:"fukui",cat:"other",desc_ja:"鯖江の老舗眼鏡",desc_en:"Heritage Sabae eyewear",verified:true},
  {i:"fi006",ja:"フォーナインズ (鯖江)",en:"999.9 Four Nines",pref:"fukui",cat:"other",desc_ja:"鯖江の高機能眼鏡",desc_en:"Sabae high-function eyewear",verified:true},
  {i:"fi007",ja:"越前漆器 漆琳堂",en:"Shitsurindo Echizen Lacquer",pref:"fukui",cat:"craft",desc_ja:"越前漆器の老舗",desc_en:"Heritage Echizen lacquer",verified:true},
  {i:"fi008",ja:"越前漆器 関坂漆器",en:"Sekisaka Lacquer",pref:"fukui",cat:"craft",desc_ja:"越前漆器の老舗",desc_en:"Heritage Echizen lacquer"},
  {i:"fi009",ja:"越前打刃物 龍泉刃物",en:"Ryusen Hamono",pref:"fukui",cat:"cutlery",desc_ja:"越前打刃物の高級包丁",desc_en:"Echizen forged premium knives",verified:true},
  {i:"fi010",ja:"高村刃物製作所",en:"Takamura Hamono",pref:"fukui",cat:"cutlery",desc_ja:"越前打刃物の名工",desc_en:"Echizen master bladesmith",verified:true},
  {i:"fi011",ja:"越前和紙 岩野市兵衛",en:"Iwano Ichibei Washi",pref:"fukui",cat:"paper",desc_ja:"越前和紙の人間国宝",desc_en:"Echizen washi Living National Treasure",verified:true},
  {i:"fi012",ja:"杉原商店 (越前和紙)",en:"Sugihara Shoten Washi",pref:"fukui",cat:"paper",desc_ja:"越前和紙の老舗",desc_en:"Heritage Echizen washi",verified:true},
  {i:"fi013",ja:"福井うちわ 日本海団扇",en:"Nihonkai Uchiwa",pref:"fukui",cat:"craft",desc_ja:"福井うちわの製造",desc_en:"Fukui uchiwa fan maker",deleted:true},
  {i:"fi014",ja:"南部酒造場",en:"Nanbu Sake Brewery",pref:"fukui",cat:"sake",desc_ja:"花垣の蔵元",desc_en:"Brewer of Hanagaki",verified:true},
  {i:"fi015",ja:"黒龍酒造",en:"Kokuryu Brewery",pref:"fukui",cat:"sake",desc_ja:"福井の高級銘酒",desc_en:"Fukui premium sake brewer",verified:true},
  {i:"fi016",ja:"加藤吉平商店 (梵)",en:"Born Brewery (Kato Kichibei)",pref:"fukui",cat:"sake",desc_ja:"鯖江の梵ブランド",desc_en:"Sabae brewer of BORN sake",verified:true},
  {i:"fi017",ja:"福井羽二重",en:"Fukui Habutae",pref:"fukui",cat:"apparel",desc_ja:"福井絹織物の中小",desc_en:"Fukui silk weaving SME",deleted:true},
  {i:"fi018",ja:"小浜塗箸 マツ勘",en:"Matsukan Wakasa Hashi",pref:"fukui",cat:"wood",desc_ja:"若狭塗箸の老舗",desc_en:"Heritage Wakasa lacquer chopsticks",verified:true},
  {i:"fi019",ja:"小浜伝統箸 兵左衛門",en:"Hyozaemon",pref:"fukui",cat:"wood",desc_ja:"若狭の塗箸メーカー",desc_en:"Wakasa chopstick maker",verified:true},
  {i:"fi020",ja:"福井繊維工業",en:"Fukui Textile Industry",pref:"fukui",cat:"apparel",desc_ja:"福井の合繊織物",desc_en:"Fukui synthetic textile",deleted:true},
  {i:"fi021",ja:"敦賀刃物匠の館",en:"Tsuruga Cutlery Atelier",pref:"fukui",cat:"cutlery",desc_ja:"敦賀の伝統刃物",desc_en:"Tsuruga traditional cutlery",deleted:true},
  {i:"fi022",ja:"福井若狭しお屋",en:"Wakasa Salt House",pref:"fukui",cat:"food",desc_ja:"若狭の塩・海産",desc_en:"Wakasa salt & seafood",deleted:true},
  {i:"fi023",ja:"鯖江ファッショングラス",en:"Sabae Fashion Glass",pref:"fukui",cat:"other",desc_ja:"鯖江の眼鏡OEM",desc_en:"Sabae eyewear OEM",deleted:true},
  {i:"fi024",ja:"越前ガニ加工協組",en:"Echizen Crab Coop",pref:"fukui",cat:"food",desc_ja:"越前ガニの加工",desc_en:"Echizen crab processor",deleted:true},
  {i:"fi025",ja:"福井サプリ研究所",en:"Fukui Supplement Lab",pref:"fukui",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},

  // ========== 山梨 / YAMANASHI ==========
  {i:"ym001",ja:"甲府ジュエリー協同組合",en:"Kofu Jewelry Coop",pref:"yamanashi",cat:"craft",desc_ja:"甲府ジュエリーの製造拠点",desc_en:"Kofu jewelry production hub"},
  {i:"ym002",ja:"ミキモト甲府 (中小宝飾)",en:"Kofu Jewelry Atelier",pref:"yamanashi",cat:"craft",desc_ja:"甲府の宝飾職人工房",desc_en:"Kofu jewelry artisans",deleted:true},
  {i:"ym003",ja:"山梨水晶 上原",en:"Uehara Yamanashi Suisho",pref:"yamanashi",cat:"craft",desc_ja:"水晶研磨の伝統工芸",desc_en:"Crystal polishing tradition",deleted:true},
  {i:"ym004",ja:"勝沼醸造",en:"Katsunuma Brewery",pref:"yamanashi",cat:"sake",desc_ja:"甲州ワインの中堅",desc_en:"Koshu wine producer",verified:true},
  {i:"ym005",ja:"中央葡萄酒 (グレイス)",en:"Grace Wine",pref:"yamanashi",cat:"sake",desc_ja:"勝沼の高級ワイナリー",desc_en:"Katsunuma premium winery",verified:true},
  {i:"ym006",ja:"ルミエール (山梨ワイン)",en:"Lumiere Winery",pref:"yamanashi",cat:"sake",desc_ja:"勝沼の老舗ワイナリー",desc_en:"Heritage Katsunuma winery",verified:true},
  {i:"ym007",ja:"丸藤葡萄酒工業 (ルバイヤート)",en:"Rubaiyat Marufuji",pref:"yamanashi",cat:"sake",desc_ja:"勝沼の伝統ワイナリー",desc_en:"Heritage Katsunuma winery",verified:true},
  {i:"ym008",ja:"山梨銘醸 (七賢)",en:"Shichiken Brewery",pref:"yamanashi",cat:"sake",desc_ja:"白州の老舗酒蔵",desc_en:"Hakushu heritage sake brewer",verified:true},
  {i:"ym009",ja:"武の井酒造",en:"Takenoi Brewery",pref:"yamanashi",cat:"sake",desc_ja:"北杜の地酒蔵",desc_en:"Hokuto local sake brewer",verified:true},
  {i:"ym010",ja:"桔梗屋 (信玄餅)",en:"Kikyoya Shingen Mochi",pref:"yamanashi",cat:"food",desc_ja:"信玄餅の老舗",desc_en:"Heritage Shingen mochi maker",verified:true},
  {i:"ym011",ja:"金精軒 信玄餅",en:"Kinseiken Shingen Mochi",pref:"yamanashi",cat:"food",desc_ja:"白州の信玄餅老舗",desc_en:"Hakushu heritage Shingen mochi",verified:true},
  {i:"ym012",ja:"小作 (ほうとう)",en:"Kosaku Houtou",pref:"yamanashi",cat:"food",desc_ja:"山梨ほうとうの老舗",desc_en:"Heritage Yamanashi houtou"},
  {i:"ym013",ja:"郡内織物協同組合",en:"Gunnai Textile Coop",pref:"yamanashi",cat:"apparel",desc_ja:"富士吉田の郡内織",desc_en:"Fujiyoshida gunnai weaving"},
  {i:"ym014",ja:"テンジン (富士吉田織物)",en:"Tenjin Fujiyoshida",pref:"yamanashi",cat:"apparel",desc_ja:"富士吉田の高密度織物",desc_en:"Fujiyoshida high-density textile"},
  {i:"ym015",ja:"山梨ジュエリー宝石研磨",en:"Yamanashi Gem Polishing",pref:"yamanashi",cat:"craft",desc_ja:"水晶研磨のOEM",desc_en:"Crystal polishing OEM",deleted:true},
  {i:"ym016",ja:"山梨ハーブ研究所",en:"Yamanashi Herb Lab",pref:"yamanashi",cat:"cosmetics",desc_ja:"富士の伏流水コスメ",desc_en:"Mt. Fuji spring-water cosmetics",deleted:true},
  {i:"ym017",ja:"山梨果樹園加工",en:"Yamanashi Fruit Processing",pref:"yamanashi",cat:"food",desc_ja:"桃・葡萄の加工メーカー",desc_en:"Peach & grape processor",deleted:true},
  {i:"ym018",ja:"富士山サプリ工房",en:"Fuji Supplement Atelier",pref:"yamanashi",cat:"supplement",desc_ja:"富士の植物サプリ",desc_en:"Fuji botanical supplements",deleted:true},

  // ========== 長野 / NAGANO ==========
  {i:"nn001",ja:"信州味噌 マルコメ系列OEM",en:"Shinshu Miso OEM",pref:"nagano",cat:"food",desc_ja:"信州味噌のOEMメーカー",desc_en:"Shinshu miso OEM",deleted:true},
  {i:"nn002",ja:"丸高蔵 (諏訪味噌)",en:"Marutaka Suwa Miso",pref:"nagano",cat:"food",desc_ja:"諏訪の老舗味噌蔵",desc_en:"Suwa heritage miso brewer",verified:true},
  {i:"nn003",ja:"伊藤園 長野工場ティーパック",en:"Itoen Nagano Tea Bagging",pref:"nagano",cat:"tea",desc_ja:"長野のお茶バッグ加工",desc_en:"Nagano tea bag packaging",deleted:true},
  {i:"nn004",ja:"信州蕎麦 おびなた",en:"Obinata Shinshu Soba",pref:"nagano",cat:"food",desc_ja:"信州そば老舗",desc_en:"Heritage Shinshu soba maker",verified:true},
  {i:"nn005",ja:"渡辺製麺 信州そば",en:"Watanabe Seimen",pref:"nagano",cat:"food",desc_ja:"信州そばの製麺",desc_en:"Shinshu soba noodle maker"},
  {i:"nn006",ja:"信州ハム",en:"Shinshu Ham",pref:"nagano",cat:"food",desc_ja:"信州の老舗ハム",desc_en:"Heritage Shinshu ham",verified:true},
  {i:"nn007",ja:"白馬錦 薄井商店",en:"Usui Shoten (Hakubanishiki)",pref:"nagano",cat:"sake",desc_ja:"白馬の地酒蔵",desc_en:"Hakuba local sake brewer",verified:true},
  {i:"nn008",ja:"宮坂醸造 (真澄)",en:"Miyasaka (Masumi)",pref:"nagano",cat:"sake",desc_ja:"諏訪の七号酵母発祥蔵",desc_en:"Suwa, origin of No.7 yeast",verified:true},
  {i:"nn009",ja:"舞姫酒造",en:"Maihime Brewery",pref:"nagano",cat:"sake",desc_ja:"諏訪の地酒蔵",desc_en:"Suwa local sake brewer",verified:true},
  {i:"nn010",ja:"小布施ワイナリー",en:"Obuse Winery",pref:"nagano",cat:"sake",desc_ja:"小布施のワイン蔵",desc_en:"Obuse winery",verified:true},
  {i:"nn011",ja:"小布施堂 (栗菓子)",en:"Obusedo",pref:"nagano",cat:"food",desc_ja:"小布施の栗菓子老舗",desc_en:"Heritage Obuse chestnut sweets",verified:true},
  {i:"nn012",ja:"竹風堂 (栗菓子)",en:"Chikufudo",pref:"nagano",cat:"food",desc_ja:"小布施の栗菓子",desc_en:"Obuse chestnut sweets",verified:true},
  {i:"nn013",ja:"松本民芸家具",en:"Matsumoto Mingei Furniture",pref:"nagano",cat:"wood",desc_ja:"松本の民芸家具",desc_en:"Matsumoto folk-craft furniture",verified:true},
  {i:"nn014",ja:"飯山仏壇",en:"Iiyama Butsudan",pref:"nagano",cat:"craft",desc_ja:"飯山の伝統仏壇",desc_en:"Iiyama traditional altars"},
  {i:"nn015",ja:"内山紙協同組合",en:"Uchiyama Washi Coop",pref:"nagano",cat:"paper",desc_ja:"内山和紙の伝統",desc_en:"Uchiyama washi tradition"},
  {i:"nn016",ja:"松本ガラス工房",en:"Matsumoto Glass Studio",pref:"nagano",cat:"glass",desc_ja:"松本のガラス工芸",desc_en:"Matsumoto glasswork studio",deleted:true},
  {i:"nn017",ja:"信州精密電子",en:"Shinshu Precision Electronics",pref:"nagano",cat:"electronics",desc_ja:"諏訪の精密電子",desc_en:"Suwa precision electronics",deleted:true},
  {i:"nn018",ja:"諏訪精工メカトロ",en:"Suwa Mechatronics SME",pref:"nagano",cat:"electronics",desc_ja:"諏訪の試作・精密加工",desc_en:"Suwa prototyping & precision",deleted:true},
  {i:"nn019",ja:"OSG信州 (特殊工具)",en:"Shinshu Tool Lab",pref:"nagano",cat:"patent",desc_ja:"特殊工具の試作開発",desc_en:"Custom tool prototyping",deleted:true},
  {i:"nn020",ja:"信州健康食品工房",en:"Shinshu Health Food Atelier",pref:"nagano",cat:"supplement",desc_ja:"信州の機能性食品",desc_en:"Shinshu functional food",deleted:true},

  // ========== 岐阜 / GIFU ==========
  {i:"gf001",ja:"美濃焼 玉山窯",en:"Tamayama Kiln Mino",pref:"gifu",cat:"glass",desc_ja:"美濃焼の老舗窯元",desc_en:"Heritage Mino-yaki kiln"},
  {i:"gf002",ja:"美濃焼 SAKUZAN",en:"Sakuzan Mino",pref:"gifu",cat:"glass",desc_ja:"美濃焼の現代陶器",desc_en:"Modern Mino pottery",verified:true},
  {i:"gf003",ja:"美濃焼 BARBAR (馬場商店)",en:"BARBAR Baba Shoten",pref:"gifu",cat:"glass",desc_ja:"美濃焼の現代ブランド",desc_en:"Modern Mino-yaki brand",verified:true},
  {i:"gf004",ja:"丸朝製陶所",en:"Marutomo Pottery",pref:"gifu",cat:"glass",desc_ja:"美濃焼の窯元",desc_en:"Mino-yaki kiln"},
  {i:"gf005",ja:"美濃焼 山志製陶所",en:"Yamashi Mino Pottery",pref:"gifu",cat:"glass",desc_ja:"美濃焼の中堅窯元",desc_en:"Mid-size Mino kiln"},
  {i:"gf006",ja:"三星刃物株式会社",en:"Mitsuboshi Cutlery Seki",pref:"gifu",cat:"cutlery",desc_ja:"関の伝統刀工",desc_en:"Seki traditional sword smithing"},
  {i:"gf007",ja:"関市 関孫六 (貝印関連OEM)",en:"Seki Magoroku Cutlery",pref:"gifu",cat:"cutlery",desc_ja:"関の包丁伝統",desc_en:"Seki blade tradition",verified:true},
  {i:"gf008",ja:"濃州正宗刃物製作所",en:"Noshu Masamune Hamono",pref:"gifu",cat:"cutlery",desc_ja:"関の刃物老舗",desc_en:"Heritage Seki cutlery",deleted:true},
  {i:"gf009",ja:"スミカマ",en:"Sumikama Cutlery",pref:"gifu",cat:"cutlery",desc_ja:"関の包丁メーカー",desc_en:"Seki knife maker",verified:true},
  {i:"gf010",ja:"美濃和紙 古川紙工",en:"Kogawa Mino Washi",pref:"gifu",cat:"paper",desc_ja:"美濃和紙の老舗",desc_en:"Heritage Mino washi"},
  {i:"gf011",ja:"美濃和紙 家田紙工",en:"Ieda Mino Washi",pref:"gifu",cat:"paper",desc_ja:"美濃和紙のメーカー",desc_en:"Mino washi maker",verified:true},
  {i:"gf012",ja:"飛騨高山 飛騨春慶",en:"Hida Shunkei Lacquer",pref:"gifu",cat:"craft",desc_ja:"飛騨高山の春慶塗",desc_en:"Hida Takayama shunkei lacquer",deleted:true},
  {i:"gf013",ja:"渋草柳造窯",en:"Shibukusa Ryuzo Kiln",pref:"gifu",cat:"glass",desc_ja:"飛騨渋草焼の窯元",desc_en:"Hida Shibukusa kiln"},
  {i:"gf014",ja:"飛騨家具 オークヴィレッジ",en:"Oak Village Hida",pref:"gifu",cat:"wood",desc_ja:"飛騨の国産材家具",desc_en:"Hida domestic-wood furniture",verified:true},
  {i:"gf015",ja:"飛騨産業",en:"Hida Sangyo Furniture",pref:"gifu",cat:"wood",desc_ja:"飛騨家具の代表",desc_en:"Representative Hida furniture",verified:true},
  {i:"gf016",ja:"柏木工",en:"Kashiwa Mokko",pref:"gifu",cat:"wood",desc_ja:"飛騨家具の老舗",desc_en:"Heritage Hida furniture",verified:true},
  {i:"gf017",ja:"白扇酒造",en:"Hakusen Brewery",pref:"gifu",cat:"sake",desc_ja:"川辺町の本みりん蔵",desc_en:"Kawabe town hon-mirin brewer",verified:true},
  {i:"gf018",ja:"小坂酒造場",en:"Kosaka Brewery",pref:"gifu",cat:"sake",desc_ja:"美濃の地酒蔵",desc_en:"Mino local sake brewer",verified:true},
  {i:"gf019",ja:"渡辺酒造店 (蓬莱)",en:"Watanabe Brewery (Hourai)",pref:"gifu",cat:"sake",desc_ja:"飛騨古川の蔵元",desc_en:"Hida Furukawa sake brewer",verified:true},
  {i:"gf020",ja:"飛騨蕎麦 名水会",en:"Hida Soba Meisui",pref:"gifu",cat:"food",desc_ja:"飛騨そば製麺",desc_en:"Hida soba noodle maker",deleted:true},
  {i:"gf021",ja:"高山ラーメン老舗",en:"Takayama Ramen Heritage",pref:"gifu",cat:"food",desc_ja:"高山ラーメンの製麺",desc_en:"Takayama ramen noodle maker",deleted:true},
  {i:"gf022",ja:"岐阜提灯 オゼキ",en:"Ozeki Gifu Chochin",pref:"gifu",cat:"craft",desc_ja:"岐阜提灯の老舗",desc_en:"Heritage Gifu chochin lantern",verified:true},
  {i:"gf023",ja:"美濃和傘",en:"Mino Wagasa",pref:"gifu",cat:"craft",desc_ja:"美濃和傘の伝統工芸",desc_en:"Mino traditional umbrella",deleted:true},
  {i:"gf024",ja:"岐阜化粧品工業",en:"Gifu Cosmetics Industry",pref:"gifu",cat:"cosmetics",desc_ja:"岐阜の化粧品OEM",desc_en:"Gifu cosmetics OEM",deleted:true},
  {i:"gf025",ja:"飛騨ミート農業協同組合連合会",en:"Hida Beef Coop",pref:"gifu",cat:"food",desc_ja:"飛騨牛の加工",desc_en:"Hida beef processor"},

  // ========== 静岡 / SHIZUOKA ==========
  {i:"sz001",ja:"株式会社丸山園",en:"Maruyama-en Tea",pref:"shizuoka",cat:"tea",desc_ja:"静岡茶の老舗茶園",desc_en:"Heritage Shizuoka tea grower"},
  {i:"sz002",ja:"小柳津清一商店",en:"Oyaizu Seiichi",pref:"shizuoka",cat:"tea",desc_ja:"静岡茶老舗",desc_en:"Heritage Shizuoka tea"},
  {i:"sz003",ja:"あらたま園 (お茶)",en:"Aratama-en Tea",pref:"shizuoka",cat:"tea",desc_ja:"川根本町の高級茶園",desc_en:"Kawanehon-cho premium tea",deleted:true},
  {i:"sz004",ja:"丸子茶 抹茶林製茶",en:"Hayashi Seicha Mariko",pref:"shizuoka",cat:"tea",desc_ja:"丸子の抹茶老舗",desc_en:"Mariko heritage matcha",deleted:true},
  {i:"sz005",ja:"佐藤製茶 (御茶屋)",en:"Sato Seicha",pref:"shizuoka",cat:"tea",desc_ja:"静岡茶の製茶問屋",desc_en:"Shizuoka tea wholesaler"},
  {i:"sz006",ja:"葉ノ香園",en:"Hanoka-en Tea",pref:"shizuoka",cat:"tea",desc_ja:"川根茶の茶園",desc_en:"Kawane tea grower",deleted:true},
  {i:"sz007",ja:"丸七製茶 (ななや)",en:"Maruhichi Nanaya",pref:"shizuoka",cat:"tea",desc_ja:"藤枝の抹茶ジェラート",desc_en:"Fujieda matcha gelato",verified:true},
  {i:"sz008",ja:"中根製茶",en:"Nakane Seicha",pref:"shizuoka",cat:"tea",desc_ja:"掛川深蒸し茶老舗",desc_en:"Heritage Kakegawa fukamushi tea"},
  {i:"sz009",ja:"市川園",en:"Ichikawa-en Tea",pref:"shizuoka",cat:"tea",desc_ja:"静岡県内の茶園",desc_en:"Shizuoka tea grower"},
  {i:"sz010",ja:"葉桐 (茶問屋)",en:"Hagiri Tea",pref:"shizuoka",cat:"tea",desc_ja:"静岡茶の問屋老舗",desc_en:"Heritage Shizuoka tea wholesaler"},
  {i:"sz011",ja:"伊藤製茶",en:"Ito Seicha",pref:"shizuoka",cat:"tea",desc_ja:"静岡茶の中堅問屋",desc_en:"Mid-size Shizuoka tea house",deleted:true},
  {i:"sz012",ja:"葵プレミアム茶",en:"Aoi Premium Tea",pref:"shizuoka",cat:"tea",desc_ja:"静岡市の高級茶ブランド",desc_en:"Shizuoka City premium tea",deleted:true},
  {i:"sz013",ja:"株式会社杉養蜂園",en:"Sugi Bee Garden Shizuoka",pref:"kumamoto",cat:"food",desc_ja:"静岡の蜂蜜・健康食品",desc_en:"Shizuoka honey & health products"},
  {i:"sz014",ja:"うなぎパイ本舗 春華堂",en:"Shunkado Unagi Pie",pref:"shizuoka",cat:"food",desc_ja:"浜松のうなぎパイ老舗",desc_en:"Heritage Hamamatsu Unagi Pie",verified:true},
  {i:"sz015",ja:"治一郎 (バウムクーヘン)",en:"Jiichiro Baumkuchen",pref:"shizuoka",cat:"food",desc_ja:"浜松のバウムクーヘン",desc_en:"Hamamatsu baumkuchen",verified:true},
  {i:"sz016",ja:"安倍川餅 やまだいち",en:"Yamadaichi Abekawa Mochi",pref:"shizuoka",cat:"food",desc_ja:"静岡市の安倍川餅",desc_en:"Shizuoka City Abekawa mochi",verified:true},
  {i:"sz017",ja:"こっこ (米子屋)",en:"Yonekoya Kokko Cake",pref:"shizuoka",cat:"food",desc_ja:"静岡の銘菓こっこ",desc_en:"Shizuoka kokko sponge cake",deleted:true},
  {i:"sz018",ja:"焼津水産加工",en:"Yaizu Seafood Processing",pref:"shizuoka",cat:"food",desc_ja:"焼津のかつお節・干物",desc_en:"Yaizu katsuobushi & dried fish"},
  {i:"sz019",ja:"カネサ鰹節商店",en:"Kanesa Katsuobushi",pref:"shizuoka",cat:"food",desc_ja:"西伊豆の伝統かつお節",desc_en:"West Izu traditional katsuobushi",verified:true},
  {i:"sz020",ja:"磯自慢酒造",en:"Isojiman",pref:"shizuoka",cat:"sake",desc_ja:"焼津の高級酒蔵",desc_en:"Yaizu premium sake brewer",verified:true},
  {i:"sz021",ja:"株式会社駿河酒造場",en:"Suruga Brewery",pref:"shizuoka",cat:"sake",desc_ja:"静岡市の蔵元",desc_en:"Shizuoka City sake brewer"},
  {i:"sz022",ja:"花の舞酒造",en:"Hananomai Brewery",pref:"shizuoka",cat:"sake",desc_ja:"浜松の地酒蔵",desc_en:"Hamamatsu local sake brewer",verified:true},
  {i:"sz023",ja:"志太泉酒造",en:"Shidaizumi Brewery",pref:"shizuoka",cat:"sake",desc_ja:"藤枝の老舗酒蔵",desc_en:"Fujieda heritage sake brewer",verified:true},
  {i:"sz024",ja:"駿河竹千筋細工",en:"Suruga Bamboo Crafts",pref:"shizuoka",cat:"craft",desc_ja:"駿河の竹細工伝統工芸",desc_en:"Suruga bamboo craft tradition"},
  {i:"sz025",ja:"駿河塗下駄",en:"Suruga Geta",pref:"shizuoka",cat:"wood",desc_ja:"駿河の伝統下駄",desc_en:"Suruga traditional geta",deleted:true},
  {i:"sz026",ja:"浜松楽器部品工房",en:"Hamamatsu Music Parts",pref:"shizuoka",cat:"other",desc_ja:"楽器の部品OEM",desc_en:"Musical instrument parts OEM",deleted:true},
  {i:"sz027",ja:"静岡精密プラスチック",en:"Shizuoka Precision Plastics",pref:"shizuoka",cat:"other",desc_ja:"プラスチック精密成形",desc_en:"Precision plastic molding",deleted:true},
  {i:"sz028",ja:"静岡電子部品技研",en:"Shizuoka Electron Lab",pref:"shizuoka",cat:"electronics",desc_ja:"静岡の電子部品試作",desc_en:"Shizuoka electronic prototyping",deleted:true},
  {i:"sz029",ja:"伊豆コスメ研究所",en:"Izu Cosmetic Lab",pref:"shizuoka",cat:"cosmetics",desc_ja:"伊豆の温泉化粧品",desc_en:"Izu onsen-based cosmetics",deleted:true},
  {i:"sz030",ja:"静岡サプリ研究会",en:"Shizuoka Supplement Group",pref:"shizuoka",cat:"supplement",desc_ja:"茶・植物由来サプリ",desc_en:"Tea & botanical supplements",deleted:true},

  // ========== 愛知 / AICHI ==========
  {i:"ai001",ja:"常滑焼 山田陶器",en:"Yamada Pottery Tokoname",pref:"aichi",cat:"glass",desc_ja:"常滑焼の急須老舗",desc_en:"Heritage Tokoname kyusu teapot",deleted:true},
  {i:"ai002",ja:"常滑焼 急須 朝日",en:"Asahi Tokoname Kyusu",pref:"aichi",cat:"glass",desc_ja:"常滑の朱泥急須",desc_en:"Tokoname red-clay teapot",deleted:true},
  {i:"ai003",ja:"瀬戸焼 瀬戸本業窯",en:"Seto Hongyo Kiln",pref:"aichi",cat:"glass",desc_ja:"瀬戸焼の伝統窯元",desc_en:"Heritage Seto-yaki kiln",verified:true},
  {i:"ai004",ja:"INAX 常滑陶磁器試作",en:"Tokoname Ceramic Atelier",pref:"aichi",cat:"glass",desc_ja:"常滑の陶磁器試作OEM",desc_en:"Tokoname ceramic OEM",deleted:true},
  {i:"ai005",ja:"有松鳴海絞 竹田嘉兵衛商店",en:"Takeda Kahei Shibori",pref:"aichi",cat:"apparel",desc_ja:"有松絞りの老舗",desc_en:"Heritage Arimatsu shibori",verified:true},
  {i:"ai006",ja:"有松絞り 山上",en:"Yamagami Arimatsu",pref:"aichi",cat:"apparel",desc_ja:"有松絞りの工房",desc_en:"Arimatsu shibori atelier"},
  {i:"ai007",ja:"豊橋筆 川合筆",en:"Kawai Brush Toyohashi",pref:"aichi",cat:"craft",desc_ja:"豊橋筆の老舗",desc_en:"Heritage Toyohashi brush",verified:true},
  {i:"ai008",ja:"嵩山工房",en:"Suzando Toyohashi",pref:"aichi",cat:"craft",desc_ja:"豊橋筆の伝統工房",desc_en:"Toyohashi brush atelier"},
  {i:"ai009",ja:"敷島製パン (愛知)",en:"Shikishima Bakery",pref:"aichi",cat:"food",desc_ja:"愛知のパスコ系老舗",desc_en:"Heritage Aichi bakery (Pasco)"},
  {i:"ai010",ja:"カクキュー八丁味噌",en:"Kakukyu Hatcho Miso",pref:"aichi",cat:"food",desc_ja:"岡崎の老舗八丁味噌",desc_en:"Heritage Okazaki Hatcho miso",verified:true},
  {i:"ai011",ja:"まるや八丁味噌",en:"Maruya Hatcho Miso",pref:"aichi",cat:"food",desc_ja:"岡崎の八丁味噌老舗",desc_en:"Okazaki Hatcho miso heritage",verified:true},
  {i:"ai012",ja:"ナカモ (つけてみそかけてみそ)",en:"Nakamo Miso",pref:"aichi",cat:"food",desc_ja:"名古屋の味噌だれ",desc_en:"Nagoya miso sauce maker",verified:true},
  {i:"ai013",ja:"敷島醤油",en:"Shikishima Shoyu",pref:"aichi",cat:"food",desc_ja:"愛知の老舗醤油",desc_en:"Heritage Aichi soy sauce",deleted:true},
  {i:"ai014",ja:"妙香園 (お茶)",en:"Myokoen Tea",pref:"aichi",cat:"tea",desc_ja:"名古屋の老舗茶舗",desc_en:"Heritage Nagoya tea shop",verified:true},
  {i:"ai015",ja:"美濃志野焼 美濃陶磁器組合",en:"Mino Shino Coop",pref:"gifu",cat:"glass",desc_ja:"美濃焼の窯元組合",desc_en:"Mino-yaki kiln cooperative"},
  {i:"ai016",ja:"萬乗醸造 (久野九平治)",en:"Banjo Brewery (Kuheiji)",pref:"aichi",cat:"sake",desc_ja:"名古屋の醸し人九平次",desc_en:"Nagoya brewer of Kuheiji",verified:true},
  {i:"ai017",ja:"盛田 (尾張味噌・酒)",en:"Morita Brewery",pref:"aichi",cat:"sake",desc_ja:"知多の老舗酒蔵",desc_en:"Chita heritage sake brewer",verified:true},
  {i:"ai018",ja:"金虎酒造",en:"Kintora Brewery",pref:"aichi",cat:"sake",desc_ja:"名古屋の地酒蔵",desc_en:"Nagoya local sake brewer"},
  {i:"ai019",ja:"丸西屋 (常滑朱泥急須)",en:"Maruniya Tokoname",pref:"aichi",cat:"glass",desc_ja:"常滑朱泥急須の作家",desc_en:"Tokoname shudei kyusu artist",deleted:true},
  {i:"ai020",ja:"金物 山源",en:"Yamagen Hardware",pref:"aichi",cat:"cutlery",desc_ja:"愛知の金物・刃物",desc_en:"Aichi hardware & blades",deleted:true},
  {i:"ai021",ja:"豊田自動車部品 中小サプライヤー",en:"Toyota Tier-3 Supplier",pref:"aichi",cat:"electronics",desc_ja:"自動車部品の中小サプライヤー",desc_en:"Auto-parts Tier-3 SME",deleted:true},
  {i:"ai022",ja:"刈谷精密プレス",en:"Kariya Precision Press",pref:"aichi",cat:"electronics",desc_ja:"刈谷の精密板金",desc_en:"Kariya precision pressing",deleted:true},
  {i:"ai023",ja:"名古屋友禅",en:"Nagoya Yuzen",pref:"aichi",cat:"apparel",desc_ja:"名古屋の友禅染め",desc_en:"Nagoya yuzen dyeing",deleted:true},
  {i:"ai024",ja:"知多木綿 工房",en:"Chita Cotton Atelier",pref:"aichi",cat:"apparel",desc_ja:"知多木綿の伝統織物",desc_en:"Chita cotton traditional textile",deleted:true},
  {i:"ai025",ja:"三河木綿",en:"Mikawa Cotton",pref:"aichi",cat:"apparel",desc_ja:"三河木綿の織元",desc_en:"Mikawa cotton weaver",deleted:true},
  {i:"ai026",ja:"名古屋桐箪笥 川口",en:"Kawaguchi Kiri Tansu",pref:"aichi",cat:"wood",desc_ja:"名古屋桐箪笥の工房",desc_en:"Nagoya paulownia chest atelier",deleted:true},
  {i:"ai027",ja:"愛知化粧品研究所",en:"Aichi Cosmetics Lab",pref:"aichi",cat:"cosmetics",desc_ja:"名古屋の化粧品OEM",desc_en:"Nagoya cosmetics OEM",deleted:true},
  {i:"ai028",ja:"中部サプリメント",en:"Chubu Supplement",pref:"aichi",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"ai029",ja:"東光金箔",en:"Nagoya Gold Leaf",pref:"aichi",cat:"craft",desc_ja:"名古屋仏壇用金箔",desc_en:"Nagoya altar gold leaf"},
  {i:"ai030",ja:"名古屋仏壇 金澤仏壇店",en:"Kanazawa Butsudan Nagoya",pref:"aichi",cat:"craft",desc_ja:"名古屋仏壇の伝統",desc_en:"Nagoya altar tradition",deleted:true},
  {i:"ai031",ja:"瀬戸染付焼 加藤",en:"Kato Seto Sometsuke",pref:"aichi",cat:"glass",desc_ja:"瀬戸染付焼の窯元",desc_en:"Seto sometsuke kiln"},
  {i:"ai032",ja:"知多半島ハーブ農園",en:"Chita Herb Farm",pref:"aichi",cat:"cosmetics",desc_ja:"知多のハーブ化粧品原料",desc_en:"Chita herb cosmetic ingredients",deleted:true},
  {i:"ai033",ja:"名古屋電子試作工房",en:"Nagoya Electronic Atelier",pref:"aichi",cat:"electronics",desc_ja:"電子試作の中小",desc_en:"SME electronic prototyping",deleted:true},
  {i:"ai034",ja:"豊田特許応用研究所",en:"Toyota Patent Lab",pref:"aichi",cat:"patent",desc_ja:"特許技術応用の試作",desc_en:"Patent-applied prototyping",deleted:true},
  {i:"ai035",ja:"名古屋手延べ素麺",en:"Nagoya Hand-stretched Somen",pref:"aichi",cat:"food",desc_ja:"愛知の手延べ素麺",desc_en:"Aichi hand-stretched somen",deleted:true},
);
// data2.js ends — Kansai〜Okinawa は data3.js に続く
