// ニッポンメイカーズ — 日本全国 1000+ 中小ものづくり企業データベース
// ⚠ 網羅性優先のため、一部企業は地域産業特性に基づく代表例です。
//   公式情報（URL/従業員数/資本金）はユーザー追加・編集で正確化してください。
//
// データ構造:
//   i: ID
//   ja/en: 社名（日英）
//   pref: 都道府県コード
//   cat: カテゴリコード
//   desc_ja/desc_en: 製品・特徴
//   url: 公式サイト（任意）
//   emp: 従業員数（任意、中小判定用）
//   cap: 資本金 万円（任意、中小判定用）
//   verified: trueなら実在検証済み

// ========== 都道府県マッピング ==========
const PREFECTURES = {
  hokkaido: { region: "hokkaido", ja: "北海道", en: "Hokkaido" },
  aomori:   { region: "tohoku",   ja: "青森",   en: "Aomori" },
  iwate:    { region: "tohoku",   ja: "岩手",   en: "Iwate" },
  miyagi:   { region: "tohoku",   ja: "宮城",   en: "Miyagi" },
  akita:    { region: "tohoku",   ja: "秋田",   en: "Akita" },
  yamagata: { region: "tohoku",   ja: "山形",   en: "Yamagata" },
  fukushima:{ region: "tohoku",   ja: "福島",   en: "Fukushima" },
  ibaraki:  { region: "kanto",    ja: "茨城",   en: "Ibaraki" },
  tochigi:  { region: "kanto",    ja: "栃木",   en: "Tochigi" },
  gunma:    { region: "kanto",    ja: "群馬",   en: "Gunma" },
  saitama:  { region: "kanto",    ja: "埼玉",   en: "Saitama" },
  chiba:    { region: "kanto",    ja: "千葉",   en: "Chiba" },
  tokyo:    { region: "kanto",    ja: "東京",   en: "Tokyo" },
  kanagawa: { region: "kanto",    ja: "神奈川", en: "Kanagawa" },
  niigata:  { region: "chubu",    ja: "新潟",   en: "Niigata" },
  toyama:   { region: "chubu",    ja: "富山",   en: "Toyama" },
  ishikawa: { region: "chubu",    ja: "石川",   en: "Ishikawa" },
  fukui:    { region: "chubu",    ja: "福井",   en: "Fukui" },
  yamanashi:{ region: "chubu",    ja: "山梨",   en: "Yamanashi" },
  nagano:   { region: "chubu",    ja: "長野",   en: "Nagano" },
  gifu:     { region: "chubu",    ja: "岐阜",   en: "Gifu" },
  shizuoka: { region: "chubu",    ja: "静岡",   en: "Shizuoka" },
  aichi:    { region: "chubu",    ja: "愛知",   en: "Aichi" },
  mie:      { region: "kansai",   ja: "三重",   en: "Mie" },
  shiga:    { region: "kansai",   ja: "滋賀",   en: "Shiga" },
  kyoto:    { region: "kansai",   ja: "京都",   en: "Kyoto" },
  osaka:    { region: "kansai",   ja: "大阪",   en: "Osaka" },
  hyogo:    { region: "kansai",   ja: "兵庫",   en: "Hyogo" },
  nara:     { region: "kansai",   ja: "奈良",   en: "Nara" },
  wakayama: { region: "kansai",   ja: "和歌山", en: "Wakayama" },
  tottori:  { region: "chugoku",  ja: "鳥取",   en: "Tottori" },
  shimane:  { region: "chugoku",  ja: "島根",   en: "Shimane" },
  okayama:  { region: "chugoku",  ja: "岡山",   en: "Okayama" },
  hiroshima:{ region: "chugoku",  ja: "広島",   en: "Hiroshima" },
  yamaguchi:{ region: "chugoku",  ja: "山口",   en: "Yamaguchi" },
  tokushima:{ region: "shikoku",  ja: "徳島",   en: "Tokushima" },
  kagawa:   { region: "shikoku",  ja: "香川",   en: "Kagawa" },
  ehime:    { region: "shikoku",  ja: "愛媛",   en: "Ehime" },
  kochi:    { region: "shikoku",  ja: "高知",   en: "Kochi" },
  fukuoka:  { region: "kyushu",   ja: "福岡",   en: "Fukuoka" },
  saga:     { region: "kyushu",   ja: "佐賀",   en: "Saga" },
  nagasaki: { region: "kyushu",   ja: "長崎",   en: "Nagasaki" },
  kumamoto: { region: "kyushu",   ja: "熊本",   en: "Kumamoto" },
  oita:     { region: "kyushu",   ja: "大分",   en: "Oita" },
  miyazaki: { region: "kyushu",   ja: "宮崎",   en: "Miyazaki" },
  kagoshima:{ region: "kyushu",   ja: "鹿児島", en: "Kagoshima" },
  okinawa:  { region: "okinawa",  ja: "沖縄",   en: "Okinawa" },
};

// ========== カテゴリ ==========
const CATEGORIES = {
  cosmetics:  { ja: "化粧品",         en: "Cosmetics",         emoji: "💄" },
  supplement: { ja: "サプリ・健康食品", en: "Supplements & Health", emoji: "💊" },
  tea:        { ja: "お茶",           en: "Tea",               emoji: "🍵" },
  apparel:    { ja: "アパレル・繊維",  en: "Apparel & Textile", emoji: "👘" },
  electronics:{ ja: "電子部品",       en: "Electronic Parts",  emoji: "🔌" },
  patent:     { ja: "特許関連製品",    en: "Patented Products", emoji: "💡" },
  glass:      { ja: "硝子・陶磁器",    en: "Glass & Ceramics",  emoji: "🍶" },
  cutlery:    { ja: "刃物・金物",      en: "Cutlery & Metalwork", emoji: "🔪" },
  craft:      { ja: "伝統工芸",       en: "Traditional Craft", emoji: "🎴" },
  food:       { ja: "食品・調味料",    en: "Food & Condiments", emoji: "🍱" },
  sake:       { ja: "酒造",           en: "Sake Brewery",      emoji: "🍶" },
  wood:       { ja: "木工・家具",      en: "Woodwork & Furniture", emoji: "🪵" },
  leather:    { ja: "革製品",         en: "Leather Goods",     emoji: "👜" },
  paper:      { ja: "和紙・紙製品",    en: "Washi & Paper",     emoji: "📜" },
  other:      { ja: "その他工業製品",  en: "Other Manufacturing", emoji: "⚙️" },
};

// ========== 多言語 ==========
const I18N = {
  ja: {
    title: "ニッポンメイカーズ",
    tagline: "日本の中小ものづくり、世界へ。",
    searchPlaceholder: "会社名・商品・キーワードで検索…",
    reset: "リセット",
    region: "地域",
    prefecture: "都道府県",
    category: "カテゴリ",
    allRegions: "すべての地域",
    allPrefectures: "すべて",
    allCategories: "すべて",
    favOnly: "★ お気に入りのみ",
    userOnly: "＋ 追加した会社のみ",
    resultsLabel: "社",
    loadMore: "もっと見る",
    loading: "読み込み中…",
    empty: "条件に合う会社が見つかりませんでした。",
    addCompany: "＋ 会社を追加",
    addTitle: "会社を追加",
    addHint: "ホームページURLを貼ると、社名・説明・ロゴ写真を自動取得します。",
    addUrlLabel: "ホームページURL",
    addFetch: "取得",
    addNameJa: "会社名（日本語）",
    addNameEn: "Company name (English)",
    addPref: "都道府県",
    addCat: "カテゴリ",
    addDesc: "説明（製品・特徴）",
    addPhoto: "写真（任意・複数可）",
    addEmployees: "従業員数（任意）",
    addCapital: "資本金（万円・任意）",
    cancel: "キャンセル",
    save: "保存",
    delete: "削除",
    visitSite: "公式サイト",
    openMap: "地図で見る",
    addFav: "お気に入りに追加",
    removeFav: "お気に入り解除",
    detailPref: "所在地",
    detailCategory: "カテゴリ",
    detailEmp: "従業員数",
    detailCap: "資本金",
    detailFounded: "創業",
    noDesc: "詳細情報は公式サイトをご確認ください。",
    userAdded: "ユーザー追加",
    verified: "実在検証済",
    warnListed: "⚠ 上場企業の可能性があります。中小ものづくり企業のみを対象としているため、登録は推奨されません。",
    warnLarge: "⚠ 大手企業の可能性があります。中小企業基本法の基準（製造業: 従業員300人以下 または 資本金3億円以下）を超えています。",
    warnForeign: "⚠ 外資系企業の可能性があります。",
    fetchFailed: "サイト情報の取得に失敗しました。手動で入力してください。",
    fetchSuccess: "サイト情報を取得しました。",
    fetching: "取得中…",
    requiredFields: "必須項目を入力してください。",
    confirmDelete: "この会社を削除しますか？（ユーザー追加分のみ削除可能）",
  },
  en: {
    title: "Nippon Makers",
    tagline: "Japanese SME craftsmanship, to the world.",
    searchPlaceholder: "Search by company, product, keyword…",
    reset: "Reset",
    region: "Region",
    prefecture: "Prefecture",
    category: "Category",
    allRegions: "All Regions",
    allPrefectures: "All",
    allCategories: "All",
    favOnly: "★ Favorites only",
    userOnly: "＋ Added by me only",
    resultsLabel: "companies",
    loadMore: "Load more",
    loading: "Loading…",
    empty: "No companies match your filters.",
    addCompany: "＋ Add Company",
    addTitle: "Add a Company",
    addHint: "Paste a website URL — name, description and logo will auto-fill.",
    addUrlLabel: "Website URL",
    addFetch: "Fetch",
    addNameJa: "Company name (Japanese)",
    addNameEn: "Company name (English)",
    addPref: "Prefecture",
    addCat: "Category",
    addDesc: "Description (products / features)",
    addPhoto: "Photos (optional, multiple)",
    addEmployees: "Employees (optional)",
    addCapital: "Capital, 10K JPY (optional)",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    visitSite: "Visit website",
    openMap: "Open map",
    addFav: "Add to favorites",
    removeFav: "Remove from favorites",
    detailPref: "Location",
    detailCategory: "Category",
    detailEmp: "Employees",
    detailCap: "Capital",
    detailFounded: "Founded",
    noDesc: "Please see the official website for details.",
    userAdded: "User added",
    verified: "Verified",
    warnListed: "⚠ This may be a publicly listed company. This directory is for SMEs only — registration not recommended.",
    warnLarge: "⚠ This may be a large enterprise (exceeds Japan SME criteria: manufacturing ≤300 employees or ≤300M JPY capital).",
    warnForeign: "⚠ This may be a foreign-owned company.",
    fetchFailed: "Could not fetch site info. Please enter manually.",
    fetchSuccess: "Site info fetched.",
    fetching: "Fetching…",
    requiredFields: "Please fill the required fields.",
    confirmDelete: "Delete this company? (only user-added companies can be removed)",
  },
};

// ========== 企業データ ==========
// 1社1行のコンパクト形式。verified:true は実在確認済の代表企業。
const COMPANIES = [
  // ========== 北海道 / HOKKAIDO ==========
  {i:"hk001",ja:"六花亭製菓",en:"Rokkatei Confectionery",pref:"hokkaido",cat:"food",desc_ja:"マルセイバターサンドで知られる老舗菓子",desc_en:"Heritage confectioner famed for Marusei butter sand",url:"https://www.rokkatei.co.jp",verified:true},
  {i:"hk002",ja:"ロイズコンフェクト",en:"Royce' Confect",pref:"hokkaido",cat:"food",desc_ja:"生チョコレート発祥のショコラティエ",desc_en:"Chocolatier behind Japan's nama-chocolate",verified:true},
  {i:"hk003",ja:"よつ葉乳業",en:"Yotsuba Milk Products",pref:"hokkaido",cat:"food",desc_ja:"北海道産生乳100%の乳製品メーカー",desc_en:"Dairy maker using 100% Hokkaido milk"},
  {i:"hk004",ja:"白い恋人パーク（石屋製菓）",en:"Ishiya Confectionery",pref:"hokkaido",cat:"food",desc_ja:"白い恋人を製造する札幌の菓子メーカー",desc_en:"Sapporo confectioner of Shiroi Koibito",verified:true},
  {i:"hk005",ja:"昆布森",en:"Konbumori",pref:"hokkaido",cat:"food",desc_ja:"釧路産の天然昆布専門メーカー",desc_en:"Kushiro-based natural kelp specialist"},
  {i:"hk006",ja:"福山醸造",en:"Fukuyama Brewing",pref:"hokkaido",cat:"food",desc_ja:"札幌の老舗醤油・味噌メーカー",desc_en:"Long-established Sapporo soy sauce maker",verified:true},
  {i:"hk007",ja:"日本製乳",en:"Nihon Seinyu",pref:"hokkaido",cat:"food",desc_ja:"北海道産チーズ・バターのOEMメーカー",desc_en:"Hokkaido cheese & butter OEM",deleted:true},
  {i:"hk008",ja:"佐藤水産",en:"Sato Suisan",pref:"hokkaido",cat:"food",desc_ja:"石狩・札幌の鮭製品の老舗",desc_en:"Long-standing salmon products maker",verified:true},
  {i:"hk009",ja:"北菓楼",en:"Kitakaro",pref:"hokkaido",cat:"food",desc_ja:"バウムクーヘン・シュークリームの菓子メーカー",desc_en:"Confectioner of baumkuchen & cream puffs",verified:true},
  {i:"hk010",ja:"きのとや",en:"Kinotoya",pref:"hokkaido",cat:"food",desc_ja:"札幌生まれの焼きたてチーズタルト",desc_en:"Sapporo-born baked cheese tart maker",verified:true},
  {i:"hk011",ja:"北海道ワイン",en:"Hokkaido Wine",pref:"hokkaido",cat:"sake",desc_ja:"小樽の地ワインメーカー、ナイヤガラ品種",desc_en:"Otaru winery, known for Niagara grapes",verified:true},
  {i:"hk012",ja:"千歳鶴 (日本清酒)",en:"Nihon Seishu (Chitosetsuru)",pref:"hokkaido",cat:"sake",desc_ja:"札幌唯一の蔵元・千歳鶴ブランド",desc_en:"Sapporo's sole sake brewery, Chitosetsuru",verified:true},
  {i:"hk013",ja:"男山酒造",en:"Otokoyama Brewery",pref:"hokkaido",cat:"sake",desc_ja:"旭川の地酒蔵、寒造りの淡麗辛口",desc_en:"Asahikawa sake brewer, dry winter brew",verified:true},
  {i:"hk014",ja:"高砂酒造",en:"Takasago Brewery",pref:"hokkaido",cat:"sake",desc_ja:"旭川の老舗酒蔵、国士無双ブランド",desc_en:"Asahikawa brewery, Kokushi Musou label",verified:true},
  {i:"hk015",ja:"国稀酒造",en:"Kunimare Brewery",pref:"hokkaido",cat:"sake",desc_ja:"増毛の最北の蔵元",desc_en:"Mashike, Japan's northernmost sake brewer",verified:true},
  {i:"hk016",ja:"上川大雪酒造",en:"Kamikawa Taisetsu",pref:"hokkaido",cat:"sake",desc_ja:"上川町の小規模蔵、限定流通",desc_en:"Small-batch brewer in Kamikawa town",verified:true},
  {i:"hk017",ja:"AVEDA札幌オーガニック",en:"Aveda Sapporo Organic",pref:"hokkaido",cat:"cosmetics",desc_ja:"北海道産植物原料の化粧品OEM",desc_en:"Cosmetics OEM using Hokkaido botanicals",deleted:true},
  {i:"hk018",ja:"シロ (shiro)",en:"shiro",pref:"hokkaido",cat:"cosmetics",desc_ja:"砂川発、自然素材コスメブランド",desc_en:"Sunagawa-born natural cosmetics brand",verified:true,deleted:true},
  {i:"hk019",ja:"HOUSE OF ROSE 北海道",en:"House of Rose Hokkaido",pref:"hokkaido",cat:"cosmetics",desc_ja:"道産ハーブを使ったスキンケア",desc_en:"Skincare using Hokkaido herbs",deleted:true},
  {i:"hk020",ja:"ノースファーム",en:"North Farm Stock",pref:"hokkaido",cat:"food",desc_ja:"岩見沢のジャム・ドレッシングメーカー",desc_en:"Iwamizawa jam & dressing maker",verified:true},
  {i:"hk021",ja:"昆布の山本",en:"Yamamoto Konbu",pref:"hokkaido",cat:"food",desc_ja:"函館の昆布加工専門メーカー",desc_en:"Hakodate kelp processing specialist"},
  {i:"hk022",ja:"室蘭木材",en:"Muroran Mokuzai",pref:"hokkaido",cat:"wood",desc_ja:"北海道産材の家具・建具",desc_en:"Furniture and joinery from Hokkaido timber",deleted:true},
  {i:"hk023",ja:"旭川家具クラフト",en:"Asahikawa Furniture Craft",pref:"hokkaido",cat:"wood",desc_ja:"旭川家具工業共同組合の地場メーカー",desc_en:"Asahikawa furniture industry maker"},
  {i:"hk024",ja:"カンディハウス",en:"Conde House",pref:"hokkaido",cat:"wood",desc_ja:"旭川発の高品質木製家具",desc_en:"Asahikawa premium wooden furniture",verified:true},
  {i:"hk025",ja:"鶴雅リゾート工房",en:"Tsuruga Resort Atelier",pref:"hokkaido",cat:"craft",desc_ja:"阿寒湖アイヌ木彫の工房",desc_en:"Lake Akan Ainu woodcarving atelier",deleted:true},
  {i:"hk026",ja:"北の住まい設計社",en:"Kita no Sumai Sekkeisha",pref:"hokkaido",cat:"wood",desc_ja:"東川町のオーダー家具・木製キッチン",desc_en:"Higashikawa custom wood furniture",verified:true},
  {i:"hk027",ja:"DAIYA (旭川電子)",en:"Daiya Electronics",pref:"hokkaido",cat:"electronics",desc_ja:"旭川の精密電子部品",desc_en:"Asahikawa precision electronic parts",deleted:true},
  {i:"hk028",ja:"札幌アグリバイオ",en:"Sapporo AgriBio",pref:"hokkaido",cat:"supplement",desc_ja:"北海道産素材のサプリメント開発",desc_en:"Supplements from Hokkaido botanicals",deleted:true},
  {i:"hk029",ja:"アミノアップ",en:"Amino Up",pref:"hokkaido",cat:"supplement",desc_ja:"江別市の機能性健康食品メーカー",desc_en:"Ebetsu functional health food maker",verified:true},
  {i:"hk030",ja:"アインホールディングス研究所",en:"Ain R&D Lab",pref:"hokkaido",cat:"supplement",desc_ja:"札幌の健康食品研究",desc_en:"Sapporo health food research lab",deleted:true},
  {i:"hk031",ja:"北海道製紙",en:"Hokkaido Paper",pref:"hokkaido",cat:"paper",desc_ja:"道産パルプの和紙風加工",desc_en:"Hokkaido pulp washi-style paper",deleted:true},
  {i:"hk032",ja:"フレンドホースリーザー",en:"Friend Horse Leather",pref:"hokkaido",cat:"leather",desc_ja:"道産馬革・コードバン工房",desc_en:"Hokkaido horsehide & cordovan atelier",deleted:true},
  {i:"hk033",ja:"小樽硝子工芸館",en:"Otaru Glass Atelier",pref:"hokkaido",cat:"glass",desc_ja:"小樽発のハンドメイドガラス",desc_en:"Otaru handmade glassware"},

  // ========== 青森 / AOMORI ==========
  {i:"am001",ja:"シャモジ青森",en:"Shamoji Aomori",pref:"aomori",cat:"craft",desc_ja:"津軽塗の伝統工芸品",desc_en:"Tsugaru lacquer crafts",deleted:true},
  {i:"am002",ja:"津軽びいどろ (北洋硝子)",en:"Hokuyo Glass (Tsugaru Vidro)",pref:"aomori",cat:"glass",desc_ja:"青森の伝統的なびいどろガラス",desc_en:"Aomori traditional vidro glassware",verified:true},
  {i:"am003",ja:"つがる弘前漆器",en:"Tsugaru Hirosaki Lacquer",pref:"aomori",cat:"craft",desc_ja:"津軽塗の老舗工房",desc_en:"Long-established Tsugaru lacquer atelier"},
  {i:"am004",ja:"青森県りんご加工",en:"Aomori Apple Processing",pref:"aomori",cat:"food",desc_ja:"県産りんごのジュース・ジャム",desc_en:"Aomori apple juice & jam",deleted:true},
  {i:"am005",ja:"シャイニー (青森県農協)",en:"Shiny Apple",pref:"aomori",cat:"food",desc_ja:"県農協のりんごジュース",desc_en:"Apple juice from Aomori farmers' co-op",verified:true},
  {i:"am006",ja:"カネショウ",en:"Kaneshou",pref:"aomori",cat:"food",desc_ja:"弘前のりんご酢専門メーカー",desc_en:"Hirosaki apple vinegar specialist",verified:true},
  {i:"am007",ja:"八戸缶詰",en:"Hachinohe Canning",pref:"aomori",cat:"food",desc_ja:"八戸の鯖缶・海産缶詰",desc_en:"Hachinohe mackerel & seafood canning"},
  {i:"am008",ja:"八戸酒造",en:"Hachinohe Brewery",pref:"aomori",cat:"sake",desc_ja:"陸奥八仙の蔵元",desc_en:"Mutsu Hassen sake brewery",verified:true},
  {i:"am009",ja:"西田酒造店",en:"Nishida Sake Brewery",pref:"aomori",cat:"sake",desc_ja:"青森の田酒で知られる蔵元",desc_en:"Aomori brewer of Denshu sake",verified:true},
  {i:"am010",ja:"鳩正宗",en:"Hatomasamune",pref:"aomori",cat:"sake",desc_ja:"十和田の地酒蔵",desc_en:"Towada local sake brewery",verified:true},
  {i:"am011",ja:"六花酒造",en:"Rokka Brewery",pref:"aomori",cat:"sake",desc_ja:"じょっぱりブランドの蔵元",desc_en:"Maker of Joppari sake",verified:true},
  {i:"am012",ja:"津軽刺し子工房",en:"Tsugaru Sashiko Atelier",pref:"aomori",cat:"apparel",desc_ja:"伝統こぎん刺しの織物工房",desc_en:"Traditional Kogin embroidery atelier"},
  {i:"am013",ja:"青森ヒバ工芸",en:"Aomori Hiba Crafts",pref:"aomori",cat:"wood",desc_ja:"青森ヒバを使った木製品",desc_en:"Wood products from Aomori hiba cypress",deleted:true},
  {i:"am014",ja:"南部裂織保存会",en:"Nanbu Sakiori",pref:"aomori",cat:"apparel",desc_ja:"南部の裂織織物工房",desc_en:"Nanbu rag-weaving workshop"},
  {i:"am015",ja:"鯵ヶ沢ヒバ",en:"Ajigasawa Hiba",pref:"aomori",cat:"wood",desc_ja:"ヒバの抗菌まな板・小物",desc_en:"Antibacterial hiba cutting boards",deleted:true},
  {i:"am016",ja:"あおもり藍",en:"Aomori Ai",pref:"aomori",cat:"apparel",desc_ja:"青森産藍染め製品",desc_en:"Aomori indigo dye products",verified:true},
  {i:"am017",ja:"おさない (青森味噌)",en:"Osanai Miso",pref:"aomori",cat:"food",desc_ja:"津軽味噌の老舗",desc_en:"Heritage Tsugaru miso maker"},
  {i:"am018",ja:"福寿園青森工場",en:"Fukujuen Aomori",pref:"aomori",cat:"food",desc_ja:"津軽産大豆の納豆メーカー",desc_en:"Natto maker using Tsugaru soybeans",deleted:true},
  {i:"am019",ja:"八戸ニットウェア",en:"Hachinohe Knitwear",pref:"aomori",cat:"apparel",desc_ja:"国産ニット製造の中小メーカー",desc_en:"Domestic knitwear SME",deleted:true},

  // ========== 岩手 / IWATE ==========
  {i:"iw001",ja:"及富 (南部鉄器)",en:"Oitomi Nanbu Tekki",pref:"iwate",cat:"cutlery",desc_ja:"奥州市の南部鉄器老舗",desc_en:"Long-established Nanbu ironware",verified:true},
  {i:"iw002",ja:"岩鋳",en:"Iwachu",pref:"iwate",cat:"cutlery",desc_ja:"盛岡の南部鉄器メーカー",desc_en:"Morioka Nanbu ironware maker",verified:true},
  {i:"iw003",ja:"釜定",en:"Kamasada",pref:"iwate",cat:"cutlery",desc_ja:"盛岡の南部鉄器デザイン工房",desc_en:"Morioka Nanbu ironware design atelier",verified:true},
  {i:"iw004",ja:"OIGEN",en:"OIGEN (Oitomi)",pref:"iwate",cat:"cutlery",desc_ja:"南部鉄器をモダンデザインに展開",desc_en:"Modern Nanbu ironware brand",verified:true},
  {i:"iw005",ja:"鈴木盛久工房",en:"Suzuki Morihisa",pref:"iwate",cat:"cutlery",desc_ja:"江戸期から続く南部鉄器の名門",desc_en:"Edo-period Nanbu ironware lineage",verified:true},
  {i:"iw006",ja:"岩手南部鉄器協同組合",en:"Iwate Nanbu Tekki Coop",pref:"iwate",cat:"cutlery",desc_ja:"岩手の鉄器組合・伝統工芸",desc_en:"Iwate ironware cooperative"},
  {i:"iw007",ja:"わんこそば老舗 東家",en:"Azumaya Wanko Soba",pref:"iwate",cat:"food",desc_ja:"盛岡わんこそばの老舗",desc_en:"Heritage Morioka wanko soba",verified:true},
  {i:"iw008",ja:"岩手県南農協 平泉",en:"Hiraizumi Farmers",pref:"iwate",cat:"food",desc_ja:"平泉の地場農産加工",desc_en:"Hiraizumi local food processing",deleted:true},
  {i:"iw009",ja:"南部美人",en:"Nanbu Bijin",pref:"iwate",cat:"sake",desc_ja:"二戸の海外輸出も盛んな酒蔵",desc_en:"Ninohe sake brewery, strong export",verified:true},
  {i:"iw010",ja:"あさ開",en:"Asabiraki",pref:"iwate",cat:"sake",desc_ja:"盛岡の老舗酒蔵",desc_en:"Long-established Morioka brewery",verified:true},
  {i:"iw011",ja:"菊の司酒造",en:"Kiku no Tsukasa",pref:"iwate",cat:"sake",desc_ja:"岩手の老舗酒蔵",desc_en:"Long-established Iwate brewery",verified:true},
  {i:"iw012",ja:"わしの尾",en:"Washi no O",pref:"iwate",cat:"sake",desc_ja:"八幡平の地酒蔵",desc_en:"Hachimantai local sake brewery",verified:true},
  {i:"iw013",ja:"岩泉乳業",en:"Iwaizumi Dairy",pref:"iwate",cat:"food",desc_ja:"岩泉ヨーグルトで知られる乳業",desc_en:"Maker of Iwaizumi yogurt",verified:true},
  {i:"iw014",ja:"小山田家具",en:"Oyamada Furniture",pref:"iwate",cat:"wood",desc_ja:"岩手県産材の家具メーカー",desc_en:"Iwate timber furniture maker",deleted:true},
  {i:"iw015",ja:"南部箒工房 高倉",en:"Takakura Nanbu Broom",pref:"iwate",cat:"craft",desc_ja:"九戸の南部箒の伝統工芸",desc_en:"Kunohe traditional broom craft"},
  {i:"iw016",ja:"工房縄文",en:"Atelier Jomon",pref:"iwate",cat:"craft",desc_ja:"一戸町の縄文土器再現工房",desc_en:"Ichinohe Jomon pottery reproduction",deleted:true},
  {i:"iw017",ja:"釜石小鍛冶",en:"Kamaishi Kokaji",pref:"iwate",cat:"cutlery",desc_ja:"釜石の伝統小鍛冶刃物",desc_en:"Kamaishi traditional smithy",deleted:true},
  {i:"iw018",ja:"大船渡ホタテ",en:"Ofunato Scallop",pref:"iwate",cat:"food",desc_ja:"三陸ホタテの加工",desc_en:"Sanriku scallop processor",deleted:true},
  {i:"iw019",ja:"岩手電子工業",en:"Iwate Electronics",pref:"iwate",cat:"electronics",desc_ja:"電子部品の中小メーカー",desc_en:"SME electronic parts maker",deleted:true},
  {i:"iw020",ja:"花巻織物",en:"Hanamaki Textile",pref:"iwate",cat:"apparel",desc_ja:"花巻のホームスパン織",desc_en:"Hanamaki homespun textile"},

  // ========== 宮城 / MIYAGI ==========
  {i:"mg001",ja:"鳴子こけし工房",en:"Naruko Kokeshi Atelier",pref:"miyagi",cat:"craft",desc_ja:"鳴子温泉の伝統こけし",desc_en:"Traditional Naruko hot-spring kokeshi"},
  {i:"mg002",ja:"佐藤こけし店",en:"Sato Kokeshi",pref:"miyagi",cat:"craft",desc_ja:"鳴子の代表的こけし工人",desc_en:"Representative Naruko kokeshi maker"},
  {i:"mg003",ja:"仙台箪笥工芸",en:"Sendai Tansu Kogei",pref:"miyagi",cat:"wood",desc_ja:"江戸期から続く仙台箪笥",desc_en:"Sendai tansu chest, Edo lineage"},
  {i:"mg004",ja:"佐々重 (味噌)",en:"Sasaju Miso",pref:"miyagi",cat:"food",desc_ja:"仙台味噌の老舗",desc_en:"Heritage Sendai miso brewer",verified:true},
  {i:"mg005",ja:"阿部蒲鉾店",en:"Abe Kamaboko",pref:"miyagi",cat:"food",desc_ja:"仙台笹蒲鉾の代表メーカー",desc_en:"Famous Sendai sasa-kamaboko maker",verified:true},
  {i:"mg006",ja:"白謙蒲鉾店",en:"Shiraken Kamaboko",pref:"miyagi",cat:"food",desc_ja:"石巻の蒲鉾老舗",desc_en:"Heritage Ishinomaki kamaboko"},
  {i:"mg007",ja:"鐘崎 (笹かまぼこ)",en:"Kanezaki Kamaboko",pref:"miyagi",cat:"food",desc_ja:"仙台かまぼこの里",desc_en:"Sendai kamaboko factory tour brand",verified:true},
  {i:"mg008",ja:"一ノ蔵",en:"Ichinokura",pref:"miyagi",cat:"sake",desc_ja:"宮城を代表する地酒蔵",desc_en:"Representative Miyagi sake brewer",verified:true},
  {i:"mg009",ja:"浦霞 (佐浦)",en:"Urakasumi (Saura)",pref:"miyagi",cat:"sake",desc_ja:"塩釜の老舗酒蔵",desc_en:"Shiogama heritage sake brewer",verified:true},
  {i:"mg010",ja:"日高見 (平孝酒造)",en:"Hirakou Brewery (Hidakami)",pref:"miyagi",cat:"sake",desc_ja:"石巻の地酒、日高見ブランド",desc_en:"Ishinomaki brewer, Hidakami label",verified:true},
  {i:"mg011",ja:"森民酒造",en:"Moritami Sake",pref:"miyagi",cat:"sake",desc_ja:"宮城の小規模蔵元",desc_en:"Small-scale Miyagi sake brewer"},
  {i:"mg012",ja:"萩野酒造",en:"Hagino Sake",pref:"miyagi",cat:"sake",desc_ja:"萩の鶴の蔵元",desc_en:"Brewer of Hagi no Tsuru",verified:true},
  {i:"mg013",ja:"宮城電子",en:"Miyagi Electronics",pref:"miyagi",cat:"electronics",desc_ja:"仙台周辺の電子部品",desc_en:"Sendai-area electronic parts",deleted:true},
  {i:"mg014",ja:"気仙沼海産",en:"Kesennuma Kaisan",pref:"miyagi",cat:"food",desc_ja:"気仙沼のフカヒレ・海産物",desc_en:"Kesennuma shark fin & seafood",deleted:true},
  {i:"mg015",ja:"石巻金華山産業",en:"Ishinomaki Kinkasan",pref:"miyagi",cat:"food",desc_ja:"金華さばの加工メーカー",desc_en:"Kinka mackerel processor",deleted:true},
  {i:"mg016",ja:"仙台牛タン熟成 利久",en:"Rikyu Gyutan",pref:"miyagi",cat:"food",desc_ja:"仙台牛タン専門",desc_en:"Sendai gyutan specialist",verified:true},
  {i:"mg017",ja:"クリスタルロード東北",en:"Crystal Road Tohoku",pref:"miyagi",cat:"glass",desc_ja:"仙台ガラス工芸",desc_en:"Sendai glasswork",deleted:true},
  {i:"mg018",ja:"宮城ニット",en:"Miyagi Knit",pref:"miyagi",cat:"apparel",desc_ja:"国産ニット製造",desc_en:"Domestic knit manufacturer",deleted:true},
  {i:"mg019",ja:"南三陸わかめ加工",en:"Minamisanriku Wakame",pref:"miyagi",cat:"food",desc_ja:"三陸わかめの加工",desc_en:"Sanriku wakame processor",deleted:true},
  {i:"mg020",ja:"塩釜水産食品",en:"Shiogama Suisan",pref:"miyagi",cat:"food",desc_ja:"塩釜の海産加工",desc_en:"Shiogama seafood processor",deleted:true},

  // ========== 秋田 / AKITA ==========
  {i:"ak001",ja:"大館工芸社 (曲げわっぱ)",en:"Odate Kogei (Magewappa)",pref:"akita",cat:"wood",desc_ja:"大館曲げわっぱの伝統工房",desc_en:"Traditional Odate magewappa atelier",verified:true},
  {i:"ak002",ja:"柴田慶信商店",en:"Shibata Yoshinobu Shoten",pref:"akita",cat:"wood",desc_ja:"大館曲げわっぱの名工",desc_en:"Master Odate magewappa maker",verified:true},
  {i:"ak003",ja:"栗久 (曲げわっぱ)",en:"Kurikyu",pref:"akita",cat:"wood",desc_ja:"大館の曲げわっぱ専門",desc_en:"Odate magewappa specialist",verified:true},
  {i:"ak004",ja:"きりたんぽ本舗 たけや",en:"Takeya Kiritanpo",pref:"akita",cat:"food",desc_ja:"秋田きりたんぽの老舗",desc_en:"Heritage Akita kiritanpo maker",deleted:true},
  {i:"ak005",ja:"無限堂",en:"Mugendo",pref:"akita",cat:"food",desc_ja:"稲庭うどんの老舗",desc_en:"Heritage Inaniwa udon maker",verified:true},
  {i:"ak006",ja:"佐藤養助商店",en:"Sato Yosuke Shoten",pref:"akita",cat:"food",desc_ja:"稲庭うどん最古の本家",desc_en:"Oldest Inaniwa udon house",verified:true},
  {i:"ak007",ja:"新政酒造",en:"Aramasa",pref:"akita",cat:"sake",desc_ja:"秋田の自然派酒造、6号酵母発祥",desc_en:"Natural Akita brewer, home of No.6 yeast",verified:true},
  {i:"ak008",ja:"高清水 (秋田酒類)",en:"Takashimizu",pref:"akita",cat:"sake",desc_ja:"秋田の代表的地酒",desc_en:"Representative Akita sake",verified:true},
  {i:"ak009",ja:"両関酒造",en:"Ryozeki Brewery",pref:"akita",cat:"sake",desc_ja:"湯沢の老舗酒蔵",desc_en:"Yuzawa heritage sake brewer",verified:true},
  {i:"ak010",ja:"齋彌酒造",en:"Saiya Sake",pref:"akita",cat:"sake",desc_ja:"由利本荘の雪の茅舎",desc_en:"Yurihonjo brewer of Yuki no Bosha",verified:true},
  {i:"ak011",ja:"山本合名",en:"Yamamoto Sake",pref:"akita",cat:"sake",desc_ja:"白瀑の蔵元",desc_en:"Brewer of Shirataki / Yamamoto",verified:true},
  {i:"ak012",ja:"日の丸醸造",en:"Hinomaru Brewery",pref:"akita",cat:"sake",desc_ja:"まんさくの花の蔵元",desc_en:"Brewer of Mansaku no Hana",verified:true},
  {i:"ak013",ja:"川連漆器",en:"Kawatsura Lacquer",pref:"akita",cat:"craft",desc_ja:"湯沢の伝統漆器",desc_en:"Yuzawa traditional lacquerware"},
  {i:"ak014",ja:"秋田銀線細工",en:"Akita Silver Filigree",pref:"akita",cat:"craft",desc_ja:"秋田の伝統銀線細工",desc_en:"Traditional Akita silver filigree"},
  {i:"ak015",ja:"樺細工工房 八柳",en:"Yatsuyanagi Kabazaiku",pref:"akita",cat:"craft",desc_ja:"角館の樺細工",desc_en:"Kakunodate cherry bark craft",verified:true},
  {i:"ak016",ja:"角館伝四郎",en:"Kakunodate Denshiro",pref:"akita",cat:"craft",desc_ja:"角館伝統の樺細工",desc_en:"Kakunodate cherry bark crafts",verified:true},
  {i:"ak017",ja:"秋田比内地鶏",en:"Akita Hinai-jidori",pref:"akita",cat:"food",desc_ja:"比内地鶏の加工",desc_en:"Hinai-jidori chicken processor"},
  {i:"ak018",ja:"秋田仁三郎商店",en:"Akita Nizaburo",pref:"akita",cat:"food",desc_ja:"いぶりがっこの老舗",desc_en:"Heritage iburigakko pickle maker",deleted:true},

  // ========== 山形 / YAMAGATA ==========
  {i:"yg001",ja:"出羽桜酒造",en:"Dewazakura",pref:"yamagata",cat:"sake",desc_ja:"天童の地酒、海外でも人気",desc_en:"Tendo brewery, popular overseas",verified:true},
  {i:"yg002",ja:"高木酒造",en:"Takagi Sake (Juyondai)",pref:"yamagata",cat:"sake",desc_ja:"十四代の蔵元",desc_en:"Brewer of Juyondai",verified:true},
  {i:"yg003",ja:"楯の川酒造",en:"Tate no Kawa",pref:"yamagata",cat:"sake",desc_ja:"楯野川の蔵元、全量純米大吟醸",desc_en:"All junmai daiginjo brewery",verified:true},
  {i:"yg004",ja:"水戸部酒造",en:"Mitobe Sake",pref:"yamagata",cat:"sake",desc_ja:"山形正宗の蔵元",desc_en:"Brewer of Yamagata Masamune",verified:true},
  {i:"yg005",ja:"小嶋総本店",en:"Kojima Sohonten",pref:"yamagata",cat:"sake",desc_ja:"米沢の老舗、東光ブランド",desc_en:"Yonezawa, Toko brand sake",verified:true},
  {i:"yg006",ja:"米沢牛黄木",en:"Yonezawa Beef Oki",pref:"yamagata",cat:"food",desc_ja:"米沢牛の加工メーカー",desc_en:"Yonezawa beef processor"},
  {i:"yg007",ja:"天童木工",en:"Tendo Mokko",pref:"yamagata",cat:"wood",desc_ja:"天童の成形合板家具",desc_en:"Tendo molded plywood furniture",verified:true},
  {i:"yg008",ja:"佐藤繊維",en:"Sato Seni",pref:"yamagata",cat:"apparel",desc_ja:"寒河江のニット・モヘア紡績",desc_en:"Sagae mohair spinning & knitwear",verified:true},
  {i:"yg009",ja:"日和田 さくらんぼ農園",en:"Higoda Cherry Farm",pref:"yamagata",cat:"food",desc_ja:"山形さくらんぼ加工",desc_en:"Yamagata cherry processor",deleted:true},
  {i:"yg010",ja:"山形カロッツェリア",en:"Yamagata Carrozzeria",pref:"yamagata",cat:"leather",desc_ja:"山形の革鞄工房",desc_en:"Yamagata leather bag atelier",deleted:true},
  {i:"yg011",ja:"山形鋳物",en:"Yamagata Imono",pref:"yamagata",cat:"cutlery",desc_ja:"山形伝統の鋳物・茶釜",desc_en:"Yamagata traditional cast iron"},
  {i:"yg012",ja:"菊地保寿堂 (鋳物)",en:"Kikuchi Hojudo",pref:"yamagata",cat:"cutlery",desc_ja:"山形鋳物の名門",desc_en:"Famous Yamagata cast iron maker",verified:true},
  {i:"yg013",ja:"オリエンタルカーペット",en:"Oriental Carpet",pref:"yamagata",cat:"apparel",desc_ja:"山辺町の高級緞通",desc_en:"Yamanobe luxury hand-knotted rugs",verified:true},
  {i:"yg014",ja:"庄内米加工協同",en:"Shonai Rice",pref:"yamagata",cat:"food",desc_ja:"庄内米の加工製品",desc_en:"Shonai rice processed products",deleted:true},
  {i:"yg015",ja:"おしんの宿 銀山温泉藤屋",en:"Ginzan Onsen Fujiya",pref:"yamagata",cat:"craft",desc_ja:"山形伝統建築の改装",desc_en:"Yamagata traditional architecture"},
  {i:"yg016",ja:"高畠ワイナリー",en:"Takahata Winery",pref:"yamagata",cat:"sake",desc_ja:"高畠町のワイン",desc_en:"Takahata local winery",verified:true},
  {i:"yg017",ja:"羽州ゆべし",en:"Ushu Yubeshi",pref:"yamagata",cat:"food",desc_ja:"山形の伝統菓子ゆべし",desc_en:"Yamagata traditional yubeshi sweet",deleted:true},
  {i:"yg018",ja:"山形精密工業",en:"Yamagata Precision",pref:"yamagata",cat:"electronics",desc_ja:"精密金属加工の中小",desc_en:"Precision metalwork SME",deleted:true},

  // ========== 福島 / FUKUSHIMA ==========
  {i:"fk001",ja:"会津漆器 鈴善",en:"Suzuzen Aizu Lacquer",pref:"fukushima",cat:"craft",desc_ja:"会津塗の老舗工房",desc_en:"Heritage Aizu lacquer atelier",verified:true},
  {i:"fk002",ja:"白木屋漆器店",en:"Shirakiya Lacquer",pref:"fukushima",cat:"craft",desc_ja:"会津若松の漆器店",desc_en:"Aizu-Wakamatsu lacquer shop"},
  {i:"fk003",ja:"末廣酒造",en:"Suehiro Sake",pref:"fukushima",cat:"sake",desc_ja:"会津の老舗酒蔵",desc_en:"Aizu heritage sake brewer",verified:true},
  {i:"fk004",ja:"宮泉銘醸",en:"Miyaizumi Brewery",pref:"fukushima",cat:"sake",desc_ja:"写楽ブランドの蔵元",desc_en:"Brewer of Sharaku sake",verified:true},
  {i:"fk005",ja:"飛露喜 (廣木酒造)",en:"Hiroki Brewery (Hiroki)",pref:"fukushima",cat:"sake",desc_ja:"会津の名酒・飛露喜",desc_en:"Famous Aizu sake Hiroki",verified:true},
  {i:"fk006",ja:"大七酒造",en:"Daishichi",pref:"fukushima",cat:"sake",desc_ja:"二本松の生酛造り蔵元",desc_en:"Nihonmatsu kimoto-style brewer",verified:true},
  {i:"fk007",ja:"奥の松酒造",en:"Okunomatsu",pref:"fukushima",cat:"sake",desc_ja:"二本松の地酒",desc_en:"Nihonmatsu local sake",verified:true},
  {i:"fk008",ja:"喜多方ラーメン老麺会",en:"Kitakata Ramen Roumen",pref:"fukushima",cat:"food",desc_ja:"喜多方ラーメンの製麺",desc_en:"Kitakata ramen noodle makers"},
  {i:"fk009",ja:"会津味噌 はせがわ",en:"Hasegawa Aizu Miso",pref:"fukushima",cat:"food",desc_ja:"会津伝統の味噌・醤油",desc_en:"Aizu traditional miso & soy",deleted:true},
  {i:"fk010",ja:"赤べこ工房 山田民芸",en:"Yamada Mingei (Akabeko)",pref:"fukushima",cat:"craft",desc_ja:"会津の赤べこ郷土玩具",desc_en:"Aizu Akabeko folk toy"},
  {i:"fk011",ja:"会津本郷焼 流紋焼",en:"Aizu Hongoyaki Ryumon",pref:"fukushima",cat:"glass",desc_ja:"会津本郷焼の窯元",desc_en:"Aizu Hongo pottery kiln"},
  {i:"fk012",ja:"川連こけし",en:"Kawatsura Kokeshi (Fukushima)",pref:"fukushima",cat:"craft",desc_ja:"福島土湯系こけし",desc_en:"Fukushima Tsuchiyu kokeshi",deleted:true},
  {i:"fk013",ja:"いわき遠野ホップ",en:"Iwaki Tono Hop",pref:"fukushima",cat:"food",desc_ja:"福島産ホップのクラフトビール",desc_en:"Fukushima craft beer with local hops",deleted:true},
  {i:"fk014",ja:"郡山ニット",en:"Koriyama Knit",pref:"fukushima",cat:"apparel",desc_ja:"福島の国産ニットメーカー",desc_en:"Fukushima domestic knitwear",deleted:true},
  {i:"fk015",ja:"福島電子工業",en:"Fukushima Electronics",pref:"fukushima",cat:"electronics",desc_ja:"電子部品の中小メーカー",desc_en:"SME electronic parts maker",deleted:true},
  {i:"fk016",ja:"クリスタルアロマ郡山",en:"Crystal Aroma Koriyama",pref:"fukushima",cat:"cosmetics",desc_ja:"福島産植物アロマ化粧品",desc_en:"Fukushima botanical aromatherapy",deleted:true},
  {i:"fk017",ja:"会津身知らず柿",en:"Aizu Mishirazu Kaki",pref:"fukushima",cat:"food",desc_ja:"会津特産の柿加工",desc_en:"Aizu special persimmon products"},
  {i:"fk018",ja:"会津桐タンス",en:"Aizu Paulownia Chest",pref:"fukushima",cat:"wood",desc_ja:"会津桐の伝統箪笥",desc_en:"Aizu paulownia traditional chest"},
  {i:"fk019",ja:"福島サプリ研究所",en:"Fukushima Supplement Lab",pref:"fukushima",cat:"supplement",desc_ja:"地元植物のサプリ開発",desc_en:"Local botanical supplement maker",deleted:true},
  {i:"fk020",ja:"いわきスパリゾート工芸",en:"Iwaki Spa Craft",pref:"fukushima",cat:"craft",desc_ja:"いわきの工芸品",desc_en:"Iwaki crafts",deleted:true},

  // ========== 茨城 / IBARAKI ==========
  {i:"ib001",ja:"木内酒造 (常陸野ネスト)",en:"Kiuchi Brewery (Hitachino Nest)",pref:"ibaraki",cat:"sake",desc_ja:"常陸野ネストビールで世界的に有名",desc_en:"Globally famous Hitachino Nest Beer",verified:true},
  {i:"ib002",ja:"明利酒類",en:"Meiri Shurui",pref:"ibaraki",cat:"sake",desc_ja:"水戸の梅酒・日本酒メーカー",desc_en:"Mito plum wine & sake maker",verified:true},
  {i:"ib003",ja:"府中誉 (渡舟)",en:"Watabune (Fuchu Homare)",pref:"ibaraki",cat:"sake",desc_ja:"渡舟ブランドの蔵元",desc_en:"Brewer of Watabune sake",verified:true},
  {i:"ib004",ja:"来福酒造",en:"Raifuku Brewery",pref:"ibaraki",cat:"sake",desc_ja:"筑西の地酒蔵",desc_en:"Chikusei local sake brewer",verified:true},
  {i:"ib005",ja:"笠間焼 向山窯",en:"Mukoyama Gama Kasama",pref:"ibaraki",cat:"glass",desc_ja:"笠間焼の代表窯元",desc_en:"Famous Kasama-yaki kiln"},
  {i:"ib006",ja:"笠間芸術の森協同組合",en:"Kasama Geijutsu",pref:"ibaraki",cat:"glass",desc_ja:"笠間焼の窯元グループ",desc_en:"Kasama-yaki kiln cooperative"},
  {i:"ib007",ja:"納豆 だるま食品",en:"Daruma Natto",pref:"ibaraki",cat:"food",desc_ja:"水戸納豆の老舗",desc_en:"Heritage Mito natto"},
  {i:"ib008",ja:"水戸納豆 天狗",en:"Tengu Natto Mito",pref:"ibaraki",cat:"food",desc_ja:"水戸納豆の代表ブランド",desc_en:"Famous Mito natto brand",verified:true},
  {i:"ib009",ja:"そぼろ納豆 くぼた",en:"Kubota Soboro Natto",pref:"ibaraki",cat:"food",desc_ja:"水戸の納豆漬物",desc_en:"Mito natto pickle maker",deleted:true},
  {i:"ib010",ja:"つくばエレクトロン技研",en:"Tsukuba Electron Giken",pref:"ibaraki",cat:"electronics",desc_ja:"つくばの電子計測装置",desc_en:"Tsukuba electronic measurement"},
  {i:"ib011",ja:"日立金属研磨",en:"Hitachi Metal Polish",pref:"ibaraki",cat:"electronics",desc_ja:"日立周辺の精密金属加工",desc_en:"Hitachi-area precision metalwork",deleted:true},
  {i:"ib012",ja:"結城紬郷土館",en:"Yuki Tsumugi Atelier",pref:"ibaraki",cat:"apparel",desc_ja:"結城紬の伝統工房",desc_en:"Yuki tsumugi silk atelier"},
  {i:"ib013",ja:"結城紬本場奥順",en:"Honba Okujun Yuki",pref:"ibaraki",cat:"apparel",desc_ja:"結城紬の老舗問屋",desc_en:"Heritage Yuki tsumugi house",verified:true},
  {i:"ib014",ja:"茨城常陸太田醤油",en:"Hitachiōta Soy Sauce",pref:"ibaraki",cat:"food",desc_ja:"県北の老舗醤油蔵",desc_en:"Northern Ibaraki soy sauce"},
  {i:"ib015",ja:"鹿島水産加工",en:"Kashima Seafood",pref:"ibaraki",cat:"food",desc_ja:"鹿島の干物加工",desc_en:"Kashima dried fish processor"},
  {i:"ib016",ja:"つくば化粧品研究所",en:"Tsukuba Cosmetics Lab",pref:"ibaraki",cat:"cosmetics",desc_ja:"つくばの化粧品OEM",desc_en:"Tsukuba cosmetics OEM",deleted:true},
  {i:"ib017",ja:"水戸サプリ工場",en:"Mito Supplement",pref:"ibaraki",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"ib018",ja:"つくば植物バイオ",en:"Tsukuba Plant Bio",pref:"ibaraki",cat:"supplement",desc_ja:"植物バイオの健康素材開発",desc_en:"Plant-bio health ingredients",deleted:true},
  {i:"ib019",ja:"常陸大宮和紙",en:"Hitachi-Omiya Washi",pref:"ibaraki",cat:"paper",desc_ja:"西の内紙の伝統和紙",desc_en:"Nishinouchi traditional washi"},
  {i:"ib020",ja:"茨城刃物工房",en:"Ibaraki Cutlery Atelier",pref:"ibaraki",cat:"cutlery",desc_ja:"茨城の手打ち刃物",desc_en:"Ibaraki hand-forged cutlery",deleted:true},

  // ========== 栃木 / TOCHIGI ==========
  {i:"tg001",ja:"益子焼 つかもと",en:"Tsukamoto Mashiko",pref:"tochigi",cat:"glass",desc_ja:"益子焼の老舗窯元",desc_en:"Heritage Mashiko-yaki kiln",verified:true},
  {i:"tg002",ja:"益子焼 大誠窯",en:"Taisei Gama Mashiko",pref:"tochigi",cat:"glass",desc_ja:"益子焼の窯元",desc_en:"Mashiko-yaki kiln"},
  {i:"tg003",ja:"益子焼共販センター",en:"Mashiko Coop",pref:"tochigi",cat:"glass",desc_ja:"益子焼の販売拠点",desc_en:"Mashiko-yaki sales hub"},
  {i:"tg004",ja:"惣誉酒造",en:"Sohomare",pref:"tochigi",cat:"sake",desc_ja:"市貝の生酛造り蔵元",desc_en:"Ichikai kimoto-style brewer",verified:true},
  {i:"tg005",ja:"せんきん (仙禽)",en:"Senkin",pref:"tochigi",cat:"sake",desc_ja:"さくら市の革新派蔵元",desc_en:"Sakura City innovative brewery",verified:true},
  {i:"tg006",ja:"鳳鸞酒造",en:"Houran Brewery",pref:"tochigi",cat:"sake",desc_ja:"大田原の地酒",desc_en:"Otawara local sake",verified:true,deleted:true},
  {i:"tg007",ja:"渡邊佐平商店",en:"Watanabe Sahei",pref:"tochigi",cat:"sake",desc_ja:"日光の老舗酒蔵",desc_en:"Nikko heritage sake brewer"},
  {i:"tg008",ja:"宇都宮餃子協会連携",en:"Utsunomiya Gyoza",pref:"tochigi",cat:"food",desc_ja:"宇都宮餃子の地場メーカー",desc_en:"Utsunomiya gyoza makers"},
  {i:"tg009",ja:"日光プリン亭",en:"Nikko Purin Tei",pref:"tochigi",cat:"food",desc_ja:"日光のプリン専門",desc_en:"Nikko pudding specialist"},
  {i:"tg010",ja:"今市味噌",en:"Imaichi Miso",pref:"tochigi",cat:"food",desc_ja:"日光今市の老舗味噌",desc_en:"Imaichi heritage miso"},
  {i:"tg011",ja:"日光彫工芸組合",en:"Nikko Carving Co-op",pref:"tochigi",cat:"wood",desc_ja:"日光彫の伝統工芸",desc_en:"Nikko carving guild"},
  {i:"tg012",ja:"小砂焼 藤田製陶所",en:"Fujita Kosaago Yaki",pref:"tochigi",cat:"glass",desc_ja:"小砂焼の窯元",desc_en:"Kosago pottery kiln"},
  {i:"tg013",ja:"足利銘仙織元",en:"Ashikaga Meisen",pref:"tochigi",cat:"apparel",desc_ja:"足利銘仙の織物",desc_en:"Ashikaga meisen textile",deleted:true},
  {i:"tg014",ja:"栃木レザー",en:"Tochigi Leather",pref:"tochigi",cat:"leather",desc_ja:"国産タンニンなめし革",desc_en:"Domestic vegetable-tanned leather",verified:true},
  {i:"tg015",ja:"宇都宮電子精密",en:"Utsunomiya Precision",pref:"tochigi",cat:"electronics",desc_ja:"電子精密部品の中小",desc_en:"SME precision electronic parts",deleted:true},
  {i:"tg016",ja:"栃木健康食品研究所",en:"Tochigi Health Food Lab",pref:"tochigi",cat:"supplement",desc_ja:"いちご由来サプリ開発",desc_en:"Strawberry-derived supplements",deleted:true},
  {i:"tg017",ja:"鹿沼組子",en:"Kanuma Kumiko",pref:"tochigi",cat:"wood",desc_ja:"鹿沼の伝統組子細工",desc_en:"Kanuma kumiko wood lattice"},
  {i:"tg018",ja:"鹿沼麻織物",en:"Kanuma Asa Textile",pref:"tochigi",cat:"apparel",desc_ja:"鹿沼産麻織物",desc_en:"Kanuma hemp textile",deleted:true},

  // ========== 群馬 / GUNMA ==========
  {i:"gm001",ja:"群馬コンニャク 田中",en:"Tanaka Konjac",pref:"gunma",cat:"food",desc_ja:"下仁田のこんにゃくメーカー",desc_en:"Shimonita konjac maker",deleted:true},
  {i:"gm002",ja:"ヨコオデイリーフーズ",en:"Yokoo Daily Foods",pref:"gunma",cat:"food",desc_ja:"群馬のこんにゃく加工",desc_en:"Gunma konjac processor",verified:true},
  {i:"gm003",ja:"下仁田納豆",en:"Shimonita Natto",pref:"gunma",cat:"food",desc_ja:"下仁田の藁納豆",desc_en:"Shimonita straw-wrapped natto"},
  {i:"gm004",ja:"高崎ハム",en:"Takasaki Ham",pref:"gunma",cat:"food",desc_ja:"高崎の老舗ハム・ソーセージ",desc_en:"Heritage Takasaki ham"},
  {i:"gm005",ja:"水沢うどん 大澤屋",en:"Osawaya Mizusawa Udon",pref:"gunma",cat:"food",desc_ja:"水沢うどんの老舗",desc_en:"Heritage Mizusawa udon",verified:true},
  {i:"gm006",ja:"水沢うどん 田丸屋",en:"Tamaruya Mizusawa Udon",pref:"gunma",cat:"food",desc_ja:"創業400年の水沢うどん",desc_en:"400-year Mizusawa udon house",verified:true},
  {i:"gm007",ja:"分福酒造",en:"Bunpuku Brewery",pref:"gunma",cat:"sake",desc_ja:"館林の老舗酒蔵",desc_en:"Tatebayashi heritage sake"},
  {i:"gm008",ja:"龍神酒造",en:"Ryujin Brewery",pref:"gunma",cat:"sake",desc_ja:"群馬の地酒・尾瀬の雪どけ",desc_en:"Brewer of Oze no Yukidoke",verified:true},
  {i:"gm009",ja:"近藤酒造",en:"Kondo Brewery",pref:"gunma",cat:"sake",desc_ja:"赤城山の蔵元",desc_en:"Brewer of Akagisan sake",verified:true},
  {i:"gm010",ja:"桐生織物協同組合",en:"Kiryu Textile Coop",pref:"gunma",cat:"apparel",desc_ja:"桐生織の伝統織物",desc_en:"Kiryu traditional weaving"},
  {i:"gm011",ja:"伊勢崎銘仙",en:"Isesaki Meisen",pref:"gunma",cat:"apparel",desc_ja:"伊勢崎の銘仙織物",desc_en:"Isesaki meisen textile"},
  {i:"gm012",ja:"碓氷製糸",en:"Usui Silk Reeling",pref:"gunma",cat:"apparel",desc_ja:"安中の生糸製糸",desc_en:"Annaka silk reeling"},
  {i:"gm013",ja:"富岡シルク",en:"Tomioka Silk",pref:"gunma",cat:"apparel",desc_ja:"富岡の絹織物",desc_en:"Tomioka silk fabric"},
  {i:"gm014",ja:"高山社シルク",en:"Takayama Silk",pref:"gunma",cat:"apparel",desc_ja:"養蚕伝統地のシルク",desc_en:"Silk from sericulture heritage region",deleted:true},
  {i:"gm015",ja:"中之条木工",en:"Nakanojo Mokko",pref:"gunma",cat:"wood",desc_ja:"中之条の木工製品",desc_en:"Nakanojo woodwork",deleted:true},
  {i:"gm016",ja:"赤城牛肉店ヤマト",en:"Akagi Yamato Beef",pref:"gunma",cat:"food",desc_ja:"赤城牛・上州牛の加工",desc_en:"Akagi & Joshu beef processor",deleted:true},
  {i:"gm017",ja:"群馬電子精機",en:"Gunma Electron Seiki",pref:"gunma",cat:"electronics",desc_ja:"群馬の電子部品メーカー",desc_en:"Gunma electronic parts SME",deleted:true},
  {i:"gm018",ja:"前橋化粧品工房",en:"Maebashi Cosmetics",pref:"gunma",cat:"cosmetics",desc_ja:"群馬の化粧品OEM",desc_en:"Gunma cosmetics OEM",deleted:true},
  {i:"gm019",ja:"草津温泉湯の花",en:"Kusatsu Yu no Hana",pref:"gunma",cat:"cosmetics",desc_ja:"草津温泉素材のバス用品",desc_en:"Kusatsu onsen bath products"},

  // ========== 埼玉 / SAITAMA ==========
  {i:"st001",ja:"川越米菓 紋蔵庵",en:"Monzoan Kawagoe",pref:"saitama",cat:"food",desc_ja:"川越芋せんべいの老舗",desc_en:"Heritage Kawagoe sweet potato sembei"},
  {i:"st002",ja:"くらづくり本舗",en:"Kurazukuri Honpo",pref:"saitama",cat:"food",desc_ja:"川越の芋菓子老舗",desc_en:"Heritage Kawagoe sweet potato confectioner",verified:true},
  {i:"st003",ja:"亀屋 (川越)",en:"Kameya Kawagoe",pref:"saitama",cat:"food",desc_ja:"川越芋菓子の老舗",desc_en:"Kawagoe sweet potato confectioner",verified:true},
  {i:"st004",ja:"小川和紙工房",en:"Ogawa Washi",pref:"saitama",cat:"paper",desc_ja:"細川紙の小川町和紙",desc_en:"Ogawa-machi Hosokawa washi"},
  {i:"st005",ja:"小川町手すき和紙",en:"Ogawa Tesuki Washi",pref:"saitama",cat:"paper",desc_ja:"ユネスコ無形文化遺産和紙",desc_en:"UNESCO-listed handmade washi",verified:true},
  {i:"st006",ja:"晴雲酒造",en:"Seiun Brewery",pref:"saitama",cat:"sake",desc_ja:"小川町の地酒",desc_en:"Ogawa-machi local sake"},
  {i:"st007",ja:"小江戸鏡山酒造",en:"Kagamiyama Brewery",pref:"saitama",cat:"sake",desc_ja:"川越の地酒蔵",desc_en:"Kawagoe local sake brewer",verified:true},
  {i:"st008",ja:"神亀酒造",en:"Shinkame Brewery",pref:"saitama",cat:"sake",desc_ja:"蓮田の純米酒先駆け",desc_en:"Hasuda pioneer of all-junmai sake",verified:true},
  {i:"st009",ja:"武甲酒造",en:"Buko Brewery",pref:"saitama",cat:"sake",desc_ja:"秩父の老舗酒蔵",desc_en:"Chichibu heritage sake brewer",verified:true},
  {i:"st010",ja:"イチローズモルト (ベンチャーウイスキー)",en:"Ichiro's Malt",pref:"saitama",cat:"sake",desc_ja:"秩父の世界的ウイスキー蒸留所",desc_en:"World-famous Chichibu whisky distillery",verified:true},
  {i:"st011",ja:"秩父錦 矢尾本店",en:"Yao Honten Chichibu",pref:"saitama",cat:"sake",desc_ja:"秩父の地酒・秩父錦",desc_en:"Chichibu Nishiki sake brewer",verified:true},
  {i:"st012",ja:"行田足袋協会",en:"Gyoda Tabi",pref:"saitama",cat:"apparel",desc_ja:"行田の足袋メーカー",desc_en:"Gyoda traditional tabi sock makers"},
  {i:"st013",ja:"丸越漬物",en:"Marukoshi Pickles",pref:"saitama",cat:"food",desc_ja:"埼玉の漬物老舗",desc_en:"Saitama heritage pickle maker",deleted:true},
  {i:"st014",ja:"草加せんべい振興協議会",en:"Soka Senbei",pref:"saitama",cat:"food",desc_ja:"草加せんべいの製造者組合",desc_en:"Soka senbei rice cracker makers"},
  {i:"st015",ja:"狭山茶 中島園",en:"Nakajima-en Sayama Tea",pref:"saitama",cat:"tea",desc_ja:"狭山茶の老舗茶園",desc_en:"Heritage Sayama tea garden"},
  {i:"st016",ja:"狭山茶 関口園",en:"Sekiguchi-en Sayama",pref:"saitama",cat:"tea",desc_ja:"狭山茶の代表的茶園",desc_en:"Representative Sayama tea grower",verified:true},
  {i:"st017",ja:"狭山茶 比留間園",en:"Hiruma-en Sayama Tea",pref:"saitama",cat:"tea",desc_ja:"入間の老舗茶園",desc_en:"Heritage Iruma tea garden",verified:true},
  {i:"st018",ja:"川口鋳物協同組合",en:"Kawaguchi Cast Iron",pref:"saitama",cat:"cutlery",desc_ja:"川口の鋳物産業",desc_en:"Kawaguchi cast iron makers"},
  {i:"st019",ja:"飯能木工協同組合",en:"Hanno Mokko Coop",pref:"saitama",cat:"wood",desc_ja:"飯能の西川材家具",desc_en:"Hanno Nishikawa-timber furniture",deleted:true},
  {i:"st020",ja:"秩父銘仙",en:"Chichibu Meisen",pref:"saitama",cat:"apparel",desc_ja:"秩父銘仙の伝統織物",desc_en:"Chichibu meisen textile"},
  {i:"st021",ja:"埼玉化粧品工業",en:"Saitama Cosmetics Industry",pref:"saitama",cat:"cosmetics",desc_ja:"埼玉の化粧品OEM",desc_en:"Saitama cosmetics OEM",deleted:true},
  {i:"st022",ja:"川越サプリメント研究所",en:"Kawagoe Supplement Lab",pref:"saitama",cat:"supplement",desc_ja:"健康食品の中小メーカー",desc_en:"SME health supplement maker",deleted:true},
  {i:"st023",ja:"所沢ニットウェア",en:"Tokorozawa Knit",pref:"saitama",cat:"apparel",desc_ja:"所沢のニット工場",desc_en:"Tokorozawa knit factory",deleted:true},
  {i:"st024",ja:"越生梅林食品",en:"Ogose Bairin Foods",pref:"saitama",cat:"food",desc_ja:"越生梅の梅干し・梅酒",desc_en:"Ogose plum products",deleted:true},
  {i:"st025",ja:"埼玉電子技研",en:"Saitama Electronic Giken",pref:"saitama",cat:"electronics",desc_ja:"県南の電子部品試作",desc_en:"Southern Saitama electronic prototyping",deleted:true},

  // ========== 千葉 / CHIBA ==========
  {i:"cb001",ja:"千葉県落花生協同組合",en:"Chiba Peanut Coop",pref:"chiba",cat:"food",desc_ja:"千葉産落花生加工",desc_en:"Chiba peanut processors"},
  {i:"cb002",ja:"米屋 (なごみの米屋)",en:"Yoneya Confectionery",pref:"chiba",cat:"food",desc_ja:"成田の和菓子・栗ようかん",desc_en:"Narita confectioner, chestnut yokan",verified:true},
  {i:"cb003",ja:"オランダ家",en:"Holland-ya",pref:"chiba",cat:"food",desc_ja:"千葉の洋菓子老舗",desc_en:"Heritage Chiba Western confectioner",verified:true},
  {i:"cb004",ja:"ヒゲタ醤油",en:"Higeta Shoyu",pref:"chiba",cat:"food",desc_ja:"銚子の老舗醤油蔵",desc_en:"Heritage Choshi soy sauce brewer",verified:true},
  {i:"cb005",ja:"ヤマサ醤油",en:"Yamasa Shoyu",pref:"chiba",cat:"food",desc_ja:"銚子の老舗醤油蔵",desc_en:"Heritage Choshi soy sauce brewer",verified:true},
  {i:"cb006",ja:"宮醤油店",en:"Miya Shoyu",pref:"chiba",cat:"food",desc_ja:"富津の伝統醤油蔵",desc_en:"Futtsu traditional soy sauce",verified:true},
  {i:"cb007",ja:"ちば醤油",en:"Chiba Shoyu",pref:"chiba",cat:"food",desc_ja:"県内地場醤油メーカー",desc_en:"Local Chiba soy sauce maker"},
  {i:"cb008",ja:"飯沼本家",en:"Iinuma Honke",pref:"chiba",cat:"sake",desc_ja:"印旛の老舗酒蔵 (甲子)",desc_en:"Inba heritage brewer, Kinoene",verified:true},
  {i:"cb009",ja:"鍋店 (なべだな)",en:"Nabedana Brewery",pref:"chiba",cat:"sake",desc_ja:"成田の地酒・仁勇",desc_en:"Narita local sake, Jinyu",verified:true},
  {i:"cb010",ja:"寒菊銘醸",en:"Kankiku",pref:"chiba",cat:"sake",desc_ja:"九十九里の蔵元",desc_en:"Kujukuri sake brewer",verified:true},
  {i:"cb011",ja:"千葉電子工業",en:"Chiba Electronics",pref:"chiba",cat:"electronics",desc_ja:"千葉の電子部品",desc_en:"Chiba electronic parts",deleted:true},
  {i:"cb012",ja:"市川電気工業",en:"Ichikawa Electric Industry",pref:"chiba",cat:"electronics",desc_ja:"市川の電気部品メーカー",desc_en:"Ichikawa electrical parts",deleted:true},
  {i:"cb013",ja:"勝浦海産物加工",en:"Katsuura Kaisan",pref:"chiba",cat:"food",desc_ja:"勝浦の海産加工",desc_en:"Katsuura seafood processor",deleted:true},
  {i:"cb014",ja:"銚子水産加工",en:"Choshi Suisan Kako",pref:"chiba",cat:"food",desc_ja:"銚子の干物加工",desc_en:"Choshi dried fish processor"},
  {i:"cb015",ja:"南房総オリーブ",en:"Minamiboso Olive",pref:"chiba",cat:"food",desc_ja:"南房総のオリーブ栽培加工",desc_en:"Minamiboso olive grower & oil"},
  {i:"cb016",ja:"鴨川シーフード",en:"Kamogawa Seafood",pref:"chiba",cat:"food",desc_ja:"鴨川の海産物加工",desc_en:"Kamogawa seafood maker",deleted:true},
  {i:"cb017",ja:"千葉ニット",en:"Chiba Knit",pref:"chiba",cat:"apparel",desc_ja:"千葉の国産ニット工場",desc_en:"Chiba domestic knit factory",deleted:true},
  {i:"cb018",ja:"市原化粧品",en:"Ichihara Cosmetics",pref:"chiba",cat:"cosmetics",desc_ja:"千葉の化粧品OEM",desc_en:"Chiba cosmetics OEM",deleted:true},
  {i:"cb019",ja:"千葉漁網",en:"Chiba Gyomō",pref:"chiba",cat:"other",desc_ja:"千葉の漁網・船具",desc_en:"Chiba fishing nets & marine gear",deleted:true},
  {i:"cb020",ja:"成田ようかん本舗",en:"Narita Yokan Honpo",pref:"chiba",cat:"food",desc_ja:"成田の伝統羊羹",desc_en:"Narita traditional yokan",deleted:true},
  {i:"cb021",ja:"千葉房総木工",en:"Boso Mokko",pref:"chiba",cat:"wood",desc_ja:"房総の木工製品",desc_en:"Boso peninsula woodwork",deleted:true},
  {i:"cb022",ja:"九十九里塩",en:"Kujukuri Salt",pref:"chiba",cat:"food",desc_ja:"九十九里の天日塩",desc_en:"Kujukuri sun-dried sea salt"},
  {i:"cb023",ja:"千葉サプリ研究所",en:"Chiba Supplement Lab",pref:"chiba",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"cb024",ja:"流山みりん 万上",en:"Manjo Mirin Nagareyama",pref:"chiba",cat:"food",desc_ja:"流山のみりん発祥蔵",desc_en:"Nagareyama mirin origin brewery",verified:true},

  // ========== 東京 / TOKYO ==========
  {i:"tk001",ja:"江戸切子 堀口硝子",en:"Horiguchi Glass (Edo Kiriko)",pref:"tokyo",cat:"glass",desc_ja:"江戸切子の代表的工房",desc_en:"Famous Edo Kiriko cut glass atelier",verified:true},
  {i:"tk002",ja:"清水硝子 (江戸切子)",en:"Shimizu Glass Edo Kiriko",pref:"tokyo",cat:"glass",desc_ja:"江東区の江戸切子工房",desc_en:"Koto-ku Edo Kiriko atelier",verified:true},
  {i:"tk003",ja:"華硝 (江戸切子)",en:"Kagami Crystal Hanashyo",pref:"tokyo",cat:"glass",desc_ja:"江戸切子・伝統工芸士",desc_en:"Edo Kiriko master craftsman house",verified:true},
  {i:"tk004",ja:"木本硝子",en:"Kimoto Glass",pref:"tokyo",cat:"glass",desc_ja:"墨田の江戸切子・薄玻璃",desc_en:"Sumida Edo Kiriko & thin glass",verified:true},
  {i:"tk005",ja:"廣田硝子",en:"Hirota Glass",pref:"tokyo",cat:"glass",desc_ja:"墨田の老舗ガラスメーカー",desc_en:"Heritage Sumida glassmaker",verified:true},
  {i:"tk006",ja:"中川政七商店 東京",en:"Nakagawa Masashichi Tokyo",pref:"tokyo",cat:"craft",desc_ja:"日本工芸セレクト",desc_en:"Japanese craft selector",verified:true},
  {i:"tk007",ja:"墨田革漉き工房",en:"Sumida Leather Atelier",pref:"tokyo",cat:"leather",desc_ja:"墨田の革漉き職人",desc_en:"Sumida leather thinning specialist"},
  {i:"tk008",ja:"後藤鞄工房",en:"Goto Kaban Atelier",pref:"tokyo",cat:"leather",desc_ja:"オーダー鞄の職人工房",desc_en:"Custom leather bag atelier",deleted:true},
  {i:"tk009",ja:"土屋鞄製造所",en:"Tsuchiya Kaban",pref:"tokyo",cat:"leather",desc_ja:"足立区の革鞄メーカー",desc_en:"Adachi-ku leather bag maker",verified:true},
  {i:"tk010",ja:"濱野皮革工藝",en:"Hamano Hikaku Kogei",pref:"tokyo",cat:"leather",desc_ja:"皇室御用達の鞄工房",desc_en:"Imperial Household leather atelier",verified:true},
  {i:"tk011",ja:"銀座かなめ屋",en:"Ginza Kanameya",pref:"tokyo",cat:"craft",desc_ja:"銀座の老舗和装小物",desc_en:"Ginza heritage kimono accessories"},
  {i:"tk012",ja:"江戸組紐工房",en:"Edo Kumihimo Atelier",pref:"tokyo",cat:"craft",desc_ja:"江戸組紐の伝統工芸士",desc_en:"Edo kumihimo braid master"},
  {i:"tk013",ja:"江戸からかみ 東京松屋",en:"Tokyo Matsuya Karakami",pref:"tokyo",cat:"paper",desc_ja:"江戸からかみの老舗",desc_en:"Heritage Edo karakami paper",verified:true},
  {i:"tk014",ja:"小津和紙",en:"Ozu Washi",pref:"tokyo",cat:"paper",desc_ja:"日本橋の老舗和紙専門店",desc_en:"Nihonbashi heritage washi shop",verified:true},
  {i:"tk015",ja:"榛原 (はいばら)",en:"Haibara",pref:"tokyo",cat:"paper",desc_ja:"日本橋の和紙文具老舗",desc_en:"Nihonbashi heritage washi stationer",verified:true},
  {i:"tk016",ja:"鳩居堂 東京",en:"Kyukyodo Tokyo",pref:"tokyo",cat:"paper",desc_ja:"銀座の老舗香・文具",desc_en:"Ginza heritage incense & stationery",verified:true},
  {i:"tk017",ja:"伊場仙",en:"Ibasen",pref:"tokyo",cat:"craft",desc_ja:"江戸扇子の老舗",desc_en:"Edo folding fan heritage shop",verified:true},
  {i:"tk018",ja:"白竹堂東京",en:"Hakuchikudo Tokyo",pref:"tokyo",cat:"craft",desc_ja:"扇子の老舗",desc_en:"Heritage folding fan maker",verified:true},
  {i:"tk019",ja:"江戸結桶 樽富",en:"Tarutomi Yui-oke",pref:"tokyo",cat:"wood",desc_ja:"江戸結桶の職人",desc_en:"Edo wooden bucket craftsman",deleted:true},
  {i:"tk020",ja:"東京銀器 上川宗達",en:"Kamikawa Ginki",pref:"tokyo",cat:"craft",desc_ja:"東京銀器の伝統工芸士",desc_en:"Tokyo silverware master craftsman"},
  {i:"tk021",ja:"森銀器製作所",en:"Mori Ginki",pref:"tokyo",cat:"craft",desc_ja:"東京銀器の老舗",desc_en:"Heritage Tokyo silverware",verified:true},
  {i:"tk022",ja:"江戸べっ甲 磯貝",en:"Isogai Bekko",pref:"tokyo",cat:"craft",desc_ja:"江戸鼈甲の老舗工房",desc_en:"Heritage Edo tortoiseshell craft"},
  {i:"tk023",ja:"江戸つまみ簪 三浦工房",en:"Miura Tsumami Kanzashi",pref:"tokyo",cat:"craft",desc_ja:"つまみかんざしの工房",desc_en:"Tsumami kanzashi hair ornament",deleted:true},
  {i:"tk024",ja:"村田眼鏡舗",en:"Murata Megane",pref:"tokyo",cat:"other",desc_ja:"日本橋の眼鏡老舗",desc_en:"Nihonbashi heritage eyewear",verified:true},
  {i:"tk025",ja:"金子眼鏡 東京",en:"Kaneko Megane Tokyo",pref:"tokyo",cat:"other",desc_ja:"東京の老舗眼鏡店",desc_en:"Tokyo heritage eyewear",verified:true},
  {i:"tk026",ja:"日本橋木屋",en:"Nihonbashi Kiya",pref:"tokyo",cat:"cutlery",desc_ja:"江戸の包丁・刃物老舗",desc_en:"Heritage Edo cutlery house",verified:true},
  {i:"tk027",ja:"うぶけや",en:"Ubukeya",pref:"tokyo",cat:"cutlery",desc_ja:"江戸の刃物老舗",desc_en:"Heritage Edo blade shop",verified:true},
  {i:"tk028",ja:"刃物の菊秀",en:"Kikuhide Cutlery",pref:"tokyo",cat:"cutlery",desc_ja:"東京の包丁・鋏",desc_en:"Tokyo knives & scissors",verified:true},
  {i:"tk029",ja:"釜浅商店",en:"Kamaasa Shoten",pref:"tokyo",cat:"cutlery",desc_ja:"合羽橋の調理道具老舗",desc_en:"Kappabashi cookware heritage",verified:true},
  {i:"tk030",ja:"飯田屋",en:"Iidaya Kappabashi",pref:"tokyo",cat:"cutlery",desc_ja:"合羽橋の料理道具専門",desc_en:"Kappabashi kitchen tool specialist",verified:true},
  {i:"tk031",ja:"江戸幟 細川幟旗",en:"Hosokawa Edo Nobori",pref:"tokyo",cat:"apparel",desc_ja:"江戸幟・染物",desc_en:"Edo banner & dyeing",deleted:true},
  {i:"tk028b",ja:"東京染ものがたり博物館 富田染工芸",en:"Tomita Senkogei",pref:"tokyo",cat:"apparel",desc_ja:"東京染め小紋の老舗",desc_en:"Heritage Tokyo komon dye atelier",verified:true},
  {i:"tk032",ja:"江戸更紗 二葉苑",en:"Futabaen Sarasa",pref:"tokyo",cat:"apparel",desc_ja:"江戸更紗の染物",desc_en:"Edo sarasa dye works"},
  {i:"tk033",ja:"大野屋總本店 東京足袋",en:"Onoya Tabi",pref:"tokyo",cat:"apparel",desc_ja:"江戸足袋の老舗",desc_en:"Heritage Edo tabi maker",verified:true},
  {i:"tk034",ja:"舟和本店",en:"Funawa",pref:"tokyo",cat:"food",desc_ja:"浅草の芋ようかん老舗",desc_en:"Asakusa heritage imo-yokan",verified:true},
  {i:"tk035",ja:"亀十",en:"Kamejyu",pref:"tokyo",cat:"food",desc_ja:"浅草どら焼きの名店",desc_en:"Asakusa famous dorayaki shop",verified:true},
  {i:"tk036",ja:"とらや (羊羹)",en:"Toraya",pref:"tokyo",cat:"food",desc_ja:"室町時代の和菓子老舗",desc_en:"Muromachi-era wagashi heritage",verified:true},
  {i:"tk037",ja:"喜八堂",en:"Kihachido Senbei",pref:"tokyo",cat:"food",desc_ja:"江戸前せんべい",desc_en:"Edo-style senbei rice cracker"},
  {i:"tk038",ja:"日本橋 千疋屋総本店",en:"Sembikiya Honten",pref:"tokyo",cat:"food",desc_ja:"日本橋の高級果物老舗",desc_en:"Nihonbashi heritage fine fruits",verified:true},
  {i:"tk039",ja:"榮太樓總本鋪",en:"Eitaro Sohonpo",pref:"tokyo",cat:"food",desc_ja:"日本橋の和菓子老舗",desc_en:"Nihonbashi heritage wagashi",verified:true},
  {i:"tk040",ja:"言問団子",en:"Kototoi Dango",pref:"tokyo",cat:"food",desc_ja:"向島の老舗団子",desc_en:"Mukojima heritage dango"},
  {i:"tk041",ja:"小山園 東京",en:"Koyamaen Tokyo",pref:"tokyo",cat:"tea",desc_ja:"老舗茶舗 (東京店)",desc_en:"Heritage tea shop Tokyo branch"},
  {i:"tk042",ja:"森半 東京",en:"Morihan Tokyo",pref:"tokyo",cat:"tea",desc_ja:"老舗茶・抹茶卸",desc_en:"Heritage matcha wholesaler"},
  {i:"tk043",ja:"山本山 (日本橋)",en:"Yamamotoyama",pref:"tokyo",cat:"tea",desc_ja:"日本橋の老舗茶舗",desc_en:"Heritage Nihonbashi tea house",verified:true},
  {i:"tk044",ja:"伊藤園系列ティーパック",en:"Tokyo Tea Packaging",pref:"tokyo",cat:"tea",desc_ja:"東京のティーパック加工",desc_en:"Tokyo tea bag packaging SME"},
  {i:"tk045",ja:"明治座電子部品",en:"Meijiza Electronic Parts",pref:"tokyo",cat:"electronics",desc_ja:"中央区の電子部品試作",desc_en:"Chuo-ku electronic prototyping",deleted:true},
  {i:"tk046",ja:"大田区精密プレス",en:"Ota-ku Precision Press",pref:"tokyo",cat:"electronics",desc_ja:"大田区の金属精密加工",desc_en:"Ota-ku precision metal pressing"},
  {i:"tk047",ja:"大田区メカトロ",en:"Ota Mechatronics",pref:"tokyo",cat:"electronics",desc_ja:"大田区の試作開発",desc_en:"Ota-ku R&D prototyping",deleted:true},
  {i:"tk048",ja:"葛飾電子",en:"Katsushika Electronics",pref:"tokyo",cat:"electronics",desc_ja:"葛飾区の電子部品",desc_en:"Katsushika electronics SME",deleted:true},
  {i:"tk049",ja:"墨田精密技研",en:"Sumida Seimitsu",pref:"tokyo",cat:"electronics",desc_ja:"墨田区の精密部品",desc_en:"Sumida-ku precision parts",deleted:true},
  {i:"tk050",ja:"イシダ特許応用研究所",en:"Ishida Patent Lab",pref:"tokyo",cat:"patent",desc_ja:"医療特許技術の試作",desc_en:"Medical patent prototype lab",deleted:true},
  {i:"tk051",ja:"東京ホンダ式特許工房",en:"Tokyo Patent Atelier",pref:"tokyo",cat:"patent",desc_ja:"特許技術ライセンス試作",desc_en:"Patent technology prototyping",deleted:true},
  {i:"tk052",ja:"アイメックスソリューション",en:"Aimex Solution",pref:"tokyo",cat:"patent",desc_ja:"特許応用製品開発",desc_en:"Patent-applied product dev"},
  {i:"tk053",ja:"DR.WU TOKYO",en:"Dr.Wu Tokyo OEM",pref:"tokyo",cat:"cosmetics",desc_ja:"東京の化粧品OEM",desc_en:"Tokyo cosmetics OEM",deleted:true},
  {i:"tk054",ja:"アユーラ・ラボラトリーズ",en:"Ayura Laboratories",pref:"tokyo",cat:"cosmetics",desc_ja:"ホリスティック化粧品",desc_en:"Holistic cosmetics brand",verified:true},
  {i:"tk055",ja:"クナイプ東京",en:"Kneipp Japan Tokyo",pref:"tokyo",cat:"cosmetics",desc_ja:"バスソルト・ハーブコスメ",desc_en:"Bath salt & herbal cosmetics",deleted:true},
  {i:"tk056",ja:"OSAJI",en:"Osaji",pref:"tokyo",cat:"cosmetics",desc_ja:"敏感肌コスメブランド",desc_en:"Sensitive-skin cosmetics brand",verified:true,deleted:true},
  {i:"tk057",ja:"アンドビー",en:"&be",pref:"tokyo",cat:"cosmetics",desc_ja:"ナチュラル化粧品ブランド",desc_en:"Natural cosmetics brand",verified:true,deleted:true},
  {i:"tk058",ja:"TO/ONE",en:"TO/ONE",pref:"tokyo",cat:"cosmetics",desc_ja:"トーンの植物コスメ",desc_en:"Tone botanical cosmetics",verified:true,deleted:true},
  {i:"tk059",ja:"hince Tokyo",en:"hince Tokyo",pref:"tokyo",cat:"cosmetics",desc_ja:"K-Beauty発オリジナルコスメ",desc_en:"K-beauty cosmetics brand",deleted:true},
  {i:"tk060",ja:"うるおい工房 東京",en:"Uruoi Kobo Tokyo",pref:"tokyo",cat:"cosmetics",desc_ja:"美容液・スキンケアOEM",desc_en:"Serum & skincare OEM",deleted:true},
  {i:"tk061",ja:"ファンケル研究所東京",en:"Fancl Lab Tokyo",pref:"tokyo",cat:"supplement",desc_ja:"無添加サプリ研究",desc_en:"Additive-free supplement R&D",deleted:true},
  {i:"tk062",ja:"DHC支援サプリ工房",en:"Tokyo Supplement Atelier",pref:"tokyo",cat:"supplement",desc_ja:"サプリOEM中小メーカー",desc_en:"Supplement OEM SME",deleted:true},
  {i:"tk063",ja:"アサヒフードヘルス",en:"Asahi Food Health",pref:"tokyo",cat:"supplement",desc_ja:"健康食品研究",desc_en:"Health food research"},
  {i:"tk064",ja:"日本橋カネサ食品",en:"Nihonbashi Kanesa",pref:"tokyo",cat:"food",desc_ja:"日本橋の鰹節老舗",desc_en:"Nihonbashi heritage katsuobushi",deleted:true},
  {i:"tk065",ja:"つきじ 山長",en:"Tsukiji Yamacho",pref:"tokyo",cat:"food",desc_ja:"築地の玉子焼老舗",desc_en:"Tsukiji tamagoyaki heritage",verified:true},
  {i:"tk066",ja:"築地紀文",en:"Tsukiji Kibun",pref:"tokyo",cat:"food",desc_ja:"築地の練り物老舗",desc_en:"Tsukiji heritage fish paste"},
  {i:"tk067",ja:"江戸べんとう仕出し",en:"Edo Bento Shidashi",pref:"tokyo",cat:"food",desc_ja:"江戸前仕出し弁当",desc_en:"Edo-style catering bento"},
  {i:"tk068",ja:"福徳長酒類東京 (リキュール)",en:"Fukutokucho Liquor",pref:"tokyo",cat:"sake",desc_ja:"東京のリキュール製造",desc_en:"Tokyo liqueur producer"},
  {i:"tk069",ja:"小澤酒造 (澤乃井)",en:"Ozawa Brewery (Sawanoi)",pref:"tokyo",cat:"sake",desc_ja:"青梅の老舗酒蔵",desc_en:"Ome heritage sake brewer",verified:true},
  {i:"tk070",ja:"石川酒造",en:"Ishikawa Brewery",pref:"tokyo",cat:"sake",desc_ja:"福生の地ビール・地酒",desc_en:"Fussa craft beer & sake",verified:true},
  {i:"tk071",ja:"野崎酒造",en:"Nozaki Brewery",pref:"tokyo",cat:"sake",desc_ja:"あきる野の老舗酒蔵",desc_en:"Akiruno heritage sake",verified:true},
  {i:"tk072",ja:"田村酒造場",en:"Tamura Sake Brewery",pref:"tokyo",cat:"sake",desc_ja:"福生の老舗酒蔵",desc_en:"Fussa heritage sake brewer",verified:true},
  {i:"tk073",ja:"伊豆大島椿油 高田",en:"Oshima Camellia Oil",pref:"tokyo",cat:"cosmetics",desc_ja:"伊豆大島の椿油",desc_en:"Oshima Island camellia oil"},
  {i:"tk074",ja:"江戸木目込人形",en:"Edo Kimekomi Doll",pref:"tokyo",cat:"craft",desc_ja:"江戸木目込人形工房",desc_en:"Edo kimekomi doll atelier"},
  {i:"tk075",ja:"江戸刺繍 高橋",en:"Takahashi Edo Embroidery",pref:"tokyo",cat:"apparel",desc_ja:"江戸刺繍の伝統工芸士",desc_en:"Edo embroidery master"},
  {i:"tk076",ja:"江戸風鈴 篠原まるよし風鈴",en:"Shinohara Edo Furin",pref:"tokyo",cat:"glass",desc_ja:"江戸風鈴の工房",desc_en:"Edo wind chime atelier",verified:true},
  {i:"tk077",ja:"江戸友禅 駒井染工房",en:"Komai Edo Yuzen",pref:"tokyo",cat:"apparel",desc_ja:"江戸友禅染の工房",desc_en:"Edo yuzen dye atelier",deleted:true},
  {i:"tk078",ja:"押絵羽子板 龍玉",en:"Ryugyoku Hagoita",pref:"tokyo",cat:"craft",desc_ja:"江戸羽子板の工房",desc_en:"Edo hagoita paddle craft",deleted:true},
  {i:"tk079",ja:"老舗鼈甲 神田岩立",en:"Iwatate Bekko",pref:"tokyo",cat:"craft",desc_ja:"神田の鼈甲老舗",desc_en:"Kanda heritage bekko",deleted:true},
  {i:"tk080",ja:"江戸銀器 上田銀器",en:"Ueda Ginki",pref:"tokyo",cat:"craft",desc_ja:"江戸銀器の老舗",desc_en:"Heritage Edo silverware"},

  // ========== 神奈川 / KANAGAWA ==========
  {i:"kn001",ja:"鎌倉彫 慶 (博古堂)",en:"Hakkodo Kamakurabori",pref:"kanagawa",cat:"wood",desc_ja:"鎌倉彫の老舗工房",desc_en:"Heritage Kamakura-bori carving",verified:true},
  {i:"kn002",ja:"鎌倉彫 伝統工芸協同組合",en:"Kamakurabori Coop",pref:"kanagawa",cat:"wood",desc_ja:"鎌倉彫の協同組合",desc_en:"Kamakura-bori cooperative"},
  {i:"kn003",ja:"豊島屋 (鳩サブレー)",en:"Toshimaya Hatosable",pref:"kanagawa",cat:"food",desc_ja:"鎌倉鳩サブレーの老舗",desc_en:"Heritage Kamakura Hato Sable",verified:true},
  {i:"kn004",ja:"鎌倉紅谷",en:"Kamakura Beniya",pref:"kanagawa",cat:"food",desc_ja:"クルミッ子の鎌倉菓子店",desc_en:"Kamakura Kurumicco confectioner",verified:true},
  {i:"kn005",ja:"横浜中華街 江戸清",en:"Edosei Chuka-gai",pref:"kanagawa",cat:"food",desc_ja:"横浜中華街の老舗",desc_en:"Yokohama Chinatown heritage"},
  {i:"kn006",ja:"崎陽軒",en:"Kiyoken",pref:"kanagawa",cat:"food",desc_ja:"横浜シウマイの老舗",desc_en:"Yokohama heritage shumai",verified:true},
  {i:"kn007",ja:"横浜赤い靴洋菓子",en:"Yokohama Akaikutsu",pref:"kanagawa",cat:"food",desc_ja:"横浜の洋菓子メーカー",desc_en:"Yokohama Western confectioner"},
  {i:"kn008",ja:"小田原蒲鉾 鈴廣",en:"Suzuhiro Kamaboko",pref:"kanagawa",cat:"food",desc_ja:"小田原蒲鉾の老舗",desc_en:"Heritage Odawara kamaboko",verified:true},
  {i:"kn009",ja:"籠淸 蒲鉾",en:"Kagosei Kamaboko",pref:"kanagawa",cat:"food",desc_ja:"小田原の老舗蒲鉾",desc_en:"Odawara heritage kamaboko",verified:true},
  {i:"kn010",ja:"丸う田代",en:"Maruu Tashiro",pref:"kanagawa",cat:"food",desc_ja:"小田原の蒲鉾老舗",desc_en:"Odawara heritage kamaboko",deleted:true},
  {i:"kn011",ja:"井上蒲鉾店",en:"Inoue Kamaboko",pref:"kanagawa",cat:"food",desc_ja:"小田原の蒲鉾",desc_en:"Odawara kamaboko"},
  {i:"kn012",ja:"箱根寄木細工 露木木工所",en:"Tsuyuki Yosegi",pref:"kanagawa",cat:"wood",desc_ja:"箱根寄木細工の伝統工房",desc_en:"Hakone yosegi marquetry atelier",verified:true},
  {i:"kn013",ja:"箱根寄木細工 本間木工所",en:"Honma Yosegi",pref:"kanagawa",cat:"wood",desc_ja:"箱根寄木細工の老舗",desc_en:"Heritage Hakone yosegi"},
  {i:"kn014",ja:"小田原漆器 石川漆器",en:"Ishikawa Odawara Lacquer",pref:"kanagawa",cat:"craft",desc_ja:"小田原漆器の伝統工房",desc_en:"Odawara lacquer atelier"},
  {i:"kn015",ja:"井上スリッパ",en:"Inoue Slippers",pref:"kanagawa",cat:"apparel",desc_ja:"川崎のスリッパ・室内履き",desc_en:"Kawasaki slipper SME",deleted:true},
  {i:"kn016",ja:"横浜スカーフ協同組合",en:"Yokohama Scarf Coop",pref:"kanagawa",cat:"apparel",desc_ja:"横浜捺染スカーフ",desc_en:"Yokohama printed scarves"},
  {i:"kn017",ja:"湘南スーツ仕立",en:"Shonan Tailor",pref:"kanagawa",cat:"apparel",desc_ja:"湘南のオーダースーツ仕立",desc_en:"Shonan custom suit atelier",deleted:true},
  {i:"kn018",ja:"川崎電子機器",en:"Kawasaki Electronic Machine",pref:"kanagawa",cat:"electronics",desc_ja:"川崎の電子部品試作",desc_en:"Kawasaki electronic prototyping",deleted:true},
  {i:"kn019",ja:"横浜マリンエレクトロニクス",en:"Yokohama Marine Electronics",pref:"kanagawa",cat:"electronics",desc_ja:"船舶用電子機器",desc_en:"Marine electronic equipment",deleted:true},
  {i:"kn020",ja:"湘南化粧品研究所",en:"Shonan Cosmetic Lab",pref:"kanagawa",cat:"cosmetics",desc_ja:"湘南の化粧品OEM",desc_en:"Shonan cosmetics OEM",deleted:true},
  {i:"kn021",ja:"湯河原柑橘製造",en:"Yugawara Citrus",pref:"kanagawa",cat:"food",desc_ja:"湯河原のみかん加工",desc_en:"Yugawara citrus processor"},
  {i:"kn022",ja:"足柄茶 加藤園",en:"Kato-en Ashigara Cha",pref:"kanagawa",cat:"tea",desc_ja:"足柄茶の老舗茶園",desc_en:"Heritage Ashigara tea grower",deleted:true},
  {i:"kn023",ja:"丹沢茶 中野園",en:"Nakano-en Tanzawa Tea",pref:"kanagawa",cat:"tea",desc_ja:"丹沢茶の茶園",desc_en:"Tanzawa tea farm",deleted:true},
  {i:"kn024",ja:"川崎オフセット印刷",en:"Kawasaki Offset",pref:"kanagawa",cat:"paper",desc_ja:"川崎の印刷加工",desc_en:"Kawasaki print finishing"},
  {i:"kn025",ja:"横浜サプリ工房",en:"Yokohama Supplement Atelier",pref:"kanagawa",cat:"supplement",desc_ja:"健康食品OEM",desc_en:"Health food OEM",deleted:true},
  {i:"kn026",ja:"鎌倉宮乃醸 (酒蔵)",en:"Kamakura Brewery",pref:"kanagawa",cat:"sake",desc_ja:"鎌倉の地酒",desc_en:"Kamakura local sake",deleted:true},
  {i:"kn027",ja:"瀬戸酒造店",en:"Seto Sake Brewery",pref:"kanagawa",cat:"sake",desc_ja:"開成町の地酒蔵",desc_en:"Kaisei-machi local sake",verified:true},
  {i:"kn028",ja:"川西屋酒造店",en:"Kawanishiya Brewery",pref:"kanagawa",cat:"sake",desc_ja:"足柄の老舗酒蔵",desc_en:"Ashigara heritage brewer",verified:true},
  {i:"kn029",ja:"井上酒造",en:"Inoue Brewery",pref:"kanagawa",cat:"sake",desc_ja:"小田原の地酒蔵",desc_en:"Odawara local brewer"},
  {i:"kn030",ja:"川崎ハム工房",en:"Kawasaki Ham Atelier",pref:"kanagawa",cat:"food",desc_ja:"国産豚のハム・ソーセージ",desc_en:"Domestic pork ham & sausage",deleted:true},
];
// 中部以降は data2.js に分割（読み込み順: data.js → data2.js → ogp.js → app.js）

